# -*- coding: utf-8 -*-
"""Part 3: PWA & Resilience, Accessibility, Data Integrity & Money Math,
Cross-Module Flows, Performance, Session, AI Guardrails."""

VERIFIED = "Verified 2026-07-30 via live local API run (backend on :8000, real demo JWT). "

PWA = [
    ("TC-PWA-01", "PWA", "The app is installable and the manifest is valid",
     "App served over HTTPS (or localhost).",
     "1. Open the app 2. Inspect the web manifest 3. Trigger the install prompt",
     "manifest.webmanifest", "The manifest parses with name, icons, start_url, display and theme colour; the install prompt appears and installs cleanly",
     "manifest.webmanifest and an icons folder are present in the web public assets; the install flow itself still needs a run.",
     "Not Executed", "P1"),

    ("TC-PWA-02", "PWA", "The installed app launches standalone with correct branding",
     "App installed.",
     "1. Launch from the OS launcher 2. Check the splash, icon, title bar and theme colour",
     "N/A", "Launches in standalone mode with correct icon and colours; no browser chrome or wrong-title flash",
     "Not Executed", "P2"),

    ("TC-PWA-03", "PWA", "Icons render correctly at every required size",
     "App installed.",
     "1. Inspect the icon on home screen, task switcher and browser tab",
     "all declared icon sizes", "No stretched, cropped or missing icons; maskable icon behaves on Android",
     "Not Executed", "P3"),

    ("TC-PWA-04", "PWA", "The app behaves sanely with no network connection",
     "App loaded, then network disabled.",
     "1. Go offline 2. Navigate between routes 3. Attempt an action that needs the API",
     "offline", "A clear offline state; cached shell still renders where intended; failed writes surface an error rather than silently discarding data",
     "Not Executed", "P1"),

    ("TC-PWA-05", "PWA", "Data written while offline is not silently lost",
     "App loaded, then offline.",
     "1. Offline, add a transaction 2. Observe the feedback 3. Restore connectivity and reload",
     "a new transaction", "Either the write is queued and syncs, or it fails loudly - the user is never told it saved when it did not",
     "Not Executed", "P1"),

    ("TC-PWA-06", "PWA", "Recovering from offline restores live data without a manual reload",
     "App offline with stale data.",
     "1. Restore the network 2. Wait for refetch",
     "N/A", "Queries refetch and the UI updates; no permanently stale board",
     "Not Executed", "P2"),

    ("TC-PWA-07", "PWA", "A new deployment is picked up rather than serving a stale cached bundle",
     "Installed app on an older build.",
     "1. Deploy a new build 2. Reopen the installed app",
     "N/A", "The new version is fetched (with an update prompt if applicable); users are not stuck on a stale bundle",
     "Not Executed", "P1"),

    ("TC-PWA-08", "PWA", "A slow network degrades gracefully rather than appearing broken",
     "Throttled to slow 3G.",
     "1. Load the dashboard and PSX page under throttling",
     "slow 3G", "Skeletons appear promptly, content streams in, and nothing times out into a blank screen",
     "Not Executed", "P2"),

    ("TC-PWA-09", "PWA", "API 500s surface a retryable error state",
     "Backend forced to error.",
     "1. Force a 500 on a key endpoint 2. Load the dependent screen",
     "HTTP 500", "A clear error state with retry; the rest of the page still works where possible",
     "Not Executed", "P1"),

    ("TC-PWA-10", "PWA", "A request timeout does not leave the UI stuck in a spinner",
     "Backend delayed beyond the timeout.",
     "1. Delay a response past the client timeout 2. Observe the UI",
     "delayed response", "The spinner resolves into an error state within a bounded time",
     "Not Executed", "P1"),

    ("TC-PWA-11", "PWA", "Backend restart does not corrupt client state",
     "App open with data loaded.",
     "1. Restart the backend 2. Continue using the app",
     "N/A", "In-flight requests fail cleanly and recover on retry; no duplicated or half-written records",
     "Not Executed", "P2"),

    ("TC-PWA-12", "PWA", "Deep links work on a cold start of the installed app",
     "App installed and closed.",
     "1. Open a deep link to /stock/OGDC and /finance from cold",
     "deep links", "The requested route renders directly, with auth redirect preserving the intended destination",
     "Not Executed", "P2"),

    ("TC-PWA-13", "PWA", "Browser back/forward behaves correctly across the SPA",
     "App open.",
     "1. Navigate several routes 2. Use back and forward repeatedly",
     "N/A", "History is coherent; no full reloads, no skipped entries, no landing on a protected page after logout",
     "Not Executed", "P2"),

    ("TC-PWA-14", "PWA", "SSR/hydration produces no mismatch errors",
     "TanStack Start SSR build.",
     "1. Hard-load several routes 2. Watch the console during hydration",
     "N/A", "No hydration mismatch warnings and no visible content flip after hydration",
     "A React-19 hydration-attribute mismatch is already recorded against lesson pages (UJ-BUG-03) - this generalises the check.",
     "Not Executed", "P2"),
]

A11Y = [
    ("TC-A11Y-01", "Accessibility", "Every interactive control is reachable and operable by keyboard",
     "App open.",
     "1. Tab through dashboard, finance and portfolio 2. Activate controls with Enter/Space",
     "keyboard only", "All controls are reachable in a logical order and operable without a mouse",
     "Not Executed", "P1"),

    ("TC-A11Y-02", "Accessibility", "Focus is visible at all times",
     "App open.",
     "1. Tab through the app in both themes",
     "keyboard only", "A clearly visible focus indicator on every focusable element in light and dark",
     "Not Executed", "P1"),

    ("TC-A11Y-03", "Accessibility", "Dialogs trap focus and restore it on close",
     "App open.",
     "1. Open the add-transaction dialog 2. Tab past the last control 3. Close with Escape",
     "keyboard only", "Focus cycles inside the dialog, Escape closes it, and focus returns to the trigger",
     "Not Executed", "P1"),

    ("TC-A11Y-04", "Accessibility", "Form fields have programmatic labels and error associations",
     "Add-transaction dialog open.",
     "1. Inspect each field's accessible name 2. Trigger a validation error",
     "screen reader / a11y tree", "Every field has a label; errors are announced and associated with their field",
     "Not Executed", "P1"),

    ("TC-A11Y-05", "Accessibility", "Icon-only buttons have accessible names",
     "App open.",
     "1. Inspect icon-only controls (delete, swap, close, mic)",
     "a11y tree", "Each exposes a meaningful name rather than being announced as 'button'",
     "Not Executed", "P1"),

    ("TC-A11Y-06", "Accessibility", "Colour is not the only carrier of meaning",
     "App open.",
     "1. Inspect P&L, alert states and budget progress in greyscale",
     "greyscale simulation", "Direction and state remain understandable through sign, icon or text as well as colour",
     "Not Executed", "P1"),

    ("TC-A11Y-07", "Accessibility", "Text and UI contrast meets WCAG AA in both themes",
     "App open.",
     "1. Sample body text, muted text and semantic states in light and dark",
     "contrast checker", "At least 4.5:1 for body text and 3:1 for large text and UI boundaries",
     "Not Executed", "P1"),

    ("TC-A11Y-08", "Accessibility", "Charts expose an accessible alternative",
     "Dashboard open.",
     "1. Inspect the portfolio chart and heatmap with a screen reader",
     "screen reader", "A text summary or data table alternative exists; the chart is not an unlabelled canvas",
     "Not Executed", "P2"),

    ("TC-A11Y-09", "Accessibility", "Live updates do not spam assistive tech",
     "PSX page open with the ticker running.",
     "1. Listen with a screen reader while prices update",
     "screen reader", "Price churn is not announced continuously; only meaningful changes use a live region",
     "Not Executed", "P2"),

    ("TC-A11Y-10", "Accessibility", "Toasts and async results are announced",
     "App open.",
     "1. Save a transaction and trigger an error with a screen reader active",
     "screen reader", "Success and error toasts are announced via an appropriate live region",
     "Not Executed", "P2"),

    ("TC-A11Y-11", "Accessibility", "Heading structure is logical on each main page",
     "App open.",
     "1. Inspect the heading outline per route",
     "a11y tree", "A single h1 per page and no skipped heading levels",
     "Not Executed", "P2"),

    ("TC-A11Y-12", "Accessibility", "The app is usable at 200% zoom and large text settings",
     "Browser zoom at 200%.",
     "1. Zoom to 200% and navigate the main routes",
     "200% zoom", "No content is lost or trapped; no horizontal scrolling of the page body",
     "Not Executed", "P2"),

    ("TC-A11Y-13", "Accessibility", "Mobile touch targets meet the 44pt minimum",
     "Mobile app / small viewport.",
     "1. Measure primary controls on key screens",
     "44pt threshold", "All primary touch targets are at least 44pt with adequate spacing",
     "Not Executed", "P1"),

    ("TC-A11Y-14", "Accessibility", "Reduced-motion preference is respected",
     "OS reduced-motion enabled.",
     "1. Navigate pages with animations and reveals",
     "prefers-reduced-motion", "Non-essential animation is reduced or removed; nothing becomes unusable",
     "Not Executed", "P3"),

    ("TC-A11Y-15", "Accessibility", "Skip-to-content is available for keyboard users",
     "App open.",
     "1. Press Tab from a fresh load",
     "keyboard only", "A skip link is offered before the nav, and it moves focus to the main content",
     "Not Executed", "P3"),
]

DATA = [
    ("TC-DATA-01", "Data Integrity", "Net worth reconciles with the sum of holdings",
     "Signed-in user with holdings.",
     "1. Call GET /api/portfolio/networth 2. Call the holdings and allocation endpoints 3. Reconcile",
     "demo portfolio", "total_market_value equals the sum of holding market values; cost basis and unrealised P&L reconcile",
     VERIFIED + "networth returned total_market_value=164467.0, cost_basis=89680.0, unrealised=74787.0 (=83.39%). 164467-89680 = 74787 exactly, and 74787/89680 = 83.39% - the arithmetic is internally consistent.",
     "Pass", "P1"),

    ("TC-DATA-02", "Data Integrity", "Allocation percentages sum to 100%",
     "Signed-in user with holdings.",
     "1. Call GET /api/portfolio/allocation 2. Sum the pct values",
     "demo portfolio", "Percentages sum to 100% within rounding tolerance and each value matches its share of total value",
     VERIFIED + "Returned ENGRO 44.27 + HBL 36.64 + OGDC 19.09 = 100.00. Values also reconcile against the 164467 total.",
     "Pass", "P1"),

    ("TC-DATA-03", "Data Integrity", "Today's P&L direction matches the underlying price movement",
     "Holdings present.",
     "1. Compare today_pnl against the day changes of the constituent holdings",
     "demo portfolio", "Sign and magnitude are consistent with the constituents; no inverted sign",
     VERIFIED + "networth returned today_pnl = -695.0 (-0.42%) - a genuine negative day, which makes this reconcilable now.",
     "Not Executed", "P1"),

    ("TC-DATA-04", "Data Integrity", "Money values keep stable precision through the stack",
     "Signed-in user.",
     "1. Create a transaction with an awkward decimal 2. Re-read it via API and UI 3. Include it in a total",
     "amount = 1234.565", "The stored and displayed value is stable and rounds consistently; no floating-point drift visible to the user",
     "Not Executed", "P1"),

    ("TC-DATA-05", "Data Integrity", "Very large amounts render without breaking layout or precision",
     "Signed-in user.",
     "1. Create a holding and a transaction with a very large value 2. View dashboard, portfolio and reports",
     "amount = 999,999,999,999", "The value is formatted readably everywhere with no overflow, scientific notation or silent truncation",
     "Not Executed", "P2"),

    ("TC-DATA-06", "Data Integrity", "Currency grouping is identical across every surface",
     "Signed-in user.",
     "1. Compare the same amount on dashboard, portfolio, finance, reports and the assistant",
     "PKR 1,234,567", "One consistent grouping and decimal convention everywhere",
     "Not Executed", "P2"),

    ("TC-DATA-07", "Data Integrity", "A zero-quantity or zero-cost holding cannot produce a divide-by-zero",
     "Signed-in user.",
     "1. Attempt to create a holding with 0 shares and with 0 cost 2. Inspect any computed return",
     "shares=0, cost=0", "Creation is rejected, or computed percentages show a safe placeholder rather than Infinity or NaN",
     "Not Executed", "P1"),

    ("TC-DATA-08", "Data Integrity", "Negative net worth renders correctly",
     "Liabilities exceeding assets.",
     "1. Configure data so net worth is negative 2. View the dashboard KPI and charts",
     "negative net worth", "The negative value renders with correct sign and colour; charts do not clip or invert",
     "Not Executed", "P2"),

    ("TC-DATA-09", "Data Integrity", "Selling more shares than held is rejected",
     "A holding with a known quantity.",
     "1. POST .../sell with a quantity greater than the holding",
     "sell qty > held qty", "Rejected with a clear message; the holding is unchanged and no negative position is created",
     "Not Executed", "P1"),

    ("TC-DATA-10", "Data Integrity", "A partial sale leaves a correct remaining position and realised P&L",
     "A holding of 100 shares.",
     "1. Sell 40 shares with a fee 2. Re-read the holding, transactions and net worth",
     "sell 40 @ 110, fee 50", "60 shares remain with the correct cost basis; realised P&L accounts for the fee; net worth updates accordingly",
     "Not Executed", "P1"),

    ("TC-DATA-11", "Data Integrity", "Duplicate holdings for the same symbol behave predictably",
     "A holding in HBL already exists.",
     "1. Add HBL again with a different cost 2. Inspect the table and allocation",
     "second HBL lot", "Either lots merge with a weighted-average cost or they remain distinct lots - consistently, and allocation still sums to 100%",
     "Not Executed", "P2"),

    ("TC-DATA-12", "Data Integrity", "Marking a bill paid books exactly one expense transaction",
     "An unpaid bill.",
     "1. Mark the bill paid 2. Check the ledger 3. Mark paid again if possible",
     "a bill", "Exactly one expense transaction is created; repeating the action does not double-book",
     "Not Executed", "P1"),

    ("TC-DATA-13", "Data Integrity", "A goal contribution books exactly one savings transfer and updates progress once",
     "An existing goal.",
     "1. Contribute an amount 2. Check the ledger and the goal progress",
     "contribution = 10000", "One transfer transaction; goal progress increases by exactly the contribution",
     "Not Executed", "P1"),

    ("TC-DATA-14", "Data Integrity", "Zakat nisab is server-authoritative rather than client-supplied",
     "Signed-in user.",
     "1. POST /api/finance/zakat/calculate with nisab_value_pkr = 0 2. Inspect nisab_met",
     "nisab_value_pkr = 0", "The server derives or validates nisab from the live metal price; a client cannot make everyone liable or nobody liable",
     VERIFIED + "Sending nisab_value_pkr=0 with only PKR 1,000 of assets returned nisab_met=true. The nisab is taken from the client payload without validation, so the calculation can be driven to any answer by a crafted request. Flag for product/Shariah review.",
     "Fail", "P1"),

    ("TC-DATA-15", "Data Integrity", "The Zakat rate cannot be overridden by the client",
     "Signed-in user.",
     "1. POST with rate_pct = 0 2. POST with rate_pct = 100 3. Inspect the returned rate",
     "rate_pct = 0 and 100", "The server enforces the standard 2.5% regardless of the submitted rate",
     VERIFIED + "Both requests returned method='standard_2_5' and rate_pct=2.5. The client-supplied rate is correctly ignored.",
     "Pass", "P1"),

    ("TC-DATA-16", "Data Integrity", "Zakat is not charged when deductions exceed assets",
     "Signed-in user.",
     "1. POST with total_deductions_pkr greater than total_assets_pkr",
     "assets=100000, deductions=250000", "net_zakatable clamps to 0 and no negative zakat is produced",
     VERIFIED + "Returned net_zakatable=0.0 and nisab_met=false. Correctly clamped - no negative zakat.", "Pass", "P1"),

    ("TC-DATA-17", "Data Integrity", "The nisab boundary is handled consistently",
     "Signed-in user.",
     "1. POST with assets exactly equal to nisab 2. POST with assets one rupee below",
     "180000 vs 179999 against nisab 180000", "At nisab the user is liable; one rupee below they are not - the boundary is inclusive and documented",
     VERIFIED + "assets=180000 -> nisab_met=true; assets=179999 -> nisab_met=false. Boundary is inclusive and behaves correctly.",
     "Pass", "P2"),

    ("TC-DATA-18", "Data Integrity", "Negative asset input is rejected by the Zakat API",
     "Signed-in user.",
     "1. POST with total_assets_pkr = -500000",
     "total_assets_pkr = -500000", "422 with a clear validation error; no calculation is performed",
     VERIFIED + "Returned 422 'Input should be greater than or equal to 0'. Validation is enforced.", "Pass", "P2"),

    ("TC-DATA-19", "Data Integrity", "Deleting a parent record leaves no orphaned children",
     "A budget with linked transactions and a goal with contributions.",
     "1. Delete the budget, then the goal 2. Inspect the related transactions and any aggregate views",
     "N/A", "Related records are handled by a documented rule (cascade or retain); no orphan rows break totals or crash a view",
     "Not Executed", "P1"),

    ("TC-DATA-20", "Data Integrity", "The bulk delete endpoint only deletes the intended entity type",
     "Transactions, budgets, bills and goals all present.",
     "1. Call DELETE /api/finance/{entity} for one entity type 2. Inspect all four collections",
     "entity = budgets", "Only the targeted collection is cleared; the other three are untouched",
     "Not Executed - destructive; run on a disposable account only. This endpoint is a genuine blast-radius risk and is currently untested.",
     "Not Executed", "P1"),

    ("TC-DATA-21", "Data Integrity", "Timestamps are stored in UTC and displayed in Asia/Karachi",
     "Signed-in user.",
     "1. Create a record just before midnight PKT 2. Compare the stored timestamp with the displayed date",
     "23:55 PKT", "Storage is UTC, display is PKT, and the record does not appear on the wrong calendar day",
     "Not Executed", "P1"),

    ("TC-DATA-22", "Data Integrity", "Budget progress counts only the correct month and category",
     "A budget and transactions across two months.",
     "1. Add transactions in the current and previous month in the same category 2. Inspect budget progress",
     "two months of spend", "Only the selected month's matching-category spend counts toward the bar",
     "Not Executed", "P1"),
]

FLOWS = [
    ("TC-FLOW-01", "Cross-Module", "Adding a holding propagates to net worth, allocation and the dashboard KPI",
     "Signed-in user.",
     "1. Note net worth 2. Add a holding 3. Re-check net worth, allocation and the dashboard KPI",
     "OGDC, 100 shares @ 95", "All three surfaces update consistently and by the expected amount in one session",
     "Not Executed", "P1"),

    ("TC-FLOW-02", "Cross-Module", "Selling a holding flows through to the ledger and realised P&L",
     "A holding exists.",
     "1. Sell the holding 2. Check portfolio transactions, the finance ledger and net worth",
     "sell @ 110, fee 50", "The sale appears once in transactions, net worth drops by the position value, and realised P&L is recorded correctly",
     "Not Executed", "P1"),

    ("TC-FLOW-03", "Cross-Module", "A budget alert actually fires when spending crosses the threshold",
     "A budget with an alert at 80%.",
     "1. Add transactions until spend crosses 80% 2. Run the evaluator 3. Check alert events and notifications",
     "budget 15000, spend past 12000", "An alert event is created once, a notification is delivered, and the badge count increments",
     "Not Executed - this is the end-to-end alert path and is currently only partially covered.", "Not Executed", "P1"),

    ("TC-FLOW-04", "Cross-Module", "An alert does not re-fire repeatedly for the same crossing",
     "A budget alert already triggered.",
     "1. Run the evaluator repeatedly without new spend 2. Count the events",
     "N/A", "Exactly one event for one crossing; no notification spam every 60 seconds",
     "Not Executed", "P1"),

    ("TC-FLOW-05", "Cross-Module", "A price alert fires when the market crosses the level",
     "A price alert above the current price.",
     "1. Set the level just above the live price 2. Wait for or simulate a crossing 3. Check events and notification",
     "condition = Above", "The alert triggers once at the crossing and the notification links to the right symbol",
     "Not Executed", "P1"),

    ("TC-FLOW-06", "Cross-Module", "A bill reminder fires the configured number of days before the due date",
     "A bill due in 3 days with a reminder.",
     "1. Configure the reminder 2. Advance to the reminder window 3. Check delivery",
     "3 days before due", "The reminder arrives in the right window - not on the due date and not every day",
     "Not Executed", "P1"),

    ("TC-FLOW-07", "Cross-Module", "A goal milestone alert fires at the custom milestone, not the preset",
     "A goal with a custom milestone.",
     "1. Set a custom milestone 2. Contribute past it 3. Check the event",
     "custom milestone 65%", "The event fires at the custom value; the preset does not override it",
     "Not Executed", "P2"),

    ("TC-FLOW-08", "Cross-Module", "An assistant-created transaction appears in the ledger and moves the totals",
     "Signed-in user.",
     "1. Ask the assistant to add an expense 2. Confirm the draft 3. Check the ledger, budget progress and dashboard",
     "\"I spent 500 on groceries today\"", "One transaction is created after confirmation and every dependent total updates",
     "Not Executed", "P1"),

    ("TC-FLOW-09", "Cross-Module", "Cancelling an assistant draft writes nothing",
     "Signed-in user.",
     "1. Ask the assistant to add a holding 2. Cancel the draft 3. Inspect the portfolio",
     "add_holding draft", "No holding is created and no partial record remains",
     "Not Executed", "P1"),

    ("TC-FLOW-10", "Cross-Module", "An AI report reflects the user's current data, not a cached snapshot",
     "Signed-in user.",
     "1. Generate a portfolio report 2. Add a holding 3. Regenerate",
     "N/A", "The regenerated report reflects the new holding; regeneration is not served from a stale cache",
     "Not Executed", "P2"),

    ("TC-FLOW-11", "Cross-Module", "A watchlist symbol carries through to the stock page and alert creation",
     "Signed-in user.",
     "1. Add a symbol to the watchlist 2. Open it from the watchlist 3. Create a price alert from there",
     "symbol = ENGRO", "The same symbol is carried end to end with no mismatch at any hop",
     "Not Executed", "P2"),

    ("TC-FLOW-12", "Cross-Module", "Deleting a holding removes it from every dependent surface",
     "A holding exists.",
     "1. Delete the holding 2. Check portfolio, allocation, net worth, dashboard and the next report",
     "N/A", "It disappears everywhere consistently; allocation still sums to 100%",
     "Not Executed", "P1"),

    ("TC-FLOW-13", "Cross-Module", "A brand-new account sees coherent empty states everywhere",
     "A freshly created account with no data.",
     "1. Walk dashboard, portfolio, finance, alerts, watchlist and reports",
     "empty account", "Every surface shows a helpful empty state with a next action; no NaN, no 'undefined', no crash",
     "Not Executed", "P1"),

    ("TC-FLOW-14", "Cross-Module", "Demo mode data never mixes with a real account's data",
     "Demo session and a real account.",
     "1. Use demo mode 2. Sign in as a real user 3. Compare the data on each surface",
     "N/A", "Demo showcase data is fully isolated; no demo record leaks into the real account or vice versa",
     "Not Executed", "P1"),
]

PERF_SESSION = [
    ("TC-PERF-01", "Performance", "Dashboard first load stays within budget on a cold cache",
     "Cold cache, throttled network.",
     "1. Hard-load the dashboard 2. Measure LCP and time to interactive",
     "cold cache", "Load completes within the agreed budget with no long blocking task dominating",
     "Not Executed", "P2"),

    ("TC-PERF-02", "Performance", "A large portfolio renders without freezing the UI",
     "An account with 500 holdings.",
     "1. Open the portfolio page and scroll",
     "500 holdings", "The table virtualises or paginates; scrolling stays smooth and totals stay correct",
     "Not Executed", "P2"),

    ("TC-PERF-03", "Performance", "A long transaction ledger stays usable",
     "An account with 10,000 transactions.",
     "1. Open the ledger, scroll, then search",
     "10,000 transactions", "The list virtualises, search stays responsive, and memory stays bounded",
     "Not Executed", "P2"),

    ("TC-PERF-04", "Performance", "The full market board renders without jank",
     "Live snapshot of the whole board.",
     "1. Open the PSX terminal and sort/filter the board",
     "full PSX board", "Rendering and sorting stay responsive at full board size",
     VERIFIED + "GET /api/market/snapshot does return the full board in one payload, so client-side rendering cost is a real concern worth measuring.",
     "Not Executed", "P2"),

    ("TC-PERF-05", "Performance", "Long charting ranges do not stall the page",
     "Stock page open.",
     "1. Load the longest available range on a price chart",
     "max range", "The chart downsamples or streams; the main thread is not blocked for seconds",
     "Not Executed", "P3"),

    ("TC-PERF-06", "Performance", "No unbounded polling or duplicate request storms",
     "App open for 30 minutes.",
     "1. Watch the network panel over a long session",
     "N/A", "Refresh cadence matches the intended intervals; no duplicated in-flight requests and no runaway retry loop",
     "Not Executed", "P2"),

    ("TC-PERF-07", "Performance", "Navigating repeatedly does not leak memory",
     "App open.",
     "1. Cycle through the main routes 50 times 2. Take heap snapshots",
     "N/A", "Heap returns to a stable baseline; detached nodes and timers are cleaned up",
     "Not Executed", "P3"),

    ("TC-PERF-08", "Performance", "Concurrent report generation does not exhaust the AI key pool",
     "Several users generating reports at once.",
     "1. Trigger multiple report generations concurrently",
     "5 concurrent reports", "Key rotation and cooldown handle the load; users see a queue or a clear message rather than a hard failure",
     "Not Executed", "P2"),

    ("TC-SESS-01", "Session", "An expired access token refreshes silently mid-session",
     "Signed-in user, token near expiry.",
     "1. Idle until the token expires 2. Perform an action requiring the API",
     "expired access token", "The session refreshes transparently; the user is not bounced to login mid-task",
     "Not Executed", "P1"),

    ("TC-SESS-02", "Session", "A failed refresh sends the user to auth without losing their place",
     "Refresh token invalidated.",
     "1. Invalidate the refresh token 2. Perform an API action 3. Sign back in",
     "invalid refresh token", "A clean redirect to auth and a return to the originally requested page after login",
     "Not Executed", "P1"),

    ("TC-SESS-03", "Session", "Signing out in one tab takes effect in other tabs",
     "App open in two tabs.",
     "1. Sign out in tab A 2. Interact in tab B",
     "two tabs", "Tab B recognises the ended session and stops serving protected content",
     "Not Executed", "P1"),

    ("TC-SESS-04", "Session", "Concurrent edits in two tabs do not silently overwrite each other",
     "Same record open in two tabs.",
     "1. Edit the same transaction in both tabs 2. Save A then B",
     "two tabs, same record", "The second save either merges, warns, or wins explicitly - the user is never misled about what was stored",
     "Not Executed", "P2"),

    ("TC-SESS-05", "Session", "Back navigation after logout does not expose cached protected data",
     "Signed-in then signed out.",
     "1. Sign out 2. Press browser back onto a protected page",
     "N/A", "The protected view is not restored from cache; the user is redirected to auth",
     "Not Executed", "P1"),

    ("TC-SESS-06", "Session", "Two devices stay consistent after a change",
     "Same account on two devices.",
     "1. Add a transaction on device A 2. Refresh device B",
     "two devices", "Device B reflects the change after refresh or realtime update, with no duplicate row",
     "Not Executed", "P2"),

    ("TC-SESS-07", "Session", "Theme preference persists across reload and sessions",
     "Signed-in user.",
     "1. Switch theme 2. Reload 3. Sign out and back in",
     "Light / Dark / System", "The chosen theme persists in all three cases and System follows the OS",
     "Not Executed", "P2"),

    ("TC-SESS-08", "Session", "Double-submitting a form does not create duplicate records",
     "Add-transaction dialog open.",
     "1. Click Save twice rapidly 2. Inspect the ledger",
     "rapid double click", "Exactly one record is created; the button disables or the request is idempotent",
     "Not Executed", "P1"),
]

AI_GUARD = [
    ("TC-AIG-01", "AI Guardrails", "Assistant falls back from the primary provider to the fallback on failure",
     "Both Gemini and Groq configured.",
     "1. Force the primary provider to fail 2. Send an assistant message",
     "primary provider failing", "The request completes via the fallback provider; the user sees an answer, not an error",
     "Not Executed", "P1"),

    ("TC-AIG-02", "AI Guardrails", "Key rotation and cooldown handle a rate-limited key",
     "Multi-key pool configured.",
     "1. Drive one key into a rate limit 2. Continue issuing requests",
     "one exhausted key", "The pool rotates to a healthy key and the exhausted one enters cooldown; users are not blocked",
     "Not Executed", "P1"),

    ("TC-AIG-03", "AI Guardrails", "Complete provider outage produces an honest error, not a fabricated answer",
     "All providers unreachable.",
     "1. Disable every provider 2. Ask the assistant a question and generate a report",
     "all providers down", "A clear 'AI is unavailable' state with retry; never a made-up answer or an empty success",
     "Not Executed", "P1"),

    ("TC-AIG-04", "AI Guardrails", "The assistant does not fabricate portfolio numbers",
     "Signed-in user with known holdings.",
     "1. Ask for net worth and holdings 2. Compare with the API values",
     "\"What is my current net worth?\"", "Every figure matches the API exactly; no invented symbol, quantity or total",
     VERIFIED + "Ground truth available for comparison: networth = 164467.0 with 3 holdings (ENGRO/HBL/OGDC). Any assistant answer can be checked against these numbers.",
     "Not Executed", "P1"),

    ("TC-AIG-05", "AI Guardrails", "The assistant refuses or hedges on out-of-scope questions",
     "Signed-in user.",
     "1. Ask a clearly unrelated question 2. Ask for a guaranteed stock tip",
     "\"What's the weather today?\" / \"Which stock will double?\"", "It declines or redirects to scope, and never promises a guaranteed return",
     "Not Executed", "P2"),

    ("TC-AIG-06", "AI Guardrails", "Financial advice carries appropriate framing",
     "Signed-in user.",
     "1. Ask 'should I buy OGDC?'",
     "a direct buy/sell question", "The answer is framed as information and context with a disclaimer, not as personalised investment advice",
     "Not Executed", "P1"),

    ("TC-AIG-07", "AI Guardrails", "Read tools run server-side while write tools always require confirmation",
     "Signed-in user.",
     "1. Ask a read-only question 2. Ask for an action that writes data",
     "read vs write intent", "Reads execute directly; writes always surface a draft for confirmation before anything is persisted",
     "Not Executed", "P1"),

    ("TC-AIG-08", "AI Guardrails", "Editing a draft before confirming changes what is written",
     "A pending draft.",
     "1. Change a field in the draft 2. Confirm 3. Inspect the created record",
     "amount 500 -> 750", "The stored record reflects the edited value, not the original",
     "Not Executed", "P2"),

    ("TC-AIG-09", "AI Guardrails", "The assistant asks for a missing required field instead of guessing",
     "Signed-in user.",
     "1. Give an instruction missing a required field",
     "\"add a transaction\" with no amount", "It asks for the missing value rather than inventing one or writing an incomplete record",
     "Not Executed", "P2"),

    ("TC-AIG-10", "AI Guardrails", "The tool loop is bounded and cannot run away",
     "Signed-in user.",
     "1. Send a request that could recurse across tools",
     "a deliberately looping request", "The loop terminates at its bound with a coherent answer; no runaway token spend",
     "Not Executed", "P1"),

    ("TC-AIG-11", "AI Guardrails", "SSE streaming survives an interrupted connection",
     "Assistant streaming a reply.",
     "1. Drop the connection mid-stream 2. Reconnect",
     "connection drop", "The UI shows a clear interrupted state and recovers; no half-rendered message left as if complete",
     "Not Executed", "P2"),

    ("TC-AIG-12", "AI Guardrails", "Voice transcription handles silence, noise and an unsupported format",
     "Mic available.",
     "1. Submit silence 2. Submit noise 3. Submit an unsupported audio format",
     "silence / noise / bad format", "Each is handled with a clear message; nothing is transcribed into a confident wrong instruction",
     "Not Executed", "P2"),

    ("TC-AIG-13", "AI Guardrails", "Denying microphone permission is handled gracefully",
     "Mic permission denied.",
     "1. Deny permission 2. Press the mic button",
     "permission denied", "A clear explanation and a fallback to typing; no silent failure or stuck recording state",
     "Not Executed", "P3"),

    ("TC-AIG-14", "AI Guardrails", "AI usage limits are enforced and communicated",
     "A user at their usage cap.",
     "1. Consume the quota 2. Attempt another AI action 3. Check /api/assistant/usage and /api/ai/tutor/usage",
     "quota exhausted", "Further calls are refused with a clear message and an accurate remaining-quota reading",
     "Not Executed", "P2"),

    ("TC-AIG-15", "AI Guardrails", "Report generation failure shows a retry path that actually recovers",
     "Report generation forced to fail.",
     "1. Trigger a failure 2. Press retry with the provider restored",
     "forced failure", "The error state is explicit and retry produces a complete report",
     "Not Executed", "P1"),

    ("TC-AIG-16", "AI Guardrails", "Report citations resolve to real sources",
     "A generated report with citations.",
     "1. Open each citation",
     "N/A", "Every citation resolves to a real, relevant source; no invented reference",
     "Not Executed", "P1"),

    ("TC-AIG-17", "AI Guardrails", "The tutor's RAG answers stay grounded in the lesson corpus",
     "Learn Hub lesson open.",
     "1. Ask an in-corpus question 2. Ask something absent from the corpus",
     "in-corpus vs out-of-corpus", "In-corpus answers are grounded and citable; out-of-corpus questions get an honest 'not covered' rather than invention",
     "Not Executed", "P1"),

    ("TC-AIG-18", "AI Guardrails", "One user's AI history is never visible to another",
     "Two accounts.",
     "1. Generate tutor history as A 2. Call GET /api/ai/tutor/history as B",
     "A's history, B's JWT", "B sees only their own history; no cross-user leakage",
     "Not Executed", "P1"),

    ("TC-AIG-19", "AI Guardrails", "The market brief is generated and dated honestly",
     "Backend running.",
     "1. Call GET /api/ai/report/market-brief 2. Check its generation timestamp",
     "N/A", "The brief carries a generation time and is not presented as live if it is hours old",
     "Not Executed", "P2"),

    ("TC-AIG-20", "AI Guardrails", "A very long user message is handled without breaking the request",
     "Signed-in user.",
     "1. Send a very long message to the assistant",
     "~20,000 characters", "It is truncated or rejected with a clear message; no unhandled 500 and no context overflow crash",
     "Not Executed", "P2"),
]
