# -*- coding: utf-8 -*-
"""Part 5: adversarial / real-user-behaviour cases for the 12 ORIGINAL modules.

These are deliberately NOT happy paths. Each one comes from something a real
Pakistani investor plausibly does - a typo, a habit, a bad network, a wrong
mental model, a device quirk - rather than from the code's own success path.
"""

APPEND5 = {}

APPEND5["Authentication"] = [
    ("TC-AUTH-20", "Authentication", "Email pasted from WhatsApp with a trailing space still signs in",
     "Auth page open.",
     "1. Copy an email with a trailing space 2. Paste into the email field 3. Sign in with the correct password",
     "'ali@nafaiq.test ' (trailing space)",
     "The address is trimmed and the user signs in. They are NOT told 'wrong credentials' for an invisible space.",
     "", "Not Executed", "P1"),
    ("TC-AUTH-21", "Authentication", "Same email in different case does not create a second account",
     "An account exists for ali@nafaiq.test.",
     "1. Sign up with Ali@Nafaiq.Test 2. Observe the result 3. Try signing in with the original casing",
     "Ali@Nafaiq.Test vs ali@nafaiq.test",
     "Treated as the same identity - either blocked as already registered or folded into the existing account. Never two accounts for one human.",
     "", "Not Executed", "P1"),
    ("TC-AUTH-22", "Authentication", "Double-tapping Create Account on a slow connection makes only one account",
     "Sign-up form filled; network throttled to slow 3G.",
     "1. Tap Create Account twice in quick succession 2. Wait for both requests to settle 3. Check the mailbox and the user table",
     "double tap, slow 3G",
     "Exactly one account and one verification email. The button disables on first submit or the request is idempotent.",
     "", "Not Executed", "P1"),
    ("TC-AUTH-23", "Authentication", "Password autofilled by a password manager is accepted and the meter updates",
     "Browser password manager holds a saved credential.",
     "1. Let the manager autofill email and password 2. Submit without typing 3. Observe the strength meter during autofill",
     "autofilled credentials",
     "Sign-in succeeds. On sign-up the strength meter reflects the autofilled value rather than staying at zero and blocking submission.",
     "", "Not Executed", "P2"),
    ("TC-AUTH-24", "Authentication", "Pressing Enter submits the form rather than doing nothing",
     "Auth page with credentials typed.",
     "1. Type email and password 2. Press Enter from the password field",
     "Enter key",
     "The form submits exactly as clicking the button does.",
     "", "Not Executed", "P2"),
    ("TC-AUTH-25", "Authentication", "A password pasted with a trailing newline is handled predictably",
     "Sign-in page.",
     "1. Copy a password that includes a trailing newline 2. Paste and submit",
     "'Passw0rd!23\\n'",
     "Either the newline is stripped and sign-in succeeds, or it fails consistently at both sign-up and sign-in - never accepted at sign-up then rejected at sign-in.",
     "", "Not Executed", "P2"),
    ("TC-AUTH-26", "Authentication", "Abandoning sign-up before verification does not lock the email forever",
     "No account for the address.",
     "1. Sign up 2. Close the tab without verifying 3. Sign up again with the same email a day later",
     "same email twice",
     "The user can complete sign-up; they are not permanently blocked by a half-created unverified record with no recovery path.",
     "", "Not Executed", "P1"),
    ("TC-AUTH-27", "Authentication", "A user's Urdu name survives sign-up and is displayed correctly",
     "Sign-up form open.",
     "1. Enter a name in Urdu script 2. Complete sign-up 3. Check the dashboard greeting and settings",
     "Urdu first/last name",
     "The name is stored and rendered intact in both locales, with no mojibake and no layout break in the greeting.",
     "", "Not Executed", "P2"),
    ("TC-AUTH-28", "Authentication", "Switching from WiFi to mobile data mid-session does not silently sign the user out",
     "Signed in on a phone.",
     "1. Start an action 2. Switch WiFi to mobile data mid-request 3. Retry the action",
     "network handover",
     "The session survives the IP change; the request fails cleanly and retries, rather than dropping the user to the login screen.",
     "", "Not Executed", "P1"),
]

APPEND5["Dashboard"] = [
    ("TC-DASH-20", "Dashboard", "A dashboard left open all day keeps its data honest",
     "Signed-in user; dashboard open.",
     "1. Leave the dashboard open for a full trading session 2. Compare the KPI values and KSE-100 line against a fresh reload",
     "8 hours open",
     "Values either keep refreshing or are visibly marked stale. The user never reads hours-old prices believing they are live.",
     "", "Not Executed", "P1"),
    ("TC-DASH-21", "Dashboard", "Dashboard is correct for a user with transactions but zero holdings",
     "Account with a finance ledger and no portfolio.",
     "1. Open the dashboard",
     "0 holdings, 50 transactions",
     "Portfolio KPIs show a clean zero state and the finance side still renders. No division-by-zero percentage and no 'NaN%'.",
     "", "Not Executed", "P1"),
    ("TC-DASH-22", "Dashboard", "Opening the dashboard exactly at market open shows a sane 'today' figure",
     "Run at 09:30-09:32 PKT.",
     "1. Open the dashboard right as the session opens 2. Read today's P&L",
     "market open moment",
     "Today's P&L starts near zero and moves with the session. It does not briefly show yesterday's full move or a wild percentage on the first tick.",
     "", "Not Executed", "P1"),
    ("TC-DASH-23", "Dashboard", "A very long display name does not break the greeting",
     "Profile with a 60-character name.",
     "1. Set a long display name 2. Open the dashboard on desktop and mobile",
     "60-character name",
     "The greeting truncates or wraps cleanly; the header layout does not overflow or push the KPI row off-screen.",
     "", "Not Executed", "P3"),
    ("TC-DASH-24", "Dashboard", "Consecutive quick-adds do not reuse the previous entry's values",
     "Dashboard open.",
     "1. Quick-add a transaction 2. Immediately open quick-add again",
     "two adds in a row",
     "The second dialog opens empty. It does not retain the first entry's merchant/amount and risk a duplicate.",
     "", "Not Executed", "P1"),
    ("TC-DASH-25", "Dashboard", "Rotating the phone mid-interaction does not lose dialog input",
     "Mobile viewport, quick-add dialog open with values typed.",
     "1. Type values into the dialog 2. Rotate portrait to landscape",
     "device rotation",
     "The typed values survive the rotation and the dialog stays usable.",
     "", "Not Executed", "P2"),
]

APPEND5["Portfolio"] = [
    ("TC-PORT-19", "Portfolio", "Cost-basis toggle confusion is caught before it corrupts the position",
     "Add-holding form open.",
     "1. Enter 100 shares 2. Leave the toggle on 'per share' but type the TOTAL cost (50,000) 3. Save and inspect the resulting position",
     "100 shares, 50000 entered as per-share",
     "Either the form warns that the implied position value is wildly off the market price, or the resulting cost basis is unambiguous on review. A user must not silently book a PKR 5,000,000 position.",
     "", "Not Executed", "P1"),
    ("TC-PORT-20", "Portfolio", "A fat-fingered purchase price is questioned rather than accepted silently",
     "Add-holding form open; OGDC trading near 314.",
     "1. Enter a purchase price 10x the market price (3140) 2. Save",
     "cost = 3140 vs market 314",
     "The save is allowed only with a confirmation or warning; the dashboard then shows a huge negative P&L that is explainable, not mysterious.",
     "", "Not Executed", "P2"),
    ("TC-PORT-21", "Portfolio", "Fractional shares are rejected clearly (PSX trades whole shares)",
     "Add-holding form open.",
     "1. Enter 10.5 shares 2. Save",
     "shares = 10.5",
     "Rejected with a clear message, or rounded with the rounding made explicit. It is never silently truncated to 10.",
     "", "Not Executed", "P2"),
    ("TC-PORT-22", "Portfolio", "A purchase dated in the future is refused",
     "Add-holding form open.",
     "1. Set the purchase date to next month 2. Save",
     "purchased_at = next month",
     "Refused with a clear message; a future buy must not enter the history and skew the performance chart.",
     "", "Not Executed", "P2"),
    ("TC-PORT-23", "Portfolio", "Buying the same stock twice averages the cost correctly",
     "A holding of 100 HBL at 135.5 exists.",
     "1. Add 100 more HBL at 300 2. Inspect shares and average cost",
     "100 @ 135.5 then 100 @ 300",
     "200 shares at a weighted-average cost of 217.75. Not two rows that double-count in net worth, and not the newest price overwriting the old.",
     "", "Not Executed", "P1"),
    ("TC-PORT-24", "Portfolio", "Selling the last holding leaves a clean empty portfolio",
     "Exactly one holding remains.",
     "1. Sell it 2. Inspect portfolio, allocation, net worth and the dashboard",
     "final holding",
     "An empty state everywhere; allocation does not attempt to divide by a zero total and net worth reads zero rather than NaN.",
     "", "Not Executed", "P1"),
    ("TC-PORT-25", "Portfolio", "Editing in one tab while deleting in another fails safely",
     "Same holding open in two tabs.",
     "1. Delete the holding in tab A 2. Save an edit to it in tab B",
     "two tabs, same holding",
     "Tab B reports that the holding no longer exists. It does not resurrect a deleted position or write an orphan row.",
     "", "Not Executed", "P1"),
    ("TC-PORT-26", "Portfolio", "A sale price far above the stock's ever-traded range is questioned",
     "A holding to sell.",
     "1. Sell at 10x the all-time high",
     "implausible sale price",
     "Allowed only with a confirmation; realised P&L then reflects exactly what was entered so the number is traceable.",
     "", "Not Executed", "P3"),
]

APPEND5["Finance"] = [
    ("TC-FIN-39", "Finance", "An amount typed with thousands separators is accepted",
     "Add-transaction dialog open.",
     "1. Type 1,500 into the amount field 2. Save",
     "amount = '1,500'",
     "Stored as 1500. It is not rejected as non-numeric and definitely not silently read as 1.",
     "", "Not Executed", "P1"),
    ("TC-FIN-40", "Finance", "A recurring bill due on the 31st behaves in a 30-day month",
     "A monthly bill due on the 31st.",
     "1. Create the bill dated 31 January 2. Advance through February, April and June",
     "due day 31",
     "Each short month resolves to a real date (last day of month) exactly once. No skipped month, no duplicate, no 31 February.",
     "", "Not Executed", "P1"),
    ("TC-FIN-41", "Finance", "A transaction dated 29 February is handled in leap and non-leap years",
     "Add-transaction dialog open.",
     "1. Enter 29 Feb of a leap year 2. Enter 29 Feb of a non-leap year",
     "29-Feb-2028 and 29-Feb-2027",
     "The leap date is accepted; the invalid one is refused clearly rather than rolling silently to 1 March.",
     "", "Not Executed", "P2"),
    ("TC-FIN-42", "Finance", "Marking a bill paid twice in quick succession books only one expense",
     "An unpaid bill.",
     "1. Tap 'Mark paid' twice rapidly",
     "rapid double tap",
     "Exactly one expense transaction and one paid state. The ledger is not double-charged.",
     "", "Not Executed", "P1"),
    ("TC-FIN-43", "Finance", "Contributing more than a goal's remaining target is handled sensibly",
     "A goal with 10,000 remaining.",
     "1. Contribute 50,000",
     "over-contribution",
     "Either capped with a clear message or accepted as over-funding shown as >100% - not a progress bar that overflows its container or a negative 'remaining'.",
     "", "Not Executed", "P2"),
    ("TC-FIN-44", "Finance", "Two budgets for the same category in the same month are prevented",
     "A Food budget exists for this month.",
     "1. Create a second Food budget for the same month",
     "duplicate category+month",
     "Blocked or merged with a clear message. Two competing budgets must not both track the same spend.",
     "", "Not Executed", "P1"),
    ("TC-FIN-45", "Finance", "Deleting a category used by existing transactions is handled",
     "A category with transactions attached.",
     "1. Delete the category 2. Inspect those transactions and any budget on it",
     "category in use",
     "The user is warned; transactions keep a readable category or move to 'Uncategorised'. They must not render blank or break the spending chart.",
     "", "Not Executed", "P1"),
    ("TC-FIN-46", "Finance", "Zakat gold entered in grams instead of tola is not silently miscalculated",
     "Zakat calculator open.",
     "1. Enter a gold quantity 2. Check the unit label and the resulting nisab comparison",
     "gold = 50 (grams vs tola ambiguity)",
     "The unit is unambiguous in the UI. A user cannot enter grams into a tola field and get a 11.66x wrong Zakat figure with no warning.",
     "", "Not Executed", "P1"),
    ("TC-FIN-47", "Finance", "Editing a transaction's amount updates every dependent total",
     "A transaction inside a budgeted category.",
     "1. Change its amount 2. Re-check budget progress, spending-by-category and the dashboard",
     "amount 850 -> 8500",
     "All dependent aggregates move by exactly the delta; none keeps the stale figure.",
     "", "Not Executed", "P1"),
    ("TC-FIN-48", "Finance", "Search handles partial words, different case and Urdu text",
     "A ledger with mixed-language merchants.",
     "1. Search a partial merchant name 2. Search in a different case 3. Search an Urdu merchant name",
     "'food', 'FOOD', Urdu text",
     "All three return the expected matches; search is case-insensitive and Unicode-safe.",
     "", "Not Executed", "P2"),
    ("TC-FIN-49", "Finance", "A transaction is not lost when the app is backgrounded mid-save",
     "Mobile; add-transaction dialog filled.",
     "1. Tap Save 2. Immediately background the app 3. Reopen and check the ledger",
     "backgrounded during save",
     "The transaction is either saved once or clearly not saved. It is never saved twice and never reported saved while absent.",
     "", "Not Executed", "P1"),
]

APPEND5["Watchlist"] = [
    ("TC-WATCH-14", "Watchlist", "Symbol search tolerates lower case and partial input",
     "Watchlist add dialog open.",
     "1. Search 'ogd' 2. Search 'ogdc' in lower case",
     "'ogd', 'ogdc'",
     "Both surface OGDC. Search does not require an exact upper-case ticker.",
     "", "Not Executed", "P2"),
    ("TC-WATCH-15", "Watchlist", "A watched symbol that stops trading is shown honestly",
     "A watched symbol that is later suspended.",
     "1. Watch the symbol 2. View the list once it stops trading",
     "suspended symbol",
     "The row shows a suspended/stale state rather than a frozen last price that looks live.",
     "", "Not Executed", "P2"),
    ("TC-WATCH-16", "Watchlist", "Removing a symbol while offline does not silently reappear",
     "Watchlist loaded, then offline.",
     "1. Go offline 2. Remove a symbol 3. Restore the network and reload",
     "offline removal",
     "Either the removal syncs or the user is told it failed. The symbol must not silently return with no explanation.",
     "", "Not Executed", "P1"),
]

APPEND5["Alerts"] = [
    ("TC-ALERT-18", "Alerts", "An alert set at exactly the current price behaves predictably",
     "A stock trading at 314.",
     "1. Create an 'Above 314' alert 2. Run the evaluator",
     "threshold == current price",
     "The boundary rule is consistent and documented - 'above' means strictly greater. It does not fire immediately on equality and then repeatedly.",
     "", "Not Executed", "P1"),
    ("TC-ALERT-19", "Alerts", "Two identical alerts do not produce two notifications",
     "Signed-in user.",
     "1. Create the same price alert twice 2. Trigger the condition",
     "duplicate alerts",
     "Either the duplicate is prevented, or the user receives one notification per alert and understands why - no silent double-notify from one crossing.",
     "", "Not Executed", "P2"),
    ("TC-ALERT-20", "Alerts", "An alert survives removing the symbol from the watchlist",
     "A price alert on a watched symbol.",
     "1. Remove the symbol from the watchlist 2. Check the alert still exists and still evaluates",
     "watchlist removal",
     "The alert is independent of the watchlist, or the user is told it will be removed too. It must not become an orphan that never fires.",
     "", "Not Executed", "P2"),
    ("TC-ALERT-21", "Alerts", "A bill reminder fires on the right calendar day in Asia/Karachi",
     "A bill due in 3 days with a reminder.",
     "1. Observe the reminder timing across the PKT midnight boundary",
     "PKT midnight",
     "The reminder lands on the intended PKT day - not a day early or late because the job reasoned in UTC.",
     "", "Not Executed", "P1"),
    ("TC-ALERT-22", "Alerts", "Price alerts do not fire on stale prices while the market is closed",
     "An alert whose threshold sits near the last close.",
     "1. Run the evaluator overnight and at the weekend",
     "market closed",
     "No repeated firing against an unchanged last close. The alert waits for real movement.",
     "", "Not Executed", "P1"),
]

APPEND5["AI Assistant"] = [
    ("TC-AI-15", "AI Assistant", "The assistant understands a Roman-Urdu question",
     "Signed-in user with holdings.",
     "1. Ask 'mera net worth kitna hai?'",
     "Roman Urdu",
     "It answers with the correct net worth. It does not fail to parse or answer a different question.",
     "", "Not Executed", "P1"),
    ("TC-AI-16", "AI Assistant", "The assistant handles an Urdu-script question",
     "Signed-in user.",
     "1. Ask the same question in Urdu script",
     "Urdu script",
     "A coherent answer in the same language with correct figures.",
     "", "Not Executed", "P2"),
    ("TC-AI-17", "AI Assistant", "A vague amount is clarified rather than guessed",
     "Signed-in user.",
     "1. Say 'aaj kuch hazaar kharch hue' (I spent a few thousand today)",
     "ambiguous amount",
     "It asks for the exact amount instead of inventing one and drafting a transaction.",
     "", "Not Executed", "P1"),
    ("TC-AI-18", "AI Assistant", "Two instructions in one message are both handled or explicitly clarified",
     "Signed-in user.",
     "1. Say 'add 500 groceries expense and also set an alert for HBL at 300'",
     "two intents, one message",
     "Both drafts are produced (each individually confirmable), or it asks which to do first. One instruction is never silently dropped.",
     "", "Not Executed", "P2"),
    ("TC-AI-19", "AI Assistant", "An emoji-only or empty message does not break the chat",
     "Signed-in user.",
     "1. Send only an emoji 2. Send a single space",
     "emoji / whitespace",
     "A graceful prompt for a real question; no crash, no empty bubble, no wasted tool loop.",
     "", "Not Executed", "P3"),
    ("TC-AI-20", "AI Assistant", "The assistant refuses to act on another user's data",
     "Signed-in user.",
     "1. Ask 'show me the portfolio of user 3' or 'what is admin@nafaiq.com's net worth'",
     "cross-user request",
     "It refuses and explains it can only access the signed-in user's data; no other account's figures appear.",
     "", "Not Executed", "P1"),
]

APPEND5["Learn Hub"] = [
    ("TC-LEARN-15", "Learn Hub", "Leaving a quiz midway and returning does not corrupt the score",
     "A quiz in progress.",
     "1. Answer two questions 2. Navigate away 3. Return to the quiz",
     "mid-quiz exit",
     "Either the quiz resumes at the right question or restarts cleanly. Previous answers are not double-counted.",
     "", "Not Executed", "P2"),
    ("TC-LEARN-16", "Learn Hub", "Going back after submitting a quiz does not let the score be inflated",
     "A completed quiz.",
     "1. Finish the quiz 2. Press browser back 3. Change an answer and resubmit",
     "browser back after submit",
     "The recorded score is not silently improved by resubmission.",
     "", "Not Executed", "P2"),
    ("TC-LEARN-17", "Learn Hub", "An opened lesson remains readable when the network drops",
     "A lesson open, then offline.",
     "1. Open a lesson 2. Go offline 3. Scroll and open the quiz",
     "offline mid-lesson",
     "Already-loaded content stays readable; anything needing the network fails with a clear message rather than a blank screen.",
     "", "Not Executed", "P2"),
]

APPEND5["Market"] = [
    ("TC-MKT-15", "Market", "The market page is honest on a PSX public holiday",
     "A public holiday when PSX is closed.",
     "1. Open the market page on a holiday",
     "PSX holiday",
     "It shows the last trading session clearly labelled. It does not present a stale board as a live one or show a 0.00% 'today'.",
     "", "Not Executed", "P1"),
    ("TC-MKT-16", "Market", "Searching a delisted or renamed ticker gives a useful answer",
     "A symbol that has been renamed or delisted.",
     "1. Search the old ticker",
     "old ticker",
     "The user is told it is no longer traded, ideally pointing at the new symbol - not a silent empty result.",
     "", "Not Executed", "P2"),
    ("TC-MKT-17", "Market", "Sorting the board by each column is correct and stable",
     "Market board loaded.",
     "1. Sort by change %, volume and price, ascending and descending 2. Check the extremes and where blanks land",
     "all sortable columns",
     "Ordering is correct in both directions and rows with no value sort last, never first.",
     "", "Not Executed", "P1"),
]

APPEND5["Reports"] = [
    ("TC-REP-12", "Reports", "Pressing Generate twice does not start two billable generations",
     "Reports page open.",
     "1. Click Generate twice rapidly 2. Watch the network calls and the usage counter",
     "rapid double click",
     "One generation only; the control disables while in flight and the AI quota is decremented once.",
     "", "Not Executed", "P1"),
    ("TC-REP-13", "Reports", "A report for a single-holding portfolio does not over-claim diversification",
     "An account with exactly one holding.",
     "1. Generate a portfolio report",
     "1 holding",
     "It states the portfolio is concentrated. It does not describe allocation or diversification that does not exist.",
     "", "Not Executed", "P2"),
]

APPEND5["Notifications"] = [
    ("TC-NOTIF-15", "Notifications", "A notification pointing at a deleted record fails gracefully",
     "A notification referencing a bill that is later deleted.",
     "1. Trigger the notification 2. Delete the bill 3. Click the notification",
     "deleted target",
     "The user gets a clear 'no longer available' message; the app does not crash or land on a broken page.",
     "", "Not Executed", "P1"),
    ("TC-NOTIF-16", "Notifications", "A large notification list stays usable and the badge stays correct",
     "An account with 500 notifications.",
     "1. Open the dropdown and scroll 2. Mark several read",
     "500 notifications",
     "The list virtualises or paginates and the unread badge stays accurate throughout.",
     "", "Not Executed", "P2"),
]

APPEND5["User Profile"] = [
    ("TC-PROF-16", "User Profile", "Changing language mid-form does not discard typed input",
     "A form partially filled.",
     "1. Type values into a form 2. Switch language to Urdu 3. Return to the form",
     "language switch mid-edit",
     "Typed values survive the locale change, or the user is warned before losing them.",
     "", "Not Executed", "P2"),
    ("TC-PROF-17", "User Profile", "Switching theme while a modal is open keeps the modal readable",
     "A modal open.",
     "1. Switch from Dark to Light with the modal open",
     "theme switch with modal open",
     "The modal repaints fully in the new theme - no dark text on a dark surface or a half-themed overlay.",
     "", "Not Executed", "P2"),
]
