# -*- coding: utf-8 -*-
"""Part 2: Market Data & Macro, Stock Detail, Monetary Desk, Localization/RTL."""

VERIFIED = "Verified 2026-07-30 via live local API run (backend on :8000, real demo JWT). "

MARKET_DATA = [
    ("TC-MKTD-01", "Market Data", "Market snapshot returns live prices for the full board",
     "Backend running; ingestion has populated psx_market_snapshot.",
     "1. Call GET /api/market/snapshot 2. Spot-check several symbols against a public source",
     "N/A", "200 with an array of symbols carrying price, change, change_pct, volume, day_high and day_low",
     VERIFIED + "Returned a populated board (e.g. 786 @ 25.86, +0.23%; AABS @ 875.98). All expected fields present.", "Pass", "P1"),

    ("TC-MKTD-02", "Market Data", "Sector heatmap returns sector performance with a named source",
     "Backend running.",
     "1. Call GET /api/market/heatmap 2. Inspect the source and sector entries",
     "N/A", "200 with a source attribution and sectors carrying pct and volume",
     VERIFIED + "Returned source='tradingview' with sectors (Industrial Services +5.71%, Commercial Services...). Source attribution is present.", "Pass", "P2"),

    ("TC-MKTD-03", "Market Data", "Heatmap tile colour and size match the underlying numbers",
     "PSX page open.",
     "1. Open the sector heatmap 2. Compare tile colour/size against the pct and volume values",
     "N/A", "Green/red direction matches the sign, intensity matches magnitude, and tile area tracks weight - no inverted or mismatched tiles",
     "Not Executed", "P2"),

    ("TC-MKTD-04", "Market Data", "Heatmap empty state renders when no sector data is available",
     "Heatmap source unavailable.",
     "1. Simulate an empty heatmap response 2. Open the PSX page",
     "empty sectors array", "A dedicated empty state renders; no blank rectangle or crash",
     "Not Executed", "P3"),

    ("TC-MKTD-05", "Market Data", "Macro rates return current FX and policy values with refresh timestamps",
     "Backend running; SBP/MUFAP scrapers have run.",
     "1. Call GET /api/macro/rates 2. Check each series' date and refreshed_at",
     "N/A", "200 with series (e.g. FX_USD_BUY), a value, a date and a refreshed_at timestamp",
     VERIFIED + "Returned FX_USD_BUY = 277.758 dated 2026-07-30, refreshed_at 04:30 PKT. Series, value and freshness fields all present.", "Pass", "P1"),

    ("TC-MKTD-06", "Market Data", "Stale macro data is labelled rather than presented as current",
     "A macro series whose refreshed_at is well behind its cadence.",
     "1. Open the macro widget 2. Compare displayed values against refreshed_at",
     "an overdue series", "The UI shows the as-of date and marks overdue data as stale instead of implying it is live",
     "Not Executed", "P1"),

    ("TC-MKTD-07", "Market Data", "News feed returns recent headlines with working source links",
     "Backend running; Business Recorder scraper has run.",
     "1. Call GET /api/news/latest 2. Open several returned URLs",
     "N/A", "200 with headlines and resolvable source URLs, newest first",
     VERIFIED + "Returned live headlines with source URLs (e.g. 'Gold price per tola up Rs1,000 in Pakistan' -> brecorder.com). Link resolution still to be spot-checked in a browser.",
     "Pass", "P2"),

    ("TC-MKTD-08", "Market Data", "Market movers list ranks gainers and losers correctly",
     "Backend running.",
     "1. Load the movers card 2. Verify ordering and that gainers/losers are on the correct side",
     "N/A", "Gainers sort descending by change_pct, losers ascending; no symbol appears in both",
     "Not Executed - note: /api/market/movers is not a valid path; the movers card is backed by a different endpoint, so confirm the real route first.",
     "Not Executed", "P1"),

    ("TC-MKTD-09", "Market Data", "Unusual activity flags abnormal volume or price moves",
     "Backend running.",
     "1. Call GET /api/market/unusual 2. Cross-check a flagged symbol's volume against its average",
     "N/A", "Flagged symbols genuinely deviate from their baseline; the threshold is explainable",
     "Not Executed - /api/unusual/activity returned 404; the live path is /api/market/unusual.", "Not Executed", "P2"),

    ("TC-MKTD-10", "Market Data", "Stock screener filters return only matching stocks",
     "Backend running.",
     "1. POST /api/screener with a sector filter 2. Verify every returned symbol is in that sector 3. Add a second filter",
     "sector = Banking", "Results satisfy every active filter; combining filters narrows rather than widens the set",
     "Not Executed", "P2"),

    ("TC-MKTD-11", "Market Data", "Screener handles a filter combination that matches nothing",
     "Backend running.",
     "1. POST a deliberately impossible filter combination",
     "contradictory numeric ranges", "An explicit empty state, not an error and not an unfiltered list",
     "Not Executed", "P2"),

    ("TC-MKTD-12", "Market Data", "KSE-100 index endpoint matches the dashboard headline number",
     "Backend running.",
     "1. Call GET /api/market/kse100 2. Compare with the dashboard's KSE-100 line and the index snapshot",
     "N/A", "The same value and change percentage appear in both places at the same moment",
     "Not Executed", "P1"),

    ("TC-MKTD-13", "Market Data", "Quote history returns a usable series for charting",
     "Backend running.",
     "1. Call GET /api/quote/{symbol}/history for several ranges 2. Check ordering and gaps",
     "symbol = OGDC", "Chronologically ordered bars with no duplicate dates; non-trading days are absent rather than zero-filled",
     "Not Executed", "P1"),

    ("TC-MKTD-14", "Market Data", "Dividend calendar renders an empty state when there are no upcoming dividends",
     "Backend running.",
     "1. Call GET /api/dividends 2. Open /dividends in the UI",
     "N/A", "An explicit 'no upcoming dividends' state; not a blank page",
     VERIFIED + "GET /api/dividends returned 200 with an empty array [] on this environment, so the empty-state UI is exactly what a user sees today - worth an explicit UI check.",
     "Not Executed", "P2"),

    ("TC-MKTD-15", "Market Data", "Mutual funds list renders an empty state when no fund data is loaded",
     "Backend running.",
     "1. Call GET /api/funds 2. Open /funds in the UI",
     "N/A", "An explicit empty state with guidance; not a blank tab",
     VERIFIED + "GET /api/funds returned 200 with an empty object {} on this environment - /funds currently has no data to render.",
     "Not Executed", "P2"),

    ("TC-MKTD-16", "Market Data", "Fund NAV history returns a coherent series",
     "Fund data loaded.",
     "1. Call GET /api/funds/{fund_code}/nav 2. Check ordering and continuity",
     "a valid fund_code", "Ordered NAV points with no duplicates or impossible jumps",
     "Not Executed", "P3"),

    ("TC-MKTD-17", "Market Data", "Filings list returns announcements for a symbol",
     "Backend running; DPS scraper has run.",
     "1. Call GET /api/filings/{symbol} 2. Open one announcement",
     "symbol = OGDC", "Announcements list with dates and titles; the detail endpoint resolves",
     VERIFIED + "GET /api/filings/latest returned an empty array on this environment; per-symbol filings still need a run once the scraper has populated data.",
     "Not Executed", "P2"),

    ("TC-MKTD-18", "Market Data", "Filings search returns only matching announcements",
     "Filings present for the symbol.",
     "1. Call GET /api/filings/{symbol}/search with a query",
     "query = dividend", "Every result matches the query; a no-match query returns an empty list, not everything",
     "Not Executed", "P3"),

    ("TC-MKTD-19", "Market Data", "Quarterly and annual financials return consistent figures",
     "Financials ingested.",
     "1. Call GET /api/financials/{symbol}/quarterly and /annual 2. Compare four quarters against the annual figure",
     "symbol = HBL", "The annual figure reconciles with the sum of its quarters within a documented tolerance",
     "Not Executed - psx_financials_quarterly has historically been empty; confirm coverage before asserting.",
     "Not Executed", "P2"),

    ("TC-MKTD-20", "Market Data", "Market ticker keeps scrolling and updating without leaking memory",
     "PSX page open.",
     "1. Leave the ticker running for 30 minutes 2. Watch memory and update cadence",
     "N/A", "Prices keep refreshing on cadence; no unbounded memory growth or stalled ticker",
     "Not Executed", "P3"),

    ("TC-MKTD-21", "Market Data", "Market data behaves correctly across the Asia/Karachi day boundary",
     "Run around 00:00 PKT.",
     "1. Observe snapshot, index and 'today' change values across midnight PKT",
     "N/A", "Daily values reset on the PKT boundary, not UTC; no negative or duplicated trading day",
     "Not Executed", "P1"),

    ("TC-MKTD-22", "Market Data", "Index cards and sector averages agree with the underlying snapshot",
     "Backend running.",
     "1. Call GET /api/index/cards and GET /api/market/sectors/avg 2. Reconcile against the snapshot",
     "N/A", "Aggregates are computed from the same snapshot and do not contradict the per-symbol data",
     "Not Executed", "P2"),
]

STOCK_DETAIL = [
    ("TC-STK-01", "Stock Detail", "Deep link to a symbol opens the correct stock page",
     "Backend and frontend running.",
     "1. Open /stock/OGDC directly 2. Check the header, price and symbol",
     "symbol = OGDC", "The page loads for the requested symbol with a live price and no flash of another symbol's data",
     "Not Executed", "P1"),

    ("TC-STK-02", "Stock Detail", "A lower-case ticker in the URL resolves to the same page",
     "Frontend running.",
     "1. Open /stock/ogdc",
     "symbol = ogdc", "Resolves to OGDC with identical content",
     VERIFIED + "The backing API is confirmed case-insensitive (lower-case 'ogdc' returned identical analysis), so this is a routing-layer check.",
     "Not Executed", "P2"),

    ("TC-STK-03", "Stock Detail", "An unknown ticker shows a not-found state rather than an error page",
     "Frontend running.",
     "1. Open /stock/ZZZZ",
     "symbol = ZZZZ", "A clear 'symbol not found' state with a way back to search; no crash or infinite spinner",
     "Not Executed", "P1"),

    ("TC-STK-04", "Stock Detail", "Price chart range switching reloads the correct window",
     "Stock page open.",
     "1. Switch between the available ranges 2. Compare the first and last bar dates",
     "1D / 1M / 6M / 1Y", "Each range fetches and renders the right window; the active range is visually indicated",
     "Not Executed", "P1"),

    ("TC-STK-05", "Stock Detail", "All detail tabs load their own data without cross-contamination",
     "Stock page open.",
     "1. Cycle through Financials, Dividends and Filings tabs 2. Switch symbol and re-check",
     "OGDC then HBL", "Each tab shows data for the currently selected symbol; no stale data from the previous symbol persists",
     "Not Executed", "P1"),

    ("TC-STK-06", "Stock Detail", "Creating a price alert from the stock page lands in Active Alerts",
     "Signed-in user on a stock page.",
     "1. Open the price alert modal 2. Set a condition and price 3. Save 4. Open /alerts",
     "Condition=Below, Price=250", "The alert appears in Active Alerts bound to the correct symbol and condition",
     "Not Executed", "P2"),

    ("TC-STK-07", "Stock Detail", "Price alert modal rejects a non-positive or non-numeric price",
     "Alert modal open.",
     "1. Enter 0, then -10, then 'abc' 2. Attempt to save each",
     "0, -10, abc", "Each is refused with a clear message and no alert is created",
     "Not Executed", "P2"),

    ("TC-STK-08", "Stock Detail", "Add-to-watchlist from the stock page reflects immediately",
     "Signed-in user.",
     "1. Add the symbol to the watchlist from the stock page 2. Open /watchlist",
     "symbol = LUCK", "The symbol appears in the watchlist and the button flips to a 'watching' state",
     "Not Executed", "P2"),

    ("TC-STK-09", "Stock Detail", "Add-to-portfolio from the stock page pre-fills the symbol",
     "Signed-in user.",
     "1. Trigger add-holding from the stock page",
     "symbol = OGDC", "The holding form opens with the symbol pre-filled and read-only where appropriate",
     "Not Executed", "P2"),

    ("TC-STK-10", "Stock Detail", "The AI stock analysis report generates and renders for a symbol",
     "Signed-in user.",
     "1. POST /api/ai/report/stock/{symbol} via the UI 2. Read the rendered report",
     "symbol = OGDC", "A structured report renders with metrics and citations; failures show a retry state rather than a blank card",
     "Not Executed", "P2"),

    ("TC-STK-11", "Stock Detail", "Financials tab handles a symbol with no financial history",
     "A symbol lacking financials.",
     "1. Open the Financials tab for that symbol",
     "a thinly covered symbol", "An explicit 'no financials available' state; no NaN, null or empty table headers",
     "Not Executed", "P2"),

    ("TC-STK-12", "Stock Detail", "Percentage and currency values render with correct sign and precision",
     "Stock page open for a falling stock.",
     "1. Inspect change, change_pct and any P&L figures",
     "a stock with a negative day change", "Negative values are clearly negative, coloured consistently, and rounded to a stable number of decimals",
     "Not Executed", "P1"),

    ("TC-STK-13", "Stock Detail", "Stock page renders correctly in Urdu / RTL",
     "Language set to Urdu.",
     "1. Open a stock page in Urdu 2. Check tabs, chart axis, numbers and layout mirroring",
     "Urdu locale", "Layout mirrors, labels translate, and the ticker/numbers stay readable in an RTL context",
     "Not Executed", "P2"),

    ("TC-STK-14", "Stock Detail", "Stock page is usable on a small mobile viewport",
     "Pixel-7-sized viewport.",
     "1. Open a stock page 2. Interact with tabs, chart and action buttons",
     "393x851", "No horizontal overflow; tabs scroll or wrap; touch targets are comfortably tappable",
     "Not Executed", "P2"),

    ("TC-STK-15", "Stock Detail", "Rapidly switching symbols does not render the wrong symbol's data",
     "Stock page open.",
     "1. Switch symbol five times in quick succession 2. Settle on the last one",
     "OGDC -> HBL -> ENGRO -> PSO -> LUCK", "The final view matches the final symbol; no out-of-order response overwrites it (race condition check)",
     "Not Executed", "P1"),

    ("TC-STK-16", "Stock Detail", "Stock page degrades gracefully when the market API is unavailable",
     "Backend stopped or blocked.",
     "1. Open a stock page with the API unreachable",
     "API down", "A clear error state with retry; no infinite skeleton and no unhandled console exception",
     "Not Executed", "P1"),
]

MONETARY = [
    ("TC-MON-01", "Monetary Desk", "Currency conversion computes correctly against the published rate",
     "Backend running; FX rates fresh.",
     "1. Open /monetary 2. Convert 100 USD to PKR 3. Compare against /api/macro/fx",
     "100 USD -> PKR", "The converted amount equals amount x rate within rounding tolerance and the rate source is named",
     VERIFIED + "Live FX confirmed available (FX_USD_BUY = 277.758 on 2026-07-30), so the expected value is checkable; the UI arithmetic still needs its own run.",
     "Not Executed", "P2"),

    ("TC-MON-02", "Monetary Desk", "Swapping currencies inverts the conversion consistently",
     "Monetary page open.",
     "1. Convert A to B and note the result 2. Press swap 3. Convert the result back",
     "USD <-> PKR", "Round-tripping returns to the original amount within rounding tolerance",
     "Not Executed", "P2"),

    ("TC-MON-03", "Monetary Desk", "Conversion rejects or safely handles invalid amounts",
     "Monetary page open.",
     "1. Enter a negative amount, then text, then an extremely large number",
     "-100, 'abc', 1e18", "Invalid input is refused with a clear message; large values do not render as scientific notation or overflow the layout",
     "Not Executed", "P2"),

    ("TC-MON-04", "Monetary Desk", "Metal prices show per-gram, per-10g and per-tola consistently",
     "Metals data available.",
     "1. Read the three metal metrics 2. Check the arithmetic between them",
     "N/A", "per_10g = 10 x per_gram and per_tola = 11.6638 x per_gram within rounding tolerance",
     "Not Executed", "P2"),

    ("TC-MON-05", "Monetary Desk", "The FX and metal source pills name the real upstream source",
     "Monetary page open.",
     "1. Read the FX source and metal source pills",
     "N/A", "Each names its actual provider and the data quality indicator matches the freshness",
     "Not Executed", "P3"),

    ("TC-MON-06", "Monetary Desk", "The 'Updated' timestamp reflects the true refresh time",
     "Monetary page open.",
     "1. Compare the displayed Updated value against the API's refreshed_at",
     "N/A", "They agree, and a stale timestamp is visibly flagged",
     VERIFIED + "Macro API exposes refreshed_at (04:30 PKT on 2026-07-30) making this directly checkable.", "Not Executed", "P2"),

    ("TC-MON-07", "Monetary Desk", "Live refresh updates values without breaking the layout",
     "Monetary page open.",
     "1. Trigger the live refresh 2. Watch the values and the layout during the update",
     "N/A", "Values update in place; no layout jump, duplicated request storm, or stuck spinner",
     "Not Executed", "P3"),

    ("TC-MON-08", "Monetary Desk", "Monetary desk degrades gracefully when the FX source is unavailable",
     "FX source unreachable.",
     "1. Open /monetary with the FX upstream failing",
     "FX source down", "A clear unavailable state and the last known value labelled as such; no zero or NaN rates shown as real",
     "Not Executed", "P2"),

    ("TC-MON-09", "Monetary Desk", "Monetary values format correctly in Urdu / RTL",
     "Urdu locale.",
     "1. Open /monetary in Urdu",
     "Urdu locale", "Currency symbols and digits stay correctly ordered in RTL; nothing renders mirrored into nonsense",
     "Not Executed", "P2"),

    ("TC-MON-10", "Monetary Desk", "Gold price feeds the Zakat nisab consistently",
     "Zakat calculator and monetary desk both open.",
     "1. Read the per-tola gold price 2. Open the Zakat calculator and inspect the nisab basis",
     "N/A", "The nisab used by the calculator is derived from the same metal price shown on the monetary desk",
     "Not Executed - the Zakat API accepts a client-supplied nisab_value_pkr, so consistency depends entirely on the client. See TC-DATA-14.",
     "Not Executed", "P1"),
]

L10N = [
    ("TC-L10N-01", "Localization", "Switching to Urdu translates the whole shell, not just the page body",
     "Signed-in user.",
     "1. Switch language to Urdu 2. Inspect nav, sidebar, footer, dialogs, toasts and empty states",
     "Urdu locale", "Every visible string is translated; no untranslated English leaks in menus, modals or toasts",
     "Not Executed", "P1"),

    ("TC-L10N-02", "Localization", "The document direction flips to RTL in Urdu",
     "Urdu selected.",
     "1. Inspect the html dir attribute 2. Observe overall layout mirroring",
     "Urdu locale", "dir='rtl' is applied and the layout mirrors coherently",
     "Not Executed", "P1"),

    ("TC-L10N-03", "Localization", "Language choice persists across reload and across sessions",
     "Urdu selected.",
     "1. Reload the page 2. Sign out and back in",
     "Urdu locale", "Urdu remains selected in both cases; the app does not silently revert to English",
     "Not Executed", "P1"),

    ("TC-L10N-04", "Localization", "Numbers and currency stay LTR inside RTL text",
     "Urdu selected.",
     "1. Inspect PKR amounts, percentages and dates inside Urdu sentences",
     "PKR 1,234,567.89", "Numerals and the currency symbol keep correct order and are not visually reversed or split",
     "Not Executed", "P1"),

    ("TC-L10N-05", "Localization", "Negative values render correctly in RTL",
     "Urdu selected; a losing position present.",
     "1. Inspect a negative P&L figure and a negative percentage",
     "-695 PKR, -0.42%", "The minus sign stays attached to the number and on the correct side; no ambiguity about direction",
     VERIFIED + "The demo portfolio genuinely returns negative values today (today_pnl = -695.0, -0.42%), so this is directly reproducible.",
     "Not Executed", "P1"),

    ("TC-L10N-06", "Localization", "Latin stock tickers remain readable inside Urdu RTL text",
     "Urdu selected.",
     "1. Open the watchlist and a stock page in Urdu",
     "OGDC, HBL, KSE-100", "Tickers render left-to-right and in the right position; 'KSE-100' is not broken across the bidi boundary",
     "Not Executed", "P1"),

    ("TC-L10N-07", "Localization", "Charts mirror sensibly in RTL",
     "Urdu selected.",
     "1. Open the portfolio and price charts in Urdu",
     "Urdu locale", "Axis labels and legends are readable and correctly placed; the time axis direction is consistent and not misleading",
     "Not Executed", "P2"),

    ("TC-L10N-08", "Localization", "Directional icons flip appropriately in RTL",
     "Urdu selected.",
     "1. Inspect back arrows, chevrons, carousels and progress bars",
     "Urdu locale", "Directional affordances mirror; non-directional icons (logos, up/down P&L arrows) do not flip incorrectly",
     "Not Executed", "P2"),

    ("TC-L10N-09", "Localization", "Form inputs accept Urdu text and keep the caret behaving",
     "Urdu selected.",
     "1. Type an Urdu merchant name and an Urdu goal name 2. Save and re-read",
     "Urdu text in text fields", "Text is stored and displayed intact; the caret and text alignment behave in RTL",
     "Not Executed", "P2"),

    ("TC-L10N-10", "Localization", "Urdu text round-trips through the API without corruption",
     "Urdu locale.",
     "1. Create a transaction with an Urdu merchant name 2. Re-fetch and view in the ledger and in a report",
     "Urdu merchant name", "The stored value returns byte-identical; no mojibake anywhere in the stack",
     "Not Executed", "P1"),

    ("TC-L10N-11", "Localization", "Dates render in the expected calendar and locale format",
     "Urdu selected.",
     "1. Inspect transaction dates, bill due dates and the analysis as_of date",
     "Urdu locale", "Dates are formatted consistently and unambiguously in both locales",
     "Not Executed", "P2"),

    ("TC-L10N-12", "Localization", "Long Urdu strings do not break layout",
     "Urdu selected.",
     "1. Inspect buttons, table headers, KPI cards and nav items with the longest Urdu labels",
     "Urdu locale", "No overflow, clipping or overlapping text; components wrap or truncate gracefully",
     "Not Executed", "P2"),

    ("TC-L10N-13", "Localization", "Validation and error messages are translated",
     "Urdu selected.",
     "1. Trigger validation errors (empty amount, negative limit) and a network error",
     "Urdu locale", "Error text appears in Urdu, not as raw English or a raw API string",
     "Not Executed", "P2"),

    ("TC-L10N-14", "Localization", "The AI assistant and reports respond appropriately for an Urdu user",
     "Urdu selected.",
     "1. Ask the assistant a question in Urdu 2. Generate a report",
     "Urdu question", "The reply is coherent and in the expected language; no garbled script or silent fallback to English mid-sentence",
     "Not Executed", "P2"),

    ("TC-L10N-15", "Localization", "Switching back to English fully restores LTR",
     "Urdu selected.",
     "1. Switch back to English 2. Inspect layout, dir attribute and icons",
     "English locale", "Everything returns to LTR with no residual mirrored components",
     "Not Executed", "P1"),

    ("TC-L10N-16", "Localization", "The dedicated Urdu QA page reflects real component states",
     "Urdu QA route available.",
     "1. Open /urdu-qa 2. Compare each showcased component against its real usage",
     "N/A", "The QA page exercises the components that actually ship, so it is a trustworthy RTL smoke check",
     "Not Executed", "P3"),

    ("TC-L10N-17", "Localization", "Mobile app matches web for language and RTL behaviour",
     "Expo app running.",
     "1. Switch the mobile app to Urdu 2. Compare key screens against web",
     "Urdu locale on mobile", "Mobile mirrors web's translations and RTL treatment; no screen is left English-only",
     "Not Executed", "P2"),

    ("TC-L10N-18", "Localization", "Number formatting matches Pakistani conventions where intended",
     "Both locales.",
     "1. Inspect large amounts across dashboard, portfolio and reports",
     "1,234,567 vs 12,34,567", "Grouping is consistent everywhere and matches the documented convention - the same number is never grouped two different ways in one app",
     "Not Executed", "P2"),
]
