# -*- coding: utf-8 -*-
"""Part 4: additional cases appended to the EXISTING module sheets,
filling gaps inside areas the sheet already covers."""

VERIFIED = "Verified 2026-07-30 via live local API run (backend on :8000, real demo JWT). "

APPEND = {}

APPEND["Authentication"] = [
    ("TC-AUTH-14", "Authentication", "Sign-in is rate limited against password brute force",
     "Backend running.",
     "1. Attempt 20 sign-ins with wrong passwords for one email 2. Observe throttling",
     "20 wrong attempts", "Attempts are throttled or locked out with a clear message; the account is not brute-forceable",
     "Not Executed", "P1"),
    ("TC-AUTH-15", "Authentication", "Sign-in errors do not reveal whether an email is registered",
     "Backend running.",
     "1. Sign in with an unknown email 2. Sign in with a known email and a wrong password 3. Compare messages",
     "unknown vs known email", "Both produce the same generic message; no user enumeration",
     "Not Executed", "P2"),
    ("TC-AUTH-16", "Authentication", "Email is validated and normalised at sign-up",
     "Auth page in sign-up mode.",
     "1. Try 'ali@', 'ali@@x.com', ' ali@x.com ' and a mixed-case address",
     "malformed and padded emails", "Malformed values are rejected; whitespace is trimmed and case handled consistently so no duplicate account is created",
     "Not Executed", "P2"),
    ("TC-AUTH-17", "Authentication", "Password field resists a very long or unusual input",
     "Sign-up form open.",
     "1. Enter a 5,000-character password 2. Enter emoji and RTL characters",
     "long / unicode password", "The form handles it without crashing; the limit is communicated rather than silently truncating a credential",
     "Not Executed", "P3"),
    ("TC-AUTH-18", "Authentication", "Password reset flow completes and invalidates the old password",
     "A test account.",
     "1. Request a reset 2. Complete it 3. Try the old password, then the new one",
     "test account", "The old password stops working and the new one signs in; the reset link is single-use",
     "Not Executed", "P1"),
    ("TC-AUTH-19", "Authentication", "An unverified email account is handled per policy",
     "A newly created, unverified account.",
     "1. Sign in before verifying 2. Attempt a protected action",
     "unverified account", "Behaviour matches the documented policy consistently in UI and API - not allowed in one and blocked in the other",
     "Not Executed", "P2"),
]

APPEND["Dashboard"] = [
    ("TC-DASH-15", "Dashboard", "KPI cards reconcile with the underlying APIs",
     "Signed-in user with holdings.",
     "1. Read the dashboard KPI values 2. Compare against /api/portfolio/networth",
     "demo account", "Every KPI matches the API to the rupee; no rounding drift between surfaces",
     VERIFIED + "API ground truth for the demo account: market value 164467.0, cost basis 89680.0, unrealised 74787.0 (83.39%), today -695.0 (-0.42%), 1 portfolio, 3 holdings. The dashboard must match these.",
     "Not Executed", "P1"),
    ("TC-DASH-16", "Dashboard", "Dashboard renders correctly for an account with no data",
     "A new account.",
     "1. Open the dashboard with no holdings, transactions or goals",
     "empty account", "Helpful empty states with next actions; no NaN, 'undefined', or divide-by-zero percentages",
     "Not Executed", "P1"),
    ("TC-DASH-17", "Dashboard", "Quick-add dialogs validate before writing",
     "Dashboard open.",
     "1. Submit each quick-add dialog empty 2. Then with invalid values",
     "empty / invalid input", "Each rejects with a clear message and creates nothing",
     "Not Executed", "P2"),
    ("TC-DASH-18", "Dashboard", "Dashboard survives a partial API failure",
     "One dependent endpoint failing.",
     "1. Force one dashboard endpoint to 500 2. Load the dashboard",
     "one endpoint failing", "The failing card shows its own error state while the rest of the dashboard still renders",
     "Not Executed", "P1"),
    ("TC-DASH-19", "Dashboard", "Goals section behaves correctly beyond the display cap",
     "More goals than the display limit.",
     "1. Create more goals than the cap 2. Inspect the section",
     "4+ goals", "The cap is applied with a clear way to see the rest; no silent hiding of goals with no affordance",
     "Not Executed", "P3"),
]

APPEND["Portfolio"] = [
    ("TC-PORT-14", "Portfolio", "Holdings table values reconcile with the API",
     "Holdings present.",
     "1. Compare each row's market value and P&L against the API 2. Compare the totals",
     "demo portfolio", "Row values and totals match the API exactly",
     VERIFIED + "Allocation ground truth: ENGRO 72807.0 (44.27%), HBL 60260.0 (36.64%), OGDC 31400.0 (19.09%), total 164467.0.",
     "Not Executed", "P1"),
    ("TC-PORT-15", "Portfolio", "Selling more shares than held is refused",
     "A holding with a known quantity.",
     "1. Attempt a sale larger than the position",
     "sell qty > held", "Rejected clearly; no negative position is created",
     "Not Executed", "P1"),
    ("TC-PORT-16", "Portfolio", "Fees are included in realised P&L on a sale",
     "A holding to sell.",
     "1. Sell with a fee 2. Inspect realised P&L and the ledger",
     "fee = 50", "Realised P&L is net of fees and the fee is visible in the resulting transaction",
     "Not Executed", "P2"),
    ("TC-PORT-17", "Portfolio", "Portfolio history chart matches the range requested",
     "History available.",
     "1. Switch ranges and compare the first/last points with /api/portfolio/history",
     "30/90/180/365 days", "Each range renders the correct window with no off-by-one at the edges",
     "Not Executed", "P2"),
    ("TC-PORT-18", "Portfolio", "A holding in a suspended or delisted symbol is handled",
     "A holding in a non-trading symbol.",
     "1. View the portfolio containing it",
     "suspended symbol", "The row renders with a clear state rather than a stale price presented as live; totals remain sane",
     "Not Executed", "P2"),
]

APPEND["Alerts"] = [
    ("TC-ALERT-13", "Alerts", "An alert actually triggers when its condition is met",
     "An alert whose condition can be crossed.",
     "1. Create the alert 2. Cause the crossing 3. Run POST /api/alerts/evaluate 4. Check /api/alerts/events",
     "a crossable condition", "Exactly one event is created and it references the correct alert and value",
     "Not Executed - alert firing is the core value of the feature and is currently only partly covered.", "Not Executed", "P1"),
    ("TC-ALERT-14", "Alerts", "A disabled alert never fires",
     "A disabled alert whose condition is met.",
     "1. Disable the alert 2. Cross the condition 3. Run the evaluator",
     "disabled alert", "No event and no notification is produced",
     "Not Executed", "P1"),
    ("TC-ALERT-15", "Alerts", "Alert events can be marked read and stay read",
     "A triggered event.",
     "1. PATCH /api/alerts/events/{id}/read 2. Reload the events list",
     "an event id", "The event is marked read and does not revert on reload",
     "Not Executed", "P2"),
    ("TC-ALERT-16", "Alerts", "Creating an alert for a non-existent symbol is refused",
     "Signed-in user.",
     "1. Create a price alert for an invalid ticker",
     "symbol = XYZ123", "Rejected with a clear message; no unfireable alert is stored",
     "Not Executed", "P2"),
    ("TC-ALERT-17", "Alerts", "A very large number of alerts does not degrade evaluation",
     "An account with 200 alerts.",
     "1. Create many alerts 2. Run the evaluator and time it",
     "200 alerts", "Evaluation completes within its 60-second window without skipping alerts",
     "Not Executed", "P2"),
]

APPEND["Finance"] = [
    ("TC-FIN-30", "Finance", "Spending-by-category totals reconcile with the ledger",
     "Transactions across several categories.",
     "1. Call GET /api/finance/spending-by-category 2. Sum matching ledger entries",
     "demo ledger", "Category totals equal the sum of their transactions for the period; no transaction is double counted",
     "Not Executed", "P1"),
    ("TC-FIN-31", "Finance", "Income vs expense summary matches the ledger",
     "Income and expense transactions present.",
     "1. Call GET /api/finance/income-expense and /summary 2. Reconcile against the ledger",
     "demo ledger", "Both endpoints agree with the ledger and with each other",
     VERIFIED + "Ledger confirmed populated (e.g. 'Freelance Income' 45000.0 income). Reconciliation itself still to run.",
     "Not Executed", "P1"),
    ("TC-FIN-32", "Finance", "A payment method can be created and used on a transaction",
     "Signed-in user.",
     "1. POST /api/finance/payment-methods 2. Create a transaction using it 3. Re-read",
     "Meezan Bank", "The method is created, selectable, and persists on the transaction",
     "Not Executed", "P3"),
    ("TC-FIN-33", "Finance", "Transactions in the future and far past are handled",
     "Add-transaction dialog open.",
     "1. Add a transaction dated next year 2. Add one dated 10 years ago",
     "future and old dates", "Either rejected by a documented rule or handled consistently in totals, budgets and charts",
     "Not Executed", "P2"),
    ("TC-FIN-34", "Finance", "A recurring bill regenerates on the correct cadence",
     "A monthly recurring bill.",
     "1. Mark it paid 2. Advance to the next cycle",
     "monthly recurrence", "The next instance appears once on the right date, without duplicating the paid one",
     "Not Executed", "P1"),
    ("TC-FIN-35", "Finance", "Budget month navigation does not leak spend across months",
     "Transactions in two months.",
     "1. Navigate between months 2. Compare progress in each",
     "two months of spend", "Each month shows only its own spend; navigation does not accumulate",
     "Not Executed", "P1"),
    ("TC-FIN-36", "Finance", "Zakat history records only saved calculations",
     "Signed-in user.",
     "1. Calculate with save=false 2. Calculate with save=true 3. Call GET /api/finance/zakat/history",
     "save flag both ways", "Only the saved calculation appears in history",
     VERIFIED + "All exploratory calculations in this run used save=false specifically to avoid polluting demo history; the save=true leg still needs a run.",
     "Not Executed", "P2"),
    ("TC-FIN-37", "Finance", "Zakat settings changes are reflected in the next calculation",
     "Signed-in user.",
     "1. PATCH /api/finance/zakat/settings 2. Recalculate",
     "changed nisab method", "The new setting drives the calculation and is persisted",
     "Not Executed", "P2"),
    ("TC-FIN-38", "Finance", "Finance settings persist and apply across surfaces",
     "Signed-in user.",
     "1. PATCH /api/finance/settings 2. Reload and check dependent views",
     "changed settings", "The setting persists and every dependent view honours it",
     "Not Executed", "P3"),
]

APPEND["Notifications"] = [
    ("TC-NOTIF-11", "Notifications", "The unread badge matches the actual unread count",
     "Notifications present.",
     "1. Compare the badge with the unread rows from /api/notifications/list 2. Mark one read and re-check",
     "demo account", "The badge matches exactly and decrements on read",
     VERIFIED + "GET /api/notifications/list returned real rows (e.g. a 'Bill paid' notification, id 1591), so the count is checkable against live data.",
     "Not Executed", "P1"),
    ("TC-NOTIF-12", "Notifications", "Notification preferences are honoured on delivery",
     "Preferences set to push on, email off.",
     "1. Set the preferences 2. Trigger an alert 3. Observe which channels deliver",
     "push=on, email=off", "Only the enabled channel delivers; the disabled one sends nothing",
     "Not Executed", "P1"),
    ("TC-NOTIF-13", "Notifications", "A notification links to the correct destination",
     "A notification referencing an entity.",
     "1. Click a bill, budget and price notification in turn",
     "N/A", "Each opens the specific referenced record, not just the section index",
     "Not Executed", "P2"),
    ("TC-NOTIF-14", "Notifications", "Notifications are not duplicated for a single event",
     "An alert that triggers once.",
     "1. Trigger one event 2. Count the notifications",
     "one trigger", "Exactly one notification per event across all surfaces",
     "Not Executed", "P1"),
]

APPEND["Watchlist"] = [
    ("TC-WATCH-11", "Watchlist", "Watchlist prices refresh on cadence without a manual reload",
     "Watchlist with symbols, market open.",
     "1. Observe the rows over several refresh intervals",
     "N/A", "Prices and changes update on the expected cadence and the last-updated indicator moves",
     "Not Executed", "P2"),
    ("TC-WATCH-12", "Watchlist", "Watchlist persists across sessions and devices",
     "Signed-in user.",
     "1. Add symbols 2. Sign out, back in, and open on another device",
     "N/A", "The same watchlist appears in both places",
     "Not Executed", "P2"),
    ("TC-WATCH-13", "Watchlist", "A large watchlist stays performant",
     "50+ symbols watched.",
     "1. Load and scroll the watchlist",
     "50 symbols", "Rendering and refresh stay smooth; requests are batched rather than one per row",
     "Not Executed", "P3"),
]

APPEND["AI Assistant"] = [
    ("TC-AI-11", "AI Assistant", "Assistant figures match the user's real data",
     "Signed-in user with known holdings.",
     "1. Ask for net worth and top holding 2. Compare with the API",
     "\"What is my net worth?\"", "Numbers match the API exactly; no fabricated values",
     VERIFIED + "Ground truth: 164467.0 total, top holding ENGRO at 72807.0 (44.27%).", "Not Executed", "P1"),
    ("TC-AI-12", "AI Assistant", "The assistant cannot write data without confirmation",
     "Signed-in user.",
     "1. Ask for a write action 2. Inspect the data before confirming",
     "add_transaction intent", "Nothing is persisted until the draft is explicitly confirmed",
     "Not Executed", "P1"),
    ("TC-AI-13", "AI Assistant", "Assistant is unavailable or gracefully limited for a demo session",
     "Demo session.",
     "1. Use the assistant in demo mode",
     "demo user", "Behaviour matches the documented demo policy with a clear message; no crash and no writes to real data",
     "Not Executed", "P2"),
    ("TC-AI-14", "AI Assistant", "Rapid consecutive messages are handled in order",
     "Signed-in user.",
     "1. Send three messages in quick succession",
     "3 rapid messages", "Replies stay matched to their prompts and in order; no interleaved or lost message",
     "Not Executed", "P2"),
]

APPEND["Learn Hub"] = [
    ("TC-LEARN-11", "Learn Hub", "Lesson pages render without duplicate-key or hydration errors",
     "Learn Hub available.",
     "1. Open several /learn/lesson/* pages 2. Watch the console",
     "N/A", "No React duplicate-key warnings and no hydration mismatch; all lesson blocks render exactly once",
     "Directly tied to the open defect UJ-BUG-03 (6x duplicate-key errors plus a React-19 hydration mismatch on every lesson load). Keep as a regression case until fixed.",
     "Not Executed", "P1"),
    ("TC-LEARN-12", "Learn Hub", "Lesson completion persists and updates the progress ring",
     "A lesson in progress.",
     "1. Complete a lesson 2. Reload and re-open Learn Hub",
     "N/A", "Completion persists and the ring reflects the new count",
     "Not Executed", "P1"),
    ("TC-LEARN-13", "Learn Hub", "Quiz scoring is correct for all-right and all-wrong runs",
     "A quiz available.",
     "1. Answer every question correctly 2. Repeat answering every one incorrectly",
     "all correct / all wrong", "Scores are 100% and 0% respectively with correct per-question feedback",
     "Not Executed", "P2"),
    ("TC-LEARN-14", "Learn Hub", "Glossary search returns relevant terms and handles no-match",
     "Glossary available.",
     "1. Search a known term 2. Search nonsense",
     "'diversification' / 'zzzz'", "Relevant results for the first; an explicit empty state for the second",
     "Not Executed", "P3"),
]

APPEND["Market"] = [
    ("TC-MKT-12", "Market", "PSX terminal renders with real market data end to end",
     "Backend running with fresh snapshot.",
     "1. Open /psx 2. Verify the index, movers, heatmap and ticker against the API",
     "N/A", "Every widget matches its API source at the same moment",
     VERIFIED + "Backing APIs confirmed live: /api/market/snapshot returned the full board and /api/market/heatmap returned sector data from TradingView.",
     "Not Executed", "P1"),
    ("TC-MKT-13", "Market", "Market page behaves correctly when the market is closed",
     "Outside trading hours.",
     "1. Open the market page after close or on a weekend",
     "market closed", "A clear closed-market state with the last session's data labelled as such",
     "Not Executed", "P1"),
    ("TC-MKT-14", "Market", "Currency converter matches the published macro rate",
     "Backend running.",
     "1. Convert an amount 2. Compare against /api/macro/fx",
     "100 USD -> PKR", "The result equals amount x published rate within rounding tolerance",
     VERIFIED + "Live rate available for comparison: FX_USD_BUY = 277.758 on 2026-07-30.", "Not Executed", "P2"),
]

APPEND["Reports"] = [
    ("TC-REP-09", "Reports", "Report metrics reconcile with the user's actual data",
     "Signed-in user with holdings.",
     "1. Generate a portfolio report 2. Compare every quoted metric with the API",
     "demo portfolio", "Each metric matches the API; nothing is invented or stale",
     VERIFIED + "Ground truth available: 164467.0 value, 83.39% unrealised gain, 3 holdings.", "Not Executed", "P1"),
    ("TC-REP-10", "Reports", "Report generation is not silently served from a stale cache",
     "An existing report.",
     "1. Change the underlying data 2. Regenerate",
     "N/A", "The regenerated report reflects the change, or the cache age is disclosed",
     "Not Executed", "P2"),
    ("TC-REP-11", "Reports", "A report for an empty account does not fabricate content",
     "A new account with no data.",
     "1. Generate a report",
     "empty account", "It states there is not enough data rather than inventing holdings or trends",
     "Not Executed", "P1"),
]

APPEND["User Profile"] = [
    ("TC-PROF-11", "User Profile", "Display name changes propagate everywhere",
     "Signed-in user.",
     "1. Change the display name 2. Check the dashboard greeting, nav and any report header",
     "Display Name = Ali Khan", "The new name appears consistently after save without a re-login",
     "Not Executed", "P2"),
    ("TC-PROF-12", "User Profile", "Profile fields reject unsafe or oversized input",
     "Settings open.",
     "1. Enter a script tag, a 1,000-character name and emoji",
     "<script>, long string, emoji", "Input is validated or safely escaped; nothing executes and layout does not break",
     "Not Executed", "P2"),
    ("TC-PROF-13", "User Profile", "Disconnecting Gmail revokes access and stops syncing",
     "Gmail connected.",
     "1. DELETE /api/integrations/email 2. Trigger a sync 3. Re-check the connection state",
     "N/A", "The token is revoked, syncing stops, and the UI shows disconnected",
     "Not Executed", "P2"),
    ("TC-PROF-14", "User Profile", "Gmail sync does not create duplicate transactions on repeat runs",
     "Gmail connected with importable mail.",
     "1. Run POST /api/integrations/email/sync twice",
     "same mailbox twice", "The second run imports nothing new; imports are idempotent",
     "Not Executed", "P1"),
    ("TC-PROF-15", "User Profile", "Account data export / deletion honours the user's request",
     "Signed-in user.",
     "1. Request export and deletion where offered",
     "N/A", "The request is fulfilled per policy and confirmed to the user; deletion removes personal data",
     "Not Executed", "P2"),
]
