import { formatNumber } from "@/lib/format";
import { ASSET_LINES, LIABILITY_LINES, type ZakatLine } from "./zakat.data";

export function exportZakatPdf({
  t,
  values,
  totalAssets,
  totalLiabilities,
  zakatableWealth,
  zakatDue,
  nisabValue,
  nisabLabel,
  metalNotes,
}: {
  t: (key: string) => string;
  values: Record<string, number>;
  totalAssets: number;
  totalLiabilities: number;
  zakatableWealth: number;
  zakatDue: number;
  nisabValue: number;
  nisabLabel: string;
  metalNotes: string[];
}) {
  if (typeof window === "undefined") return;
  const rows = (lines: ZakatLine[]) =>
    lines
      .map(
        (l) =>
          `<tr><td>${t(l.label)}</td><td style="text-align:right">PKR ${formatNumber(values[l.key] || 0, 0)}</td></tr>`,
      )
      .join("");
  const notes = metalNotes.length
    ? `<p class="sub">${metalNotes.map((note) => t(note)).join(" | ")}</p>`
    : "";
  const html = `<!doctype html><html><head><meta charset="utf-8"><title>Zakat Statement - NafaIQ</title>
      <style>
        body{font-family:-apple-system,Segoe UI,Roboto,sans-serif;color:#0f172a;padding:40px;max-width:640px;margin:auto}
        h1{font-size:22px;margin:0 0 4px}p.sub{color:#64748b;margin:0 0 24px;font-size:13px}
        h2{font-size:14px;text-transform:uppercase;letter-spacing:.08em;color:#334155;margin:24px 0 8px;border-bottom:1px solid #e2e8f0;padding-bottom:6px}
        table{width:100%;border-collapse:collapse;font-size:14px}td{padding:6px 0}
        .total{font-weight:700;border-top:1px solid #cbd5e1}
        .final{margin-top:28px;padding:20px;border-radius:12px;background:#ecfdf5;text-align:center}
        .final .amt{font-size:30px;font-weight:800;color:#047857}
      </style></head><body>
      <h1>Zakat Statement</h1><p class="sub">Generated by NafaIQ - ${new Date().toLocaleDateString()}</p>
      ${notes}
      <h2>${t("Zakatable Assets")}</h2><table>${rows(ASSET_LINES)}<tr class="total"><td>${t("Total Assets")}</td><td style="text-align:right">PKR ${formatNumber(totalAssets, 0)}</td></tr></table>
      <h2>${t("Liabilities")}</h2><table>${rows(LIABILITY_LINES)}<tr class="total"><td>${t("Total Liabilities")}</td><td style="text-align:right">PKR ${formatNumber(totalLiabilities, 0)}</td></tr></table>
      <h2>Summary</h2><table>
        <tr><td>${t("Nisab Threshold")} (${t(nisabLabel)})</td><td style="text-align:right">PKR ${formatNumber(nisabValue, 0)}</td></tr>
        <tr><td>${t("Zakatable Wealth")}</td><td style="text-align:right">PKR ${formatNumber(zakatableWealth, 0)}</td></tr>
      </table>
      <div class="final"><div>${t("Zakat Due (2.5%)")}</div><div class="amt">PKR ${formatNumber(zakatDue, 0)}</div></div>
      </body></html>`;
  const w = window.open("", "_blank");
  if (!w) return;
  w.document.write(html);
  w.document.close();
  w.focus();
  setTimeout(() => w.print(), 300);
}
