-- ================================================================
-- Email-import: multi-source transaction correlation
--
-- PROBLEM
-- One financial event produces several emails. A foodpanda order generates an
-- order confirmation (foodpanda), a payment alert (the bank), and a delivery
-- confirmation (foodpanda) -- three distinct Gmail messages, so three rows in
-- user_transactions and a user whose spending looks 3x real.
--
-- The existing content dedup (repositories/finance/transactions.find_duplicate_
-- transaction) requires the merchant string to match EXACTLY, which never holds
-- across sources: the merchant mail says "foodpanda", the bank's alert says
-- "FOODPANDA PK KARACHI" or, for Bank Alfalah's template, yields "Others" and
-- falls back to "Card Purchase". The bank leg always escapes the dedup.
--
-- APPROACH
-- Stage every candidate email in email_import_messages BEFORE parsing, then
-- correlate staged messages on order ref / card tail / merchant alias / amount /
-- time and project ONE row into user_transactions, enriched as later legs land.
--
-- Per the directive in 20260712000000_consolidate_finance_onto_user_tables.sql
-- ("Email-import fields ... should be added to user_transactions rather than
-- reintroducing a parallel table"): email_import_messages is import
-- INFRASTRUCTURE -- a durable queue, audit log and retry buffer. No finance
-- endpoint, budget join, summary query or assistant tool reads it. All money
-- continues to live in user_transactions.
--
-- Run: via Supabase Dashboard SQL Editor or supabase db push
-- ================================================================

BEGIN;

-- ── 1. The staging ledger ────────────────────────────────────────────────────
-- One row per candidate email, retained permanently. This single table is the
-- "no email is ever lost" guarantee, the parse-failure log, and the retry queue.
CREATE TABLE IF NOT EXISTS public.email_import_messages (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    message_id     TEXT NOT NULL,          -- Gmail message id
    -- Gmail groups a merchant's own order/receipt/delivered mails into one
    -- thread. Free correlation evidence for the merchant-side legs; the bank's
    -- alert is always a separate thread, which is why it can never be the only
    -- signal we rely on.
    thread_id      TEXT,
    sender_domain  TEXT,
    subject        TEXT,
    received_at    TIMESTAMPTZ NOT NULL,
    internal_date  BIGINT NOT NULL,

    -- pending          -- staged, not yet parsed (or awaiting LLM budget)
    -- imported         -- became a user_transactions / user_bills row
    -- merged           -- correlated into another message's transaction
    -- duplicate        -- same email seen again
    -- failed_txn       -- a declined/failed payment: recorded, deliberately NOT imported
    -- not_transaction  -- parsed as neither a transaction nor a bill
    -- low_confidence   -- parsed below MIN_CONFIDENCE
    -- parse_error      -- transient failure; retried until attempts hits the ceiling
    verdict        TEXT NOT NULL DEFAULT 'pending',

    parsed         JSONB,                  -- the full ParsedTransaction / ParsedBill

    -- Correlation signals, denormalised out of `parsed` so the reconciler is one
    -- indexed scan instead of a JSONB dig per row.
    order_ref         TEXT,
    amount            NUMERIC(14,2),       -- PKR-normalised, as stored on the txn
    -- Set only when llm._to_pkr converted a foreign receipt. A converted leg can
    -- never equal the bank's own marked-up figure, so correlation needs to know
    -- to apply its FX tolerance -- and a merge stays explainable afterwards.
    original_amount   NUMERIC(14,2),
    original_currency TEXT,
    account_tail      TEXT,                -- last 4 of the card/account
    merchant_norm     TEXT,
    brand_token       TEXT,

    transaction_id BIGINT REFERENCES public.user_transactions(id) ON DELETE SET NULL,
    bill_id        BIGINT REFERENCES public.user_bills(id) ON DELETE SET NULL,
    error          TEXT,
    attempts       INT NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Idempotency: re-polling the same Gmail message re-stages nothing.
CREATE UNIQUE INDEX IF NOT EXISTS uq_email_import_messages_user_message
    ON public.email_import_messages(user_id, message_id);

-- The reconciler's scan: one user's recent staged messages.
CREATE INDEX IF NOT EXISTS idx_email_import_messages_recon
    ON public.email_import_messages(user_id, received_at DESC);

-- The retry queue.
CREATE INDEX IF NOT EXISTS idx_email_import_messages_retry
    ON public.email_import_messages(user_id, verdict)
    WHERE verdict IN ('pending', 'parse_error');

-- Which emails formed transaction #N -- the audit trail. Message->transaction is
-- strictly many-to-one, so this FK column replaces a separate link table.
CREATE INDEX IF NOT EXISTS idx_email_import_messages_txn
    ON public.email_import_messages(transaction_id)
    WHERE transaction_id IS NOT NULL;

-- SECURITY: holds email subjects and parsed financial detail. RLS enabled with
-- NO policy and NO grant to `authenticated`, exactly like
-- user_email_integrations -- reachable only by the backend's direct Postgres
-- connection (service role bypasses RLS).
ALTER TABLE public.email_import_messages ENABLE ROW LEVEL SECURITY;

-- ── 2. Learned merchant aliases ──────────────────────────────────────────────
-- What makes correlation merchant-agnostic in the hard case. A bank's POS
-- descriptor ("FPANDA*KHI", "TPL*FOODPANDA") shares no token with the brand, so
-- it can never alias-match on normalisation alone. When an order ref proves two
-- legs are the same event, the descriptor is recorded here and every later
-- pairing matches on it -- no code change, no hardcoded merchant list.
--
-- Scoped PER USER on purpose: one person's mail must never shape another's
-- matching, and the descriptor set is itself personal data.
CREATE TABLE IF NOT EXISTS public.email_merchant_aliases (
    user_id     UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    brand_token TEXT NOT NULL,
    alias_norm  TEXT NOT NULL,
    hits        INT NOT NULL DEFAULT 1,
    last_seen   TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, brand_token, alias_norm)
);

ALTER TABLE public.email_merchant_aliases ENABLE ROW LEVEL SECURITY;

-- ── 3. Correlation fields on user_transactions ───────────────────────────────
ALTER TABLE public.user_transactions
    ADD COLUMN IF NOT EXISTS order_ref               TEXT,
    -- Previously parsed by rules._account and then thrown away -- it only ever
    -- reached the notification string. It is the signal that ties a bank leg to
    -- a merchant leg, so it has to be persisted.
    ADD COLUMN IF NOT EXISTS account_tail            TEXT,
    ADD COLUMN IF NOT EXISTS correlation_key         TEXT,
    -- A refund/reversal points at what it reverses. The original row is never
    -- mutated: the two rows offset, so the net is right AND the history is
    -- auditable.
    ADD COLUMN IF NOT EXISTS reverses_transaction_id BIGINT
        REFERENCES public.user_transactions(id) ON DELETE SET NULL,
    -- The merge guard. Set on every user edit; the reconciler refuses to absorb
    -- or mutate any row where this is non-null, so automation can never discard
    -- a correction the user made by hand.
    ADD COLUMN IF NOT EXISTS edited_at               TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS idx_user_txns_correlation
    ON public.user_transactions(user_id, correlation_key)
    WHERE correlation_key IS NOT NULL;

-- ── 4. Content dedup key for bills ───────────────────────────────────────────
-- user_bills deduped on email_message_id only, so an invoice and the reminder
-- that follows it created two bills.
ALTER TABLE public.user_bills
    ADD COLUMN IF NOT EXISTS correlation_key TEXT;

CREATE INDEX IF NOT EXISTS idx_user_bills_correlation
    ON public.user_bills(user_id, correlation_key)
    WHERE correlation_key IS NOT NULL;

INSERT INTO public._applied_migrations (filename, applied_at)
VALUES ('20260728120000_email_import_correlation.sql', now())
ON CONFLICT (filename) DO NOTHING;

COMMIT;
