-- ================================================================
-- User Alerts + In-App Notifications + Notification Preferences
-- Run: via Supabase Dashboard SQL Editor or supabase db push
-- ================================================================

-- 1. user_alerts: app-level alerts (bill/budget/goal/stock) linked to user
CREATE TABLE IF NOT EXISTS public.user_alerts (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    type        TEXT NOT NULL CHECK (type IN ('stock_price','bill','budget','goal')),
    title       TEXT NOT NULL,
    meta        JSONB NOT NULL DEFAULT '{}'::jsonb,
    enabled     BOOLEAN NOT NULL DEFAULT true,
    triggered_at TIMESTAMPTZ,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_user_alerts_user ON public.user_alerts(user_id);
CREATE INDEX IF NOT EXISTS idx_user_alerts_enabled ON public.user_alerts(enabled) WHERE enabled = true;
ALTER TABLE public.user_alerts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users own their alerts" ON public.user_alerts
    FOR ALL TO authenticated
    USING (user_id = auth.uid())
    WITH CHECK (user_id = auth.uid());
GRANT ALL ON public.user_alerts TO authenticated;

-- 2. in_app_notifications: notification history
CREATE TABLE IF NOT EXISTS public.in_app_notifications (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    kind        TEXT NOT NULL CHECK (kind IN ('price_alert','bill','budget','goal','system')),
    title       TEXT NOT NULL,
    body        TEXT NOT NULL,
    link        TEXT,
    read        BOOLEAN NOT NULL DEFAULT false,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_in_app_notif_user ON public.in_app_notifications(user_id, read, created_at DESC);
ALTER TABLE public.in_app_notifications ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users own their notifications" ON public.in_app_notifications
    FOR ALL TO authenticated
    USING (user_id = auth.uid())
    WITH CHECK (user_id = auth.uid());
GRANT ALL ON public.in_app_notifications TO authenticated;

-- 3. user_notification_prefs: channel preferences (1:1 with user)
CREATE TABLE IF NOT EXISTS public.user_notification_prefs (
    user_id         UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email_alerts    BOOLEAN NOT NULL DEFAULT true,
    push_alerts     BOOLEAN NOT NULL DEFAULT false,
    in_app_alerts   BOOLEAN NOT NULL DEFAULT true,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE public.user_notification_prefs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users own their notification prefs" ON public.user_notification_prefs
    FOR ALL TO authenticated
    USING (user_id = auth.uid())
    WITH CHECK (user_id = auth.uid());
GRANT ALL ON public.user_notification_prefs TO authenticated;
