-- ============================================================================
-- Zakat Settings and Records
-- Per-user zakat configuration (1:1) and historical calculation records (1:N).
-- Calculation is intentionally simple and configurable; future enhancement
-- can swap in gold/silver nisab and exclusions without schema change.
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.user_zakat_settings (
    user_id              UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    method               TEXT NOT NULL DEFAULT 'standard_2_5'
                         CHECK (method IN ('standard_2_5', 'custom_rate', 'manual_only')),
    custom_rate_pct      NUMERIC(5,2)
                         CHECK (custom_rate_pct IS NULL OR (custom_rate_pct > 0 AND custom_rate_pct <= 100)),
    nisab_source         TEXT NOT NULL DEFAULT 'gold'
                         CHECK (nisab_source IN ('gold', 'silver', 'cash', 'manual')),
    nisab_value_pkr      NUMERIC(14,2) CHECK (nisab_value_pkr IS NULL OR nisab_value_pkr > 0),
    include_cash         BOOLEAN NOT NULL DEFAULT TRUE,
    include_investments  BOOLEAN NOT NULL DEFAULT TRUE,
    include_receivables  BOOLEAN NOT NULL DEFAULT FALSE,
    notes                TEXT,
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.user_zakat_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users own their zakat settings"
    ON public.user_zakat_settings
    FOR ALL
    TO authenticated
    USING (user_id = auth.uid())
    WITH CHECK (user_id = auth.uid());

GRANT ALL ON public.user_zakat_settings TO authenticated;
GRANT ALL ON public.user_zakat_settings TO service_role;

DROP TRIGGER IF EXISTS update_user_zakat_settings_updated_at ON public.user_zakat_settings;
CREATE TRIGGER update_user_zakat_settings_updated_at
    BEFORE UPDATE ON public.user_zakat_settings
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TABLE IF NOT EXISTS public.user_zakat_records (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    islamic_year      TEXT NOT NULL,
    method            TEXT NOT NULL,
    nisab_value_pkr   NUMERIC(14,2) NOT NULL,
    total_assets_pkr  NUMERIC(14,2) NOT NULL,
    total_deductions_pkr NUMERIC(14,2) NOT NULL DEFAULT 0,
    net_zakatable_pkr NUMERIC(14,2) NOT NULL,
    rate_pct          NUMERIC(5,2) NOT NULL,
    zakat_due_pkr     NUMERIC(14,2) NOT NULL,
    breakdown         JSONB NOT NULL DEFAULT '{}'::jsonb,
    calculated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (user_id, islamic_year, method)
);

CREATE INDEX IF NOT EXISTS idx_user_zakat_records_user
    ON public.user_zakat_records(user_id, islamic_year DESC);

ALTER TABLE public.user_zakat_records ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users own their zakat records"
    ON public.user_zakat_records
    FOR ALL
    TO authenticated
    USING (user_id = auth.uid())
    WITH CHECK (user_id = auth.uid());

GRANT ALL ON public.user_zakat_records TO authenticated;
GRANT ALL ON public.user_zakat_records TO service_role;
