-- ============================================================================
-- Alert Events (Notification History)
-- Stores every time an alert fires. This is the notification history
-- that the user can browse in the Alerts page.
-- Push/email delivery is intentionally not implemented; this table
-- captures the trigger event and can be extended later.
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.alert_events (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    alert_id      BIGINT,
    alert_type    TEXT NOT NULL
                  CHECK (alert_type IN ('stock_price', 'bill', 'budget', 'goal', 'system')),
    symbol        TEXT,
    title         TEXT NOT NULL,
    body          TEXT NOT NULL,
    payload       JSONB NOT NULL DEFAULT '{}'::jsonb,
    channel       TEXT NOT NULL DEFAULT 'in_app'
                  CHECK (channel IN ('in_app', 'email', 'push')),
    delivered_at  TIMESTAMPTZ,
    read_at       TIMESTAMPTZ,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_alert_events_user
    ON public.alert_events(user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_alert_events_type
    ON public.alert_events(alert_type, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_alert_events_symbol
    ON public.alert_events(symbol) WHERE symbol IS NOT NULL;

ALTER TABLE public.alert_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users own their alert events"
    ON public.alert_events
    FOR ALL
    TO authenticated
    USING (user_id = auth.uid())
    WITH CHECK (user_id = auth.uid());

GRANT ALL ON public.alert_events TO authenticated;
GRANT ALL ON public.alert_events TO service_role;
