-- ============================================================================
-- Stock Transactions
-- Lot-level records of every buy/sell of a stock symbol.
-- Aggregated into psx_holdings on insert.
-- Independent of psx_holdings so the user can see transaction history
-- (and so future email scraping of brokerage emails can be ingested here).
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.stock_transactions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    portfolio_id  BIGINT NOT NULL REFERENCES public.psx_portfolios(id) ON DELETE CASCADE,
    symbol        TEXT NOT NULL,
    side          TEXT NOT NULL CHECK (side IN ('buy', 'sell', 'adjust')),
    quantity      BIGINT NOT NULL CHECK (quantity > 0),
    price         NUMERIC(12,4) NOT NULL CHECK (price >= 0),
    fees          NUMERIC(12,4) NOT NULL DEFAULT 0 CHECK (fees >= 0),
    executed_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    notes         TEXT,
    source        TEXT NOT NULL DEFAULT 'manual'
                  CHECK (source IN ('manual', 'brokerage_email', 'import', 'api')),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_stock_tx_user_date
    ON public.stock_transactions(user_id, executed_at DESC);

CREATE INDEX IF NOT EXISTS idx_stock_tx_portfolio
    ON public.stock_transactions(portfolio_id);

CREATE INDEX IF NOT EXISTS idx_stock_tx_symbol
    ON public.stock_transactions(symbol, executed_at DESC);

ALTER TABLE public.stock_transactions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users own their stock transactions"
    ON public.stock_transactions
    FOR ALL
    TO authenticated
    USING (user_id = auth.uid())
    WITH CHECK (user_id = auth.uid());

GRANT ALL ON public.stock_transactions TO authenticated;
GRANT ALL ON public.stock_transactions TO service_role;

-- updated_at trigger
DROP TRIGGER IF EXISTS update_stock_transactions_updated_at ON public.stock_transactions;
CREATE TRIGGER update_stock_transactions_updated_at
    BEFORE UPDATE ON public.stock_transactions
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
