-- ================================================================
-- PSX Module: Realtime + Signal Engine + Watchlist tables
-- Run: via Supabase Dashboard SQL Editor or supabase db push
-- ================================================================

-- 14. Enable Supabase Realtime on the market snapshot table
-- This allows the frontend to subscribe to live tick updates
ALTER PUBLICATION supabase_realtime ADD TABLE public.psx_market_snapshot;

-- 15. Signal cache (ML predictions cached with TTL)
CREATE TABLE IF NOT EXISTS public.psx_signals (
    symbol          TEXT PRIMARY KEY,
    signal          TEXT NOT NULL,
    confidence      NUMERIC(5,2) NOT NULL,
    probabilities   JSONB,
    features_used   TEXT[],
    model_version   TEXT,
    predicted_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(symbol)
);
CREATE INDEX IF NOT EXISTS idx_psx_signals_confidence ON public.psx_signals(confidence DESC);
CREATE INDEX IF NOT EXISTS idx_psx_signals_predicted ON public.psx_signals(predicted_at DESC);
ALTER TABLE public.psx_signals ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read signals" ON public.psx_signals FOR SELECT USING (true);
GRANT SELECT ON public.psx_signals TO anon, authenticated;
GRANT ALL ON public.psx_signals TO service_role;

-- 16. User watchlist
CREATE TABLE IF NOT EXISTS public.user_watchlist (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    symbol      TEXT NOT NULL,
    added_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(user_id, symbol)
);
CREATE INDEX IF NOT EXISTS idx_user_watchlist_user ON public.user_watchlist(user_id);
ALTER TABLE public.user_watchlist ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users own their watchlist" ON public.user_watchlist
    FOR ALL TO authenticated
    USING (user_id = auth.uid())
    WITH CHECK (user_id = auth.uid());
GRANT ALL ON public.user_watchlist TO authenticated;

-- 17. Price alerts
CREATE TABLE IF NOT EXISTS public.price_alerts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    symbol          TEXT NOT NULL,
    condition       TEXT NOT NULL CHECK (condition IN ('above', 'below', 'cross_above', 'cross_below')),
    price           NUMERIC(14,2) NOT NULL,
    enabled         BOOLEAN NOT NULL DEFAULT true,
    triggered_at    TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_price_alerts_user ON public.price_alerts(user_id);
CREATE INDEX IF NOT EXISTS idx_price_alerts_enabled ON public.price_alerts(enabled) WHERE enabled = true;
ALTER TABLE public.price_alerts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users own their alerts" ON public.price_alerts
    FOR ALL TO authenticated
    USING (user_id = auth.uid())
    WITH CHECK (user_id = auth.uid());
GRANT ALL ON public.price_alerts TO authenticated;
