-- LearnHub AI Studio: private projects over reusable, source-grounded artifacts.
-- All browser access goes through FastAPI; authenticated/anon roles receive no
-- direct table or storage metadata access.
BEGIN;

CREATE TABLE IF NOT EXISTS public.learnhub_sources (
    source_key text PRIMARY KEY,
    publisher text NOT NULL,
    title text NOT NULL,
    canonical_url text,
    published_at timestamptz,
    retrieved_at timestamptz NOT NULL DEFAULT now(),
    approved boolean NOT NULL DEFAULT false,
    content_hash text NOT NULL,
    corpus_version text NOT NULL DEFAULT '1',
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.learnhub_knowledge_chunks
    ADD COLUMN IF NOT EXISTS source_key text REFERENCES public.learnhub_sources(source_key);

CREATE TABLE IF NOT EXISTS public.learnhub_studio_artifacts (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    fingerprint text NOT NULL UNIQUE,
    language text NOT NULL CHECK (language IN ('en', 'ur')),
    level text NOT NULL CHECK (level IN ('beginner', 'intermediate', 'advanced')),
    target_minutes smallint NOT NULL DEFAULT 4 CHECK (target_minutes BETWEEN 3 AND 5),
    corpus_version text NOT NULL,
    prompt_version text NOT NULL,
    renderer_version text NOT NULL DEFAULT '1',
    status text NOT NULL DEFAULT 'generating'
        CHECK (status IN ('generating', 'ready', 'failed')),
    quality_status text NOT NULL DEFAULT 'pending'
        CHECK (quality_status IN ('pending', 'approved', 'rejected')),
    study_pack jsonb,
    source_snapshot jsonb NOT NULL DEFAULT '[]'::jsonb,
    video_object_path text,
    caption_object_path text,
    thumbnail_object_path text,
    video_duration_seconds integer,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.learnhub_studio_projects (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    artifact_id uuid REFERENCES public.learnhub_studio_artifacts(id),
    topic text NOT NULL,
    normalized_topic text NOT NULL,
    language text NOT NULL CHECK (language IN ('en', 'ur')),
    level text NOT NULL CHECK (level IN ('beginner', 'intermediate', 'advanced')),
    target_minutes smallint NOT NULL DEFAULT 4 CHECK (target_minutes BETWEEN 3 AND 5),
    status text NOT NULL DEFAULT 'queued'
        CHECK (status IN ('queued', 'generating', 'ready', 'unsupported', 'failed')),
    stage text NOT NULL DEFAULT 'queued',
    error_code text,
    error_message text,
    best_score integer NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_learnhub_studio_projects_user
    ON public.learnhub_studio_projects(user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS public.learnhub_generation_jobs (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id uuid NOT NULL REFERENCES public.learnhub_studio_projects(id) ON DELETE CASCADE,
    kind text NOT NULL CHECK (kind IN ('study_pack', 'video')),
    status text NOT NULL DEFAULT 'queued'
        CHECK (status IN ('queued', 'running', 'completed', 'failed')),
    stage text NOT NULL DEFAULT 'queued',
    attempts integer NOT NULL DEFAULT 0,
    max_attempts integer NOT NULL DEFAULT 3,
    available_at timestamptz NOT NULL DEFAULT now(),
    locked_at timestamptz,
    locked_by text,
    last_error text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE(project_id, kind)
);
CREATE INDEX IF NOT EXISTS idx_learnhub_generation_jobs_claim
    ON public.learnhub_generation_jobs(status, available_at, created_at);

CREATE TABLE IF NOT EXISTS public.learnhub_studio_quiz_attempts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id uuid NOT NULL REFERENCES public.learnhub_studio_projects(id) ON DELETE CASCADE,
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    correct integer NOT NULL CHECK (correct >= 0),
    total integer NOT NULL CHECK (total > 0 AND correct <= total),
    answers jsonb NOT NULL DEFAULT '[]'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.learnhub_studio_usage (
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    day date NOT NULL,
    pack_count integer NOT NULL DEFAULT 0 CHECK (pack_count >= 0),
    video_count integer NOT NULL DEFAULT 0 CHECK (video_count >= 0),
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, day)
);

ALTER TABLE public.learnhub_sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.learnhub_studio_artifacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.learnhub_studio_projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.learnhub_generation_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.learnhub_studio_quiz_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.learnhub_studio_usage ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.learnhub_sources FROM anon, authenticated;
REVOKE ALL ON TABLE public.learnhub_studio_artifacts FROM anon, authenticated;
REVOKE ALL ON TABLE public.learnhub_studio_projects FROM anon, authenticated;
REVOKE ALL ON TABLE public.learnhub_generation_jobs FROM anon, authenticated;
REVOKE ALL ON TABLE public.learnhub_studio_quiz_attempts FROM anon, authenticated;
REVOKE ALL ON TABLE public.learnhub_studio_usage FROM anon, authenticated;
GRANT ALL ON TABLE public.learnhub_sources TO service_role;
GRANT ALL ON TABLE public.learnhub_studio_artifacts TO service_role;
GRANT ALL ON TABLE public.learnhub_studio_projects TO service_role;
GRANT ALL ON TABLE public.learnhub_generation_jobs TO service_role;
GRANT ALL ON TABLE public.learnhub_studio_quiz_attempts TO service_role;
GRANT ALL ON TABLE public.learnhub_studio_usage TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.learnhub_studio_quiz_attempts_id_seq TO service_role;

COMMIT;
