-- User-defined payment methods for finance transactions.
-- The selected label is still written onto user_transactions.source; this table
-- stores each user's reusable picker options.

BEGIN;

CREATE TABLE IF NOT EXISTS public.user_payment_methods (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     UUID NOT NULL,
    label       TEXT NOT NULL,
    label_key   TEXT GENERATED ALWAYS AS (lower(btrim(label))) STORED,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT user_payment_methods_label_not_blank CHECK (length(btrim(label)) > 0),
    CONSTRAINT user_payment_methods_label_len CHECK (length(btrim(label)) <= 80),
    CONSTRAINT user_payment_methods_user_label_unique UNIQUE (user_id, label_key)
);

CREATE INDEX IF NOT EXISTS idx_user_payment_methods_user
    ON public.user_payment_methods(user_id, created_at DESC);

ALTER TABLE public.user_payment_methods ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users own their payment methods" ON public.user_payment_methods;
CREATE POLICY "Users own their payment methods"
    ON public.user_payment_methods
    FOR ALL TO authenticated
    USING (user_id = auth.uid())
    WITH CHECK (user_id = auth.uid());

GRANT ALL ON public.user_payment_methods TO authenticated;
GRANT ALL ON public.user_payment_methods TO service_role;

INSERT INTO public._applied_migrations (filename, applied_at)
VALUES ('20260722170000_user_payment_methods.sql', now())
ON CONFLICT (filename) DO NOTHING;

COMMIT;
