-- ================================================================
-- User Finance: transactions, goals, budgets, bills, settings
-- Run: via Supabase Dashboard SQL Editor
-- ================================================================

-- 1. user_transactions: income/expense tracking
CREATE TABLE IF NOT EXISTS public.user_transactions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         UUID NOT NULL,
    merchant        TEXT NOT NULL,
    amount          NUMERIC(12,2) NOT NULL,
    currency        TEXT NOT NULL DEFAULT 'PKR',
    transaction_type TEXT NOT NULL,
    category        TEXT NOT NULL,
    transaction_date TIMESTAMPTZ NOT NULL DEFAULT now(),
    source          TEXT DEFAULT 'manual',
    note            TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_user_txns_user ON public.user_transactions(user_id, transaction_date DESC);
ALTER TABLE public.user_transactions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users own their transactions" ON public.user_transactions
    FOR ALL TO authenticated
    USING (user_id = auth.uid())
    WITH CHECK (user_id = auth.uid());
GRANT ALL ON public.user_transactions TO authenticated;

-- 2. user_goals: savings goals
CREATE TABLE IF NOT EXISTS public.user_goals (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     UUID NOT NULL,
    emoji       TEXT NOT NULL DEFAULT '🎯',
    name        TEXT NOT NULL,
    target      NUMERIC(12,2) NOT NULL,
    saved       NUMERIC(12,2) NOT NULL DEFAULT 0,
    color       TEXT NOT NULL DEFAULT 'bull',
    ai_tip      TEXT,
    target_date TIMESTAMPTZ,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_user_goals_user ON public.user_goals(user_id, created_at DESC);
ALTER TABLE public.user_goals ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users own their goals" ON public.user_goals
    FOR ALL TO authenticated
    USING (user_id = auth.uid())
    WITH CHECK (user_id = auth.uid());
GRANT ALL ON public.user_goals TO authenticated;

-- 3. user_budgets: budget categories
CREATE TABLE IF NOT EXISTS public.user_budgets (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     UUID NOT NULL,
    category    TEXT NOT NULL,
    spent       NUMERIC(12,2) NOT NULL DEFAULT 0,
    limit_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
    period      TEXT NOT NULL DEFAULT 'monthly',
    tip         TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_user_budgets_user ON public.user_budgets(user_id);
ALTER TABLE public.user_budgets ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users own their budgets" ON public.user_budgets
    FOR ALL TO authenticated
    USING (user_id = auth.uid())
    WITH CHECK (user_id = auth.uid());
GRANT ALL ON public.user_budgets TO authenticated;

-- 4. user_bills: upcoming bills
CREATE TABLE IF NOT EXISTS public.user_bills (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     UUID NOT NULL,
    name        TEXT NOT NULL,
    amount      NUMERIC(12,2) NOT NULL,
    currency    TEXT NOT NULL DEFAULT 'PKR',
    due_date    DATE,
    status      TEXT NOT NULL DEFAULT 'UPCOMING',
    recurring   BOOLEAN NOT NULL DEFAULT false,
    paid_at     TIMESTAMPTZ,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_user_bills_user ON public.user_bills(user_id, due_date);
ALTER TABLE public.user_bills ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users own their bills" ON public.user_bills
    FOR ALL TO authenticated
    USING (user_id = auth.uid())
    WITH CHECK (user_id = auth.uid());
GRANT ALL ON public.user_bills TO authenticated;

-- 5. user_settings: per-user settings (1:1)
CREATE TABLE IF NOT EXISTS public.user_settings (
    user_id         UUID PRIMARY KEY,
    monthly_income  NUMERIC(12,2) DEFAULT 0,
    currency        TEXT NOT NULL DEFAULT 'PKR',
    language        TEXT NOT NULL DEFAULT 'en',
    plan            TEXT NOT NULL DEFAULT 'Free',
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE public.user_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users own their settings" ON public.user_settings
    FOR ALL TO authenticated
    USING (user_id = auth.uid())
    WITH CHECK (user_id = auth.uid());
GRANT ALL ON public.user_settings TO authenticated;
