-- ---------------------------------------------------------------------------
-- Error tracking + user bug reports.
--
-- Before this, nothing captured a user-facing failure: the frontend
-- ErrorBoundary only console.error'd, backend exceptions went to stdout (
-- ephemeral on Railway, not queryable, not per-user), and there was no
-- error-tracking SDK. If a user's page crashed, nobody found out unless they
-- emailed support. And they had no way to tell us.
--
-- Two separate concerns, two tables:
--   * app_error_* — MACHINE-captured. High volume, no human intent, needs
--     grouping so one bad deploy is one row and not ten thousand.
--   * bug_reports — HUMAN-authored. Low volume, has a narrative, needs a triage
--     lifecycle and a reply.
--
-- Idempotent: safe to re-run.
-- ---------------------------------------------------------------------------

-- ── 1. Error groups ─────────────────────────────────────────────────────────
-- One row per distinct failure, keyed by a fingerprint computed at ingest.
-- Triage state lives HERE rather than on the event, because "resolved" is a
-- property of the bug, not of one occurrence of it.
CREATE TABLE IF NOT EXISTS public.app_error_groups (
    fingerprint     TEXT PRIMARY KEY,
    source          TEXT NOT NULL CHECK (source IN ('client', 'server')),
    message         TEXT NOT NULL,
    route           TEXT,
    sample_stack    TEXT,
    status          TEXT NOT NULL DEFAULT 'open'
                    CHECK (status IN ('open', 'investigating', 'resolved', 'ignored')),
    -- Denormalised counters. Kept on the group so the admin list is a single
    -- indexed scan instead of an aggregate over the event table.
    event_count     BIGINT NOT NULL DEFAULT 0,
    first_seen      TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen       TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- Set when an admin marks it resolved; cleared if it recurs afterwards.
    resolved_at     TIMESTAMPTZ,
    resolved_by     UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    admin_note      TEXT
);

CREATE INDEX IF NOT EXISTS idx_app_error_groups_triage
    ON public.app_error_groups(status, last_seen DESC);

-- ── 2. Error events ─────────────────────────────────────────────────────────
-- The individual occurrences. Deliberately narrow: no request bodies, no
-- headers, no query strings — those are the usual way an error tracker turns
-- into an unmanaged PII store.
CREATE TABLE IF NOT EXISTS public.app_error_events (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fingerprint     TEXT NOT NULL REFERENCES public.app_error_groups(fingerprint) ON DELETE CASCADE,
    -- Nullable: an error can happen before sign-in, and the row must survive
    -- the user being deleted or anonymised.
    user_id         UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    source          TEXT NOT NULL CHECK (source IN ('client', 'server')),
    message         TEXT NOT NULL,
    route           TEXT,
    stack           TEXT,
    status_code     INT,
    app_version     TEXT,
    user_agent      TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_app_error_events_group
    ON public.app_error_events(fingerprint, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_app_error_events_user
    ON public.app_error_events(user_id, created_at DESC)
    WHERE user_id IS NOT NULL;
-- Supports the retention sweep.
CREATE INDEX IF NOT EXISTS idx_app_error_events_created
    ON public.app_error_events(created_at);

-- ── 3. Bug reports ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.bug_reports (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    title           TEXT NOT NULL,
    description     TEXT NOT NULL,
    category        TEXT NOT NULL DEFAULT 'bug'
                    CHECK (category IN ('bug', 'data', 'billing', 'feature', 'other')),
    -- What the user was looking at. Saves the "which page?" round-trip that
    -- makes most bug reports unusable.
    route           TEXT,
    app_version     TEXT,
    user_agent      TEXT,
    -- Set when the report is filed from an error screen, so a human report and
    -- the machine capture of the same failure can be read together.
    error_fingerprint TEXT REFERENCES public.app_error_groups(fingerprint) ON DELETE SET NULL,
    status          TEXT NOT NULL DEFAULT 'open'
                    CHECK (status IN ('open', 'investigating', 'resolved', 'wont_fix')),
    admin_note      TEXT,
    resolved_at     TIMESTAMPTZ,
    resolved_by     UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_bug_reports_triage
    ON public.bug_reports(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_bug_reports_user
    ON public.bug_reports(user_id, created_at DESC);

-- ── 4. RLS ──────────────────────────────────────────────────────────────────
-- Error tables are service_role only. A user must never be able to read other
-- users' stack traces, and ingest goes through the backend (which owns the
-- fingerprinting), never straight from the browser to PostgREST.
ALTER TABLE public.app_error_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_error_events ENABLE ROW LEVEL SECURITY;

-- Bug reports: a user owns their own. Admin access is via the backend's
-- service_role client, so no admin policy is needed here.
ALTER TABLE public.bug_reports ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users read their own bug reports" ON public.bug_reports;
CREATE POLICY "Users read their own bug reports" ON public.bug_reports
    FOR SELECT TO authenticated
    USING (user_id = auth.uid());

DROP POLICY IF EXISTS "Users file their own bug reports" ON public.bug_reports;
CREATE POLICY "Users file their own bug reports" ON public.bug_reports
    FOR INSERT TO authenticated
    WITH CHECK (user_id = auth.uid());

-- Deliberately NO update/delete policy: a user cannot edit a filed report or
-- change its triage status. Corrections come as a new report.
GRANT SELECT, INSERT ON public.bug_reports TO authenticated;

-- ── 5. Admin permissions ────────────────────────────────────────────────────
INSERT INTO public.admin_permissions (slug, description) VALUES
    ('errors.read',   'View captured application errors.'),
    ('errors.write',  'Triage application errors (resolve, ignore, annotate).'),
    ('support.read',  'View user-submitted bug reports.'),
    ('support.write', 'Triage and respond to user bug reports.')
ON CONFLICT (slug) DO UPDATE SET description = EXCLUDED.description;

-- Standing rules.
INSERT INTO public.admin_role_permissions (role_slug, permission_slug)
    SELECT 'super_admin', slug FROM public.admin_permissions
ON CONFLICT DO NOTHING;

INSERT INTO public.admin_role_permissions (role_slug, permission_slug)
    SELECT 'analyst_readonly', slug FROM public.admin_permissions WHERE slug LIKE '%.read'
ON CONFLICT DO NOTHING;

-- support_admin is the front line for user reports; data_admin watches errors
-- as part of platform health.
INSERT INTO public.admin_role_permissions (role_slug, permission_slug) VALUES
    ('support_admin', 'support.read'),
    ('support_admin', 'support.write'),
    ('support_admin', 'errors.read'),
    ('data_admin',    'errors.read'),
    ('data_admin',    'errors.write')
ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- Migration ledger
-- ---------------------------------------------------------------------------
INSERT INTO public._applied_migrations (filename) VALUES
    ('20260728180000_error_tracking_and_bug_reports.sql')
ON CONFLICT (filename) DO NOTHING;
