/** Translation dictionary. Keys are English source strings. */
export const UR: Record<string, string> = {
  // Nav
  Dashboard: "ڈیش بورڈ",
  "PSX Market": "پی ایس ایکس مارکیٹ",
  Portfolio: "پورٹ فولیو",
  Finance: "مالیات",
  "Learn Hub": "لرن ہب",
  Alerts: "الرٹس",
  Markets: "مارکیٹس",
  Settings: "ترتیبات",
  Profile: "پروفائل",
  "Plans / Upgrade": "پلانز / اپ گریڈ",
  Logout: "لاگ آؤٹ",
  "Sign out": "سائن آؤٹ",
  More: "مزید",
  Lesson: "سبق",
  // Header / common
  "Upgrade to Pro": "پرو میں اپ گریڈ کریں",
  "Free plan": "مفت پلان",
  Home: "ہوم",
  Learn: "سیکھیں",
  // Settings page
  "Personalise how NafaIQ looks and feels.":
    "نفع آئی کیو کی شکل و صورت کو اپنی پسند کے مطابق بنائیں۔",
  Appearance: "ظاہری شکل",
  "Choose the theme for your dashboard. This applies to the app only — the public site stays dark.":
    "اپنے ڈیش بورڈ کے لیے تھیم منتخب کریں۔ یہ صرف ایپ پر لاگو ہوتا ہے — عوامی سائٹ تاریک رہتی ہے۔",
  Dark: "تاریک",
  Light: "روشن",
  "Default OLED-friendly terminal look": "ڈیفالٹ OLED دوست ٹرمینل لُک",
  "Bright, high-contrast daytime view": "روشن، ہائی کنٹراسٹ دن کا منظر",
  Language: "زبان",
  "Choose the language for the app interface.": "ایپ انٹرفیس کے لیے زبان منتخب کریں۔",
  English: "انگریزی",
  Urdu: "اردو",
  "Standard interface language": "معیاری انٹرفیس زبان",
  "Right-to-left Urdu interface": "دائیں سے بائیں اردو انٹرفیس",
  Account: "اکاؤنٹ",
  Name: "نام",
  Email: "ای میل",
  Plan: "پلان",

  // Settings → change password
  Password: "پاس ورڈ",
  "Changing your password signs you out everywhere else.":
    "پاس ورڈ تبدیل کرنے سے آپ ہر دوسری جگہ سے سائن آؤٹ ہو جائیں گے۔",
  "Current password": "موجودہ پاس ورڈ",
  "New password": "نیا پاس ورڈ",
  "Confirm new password": "نئے پاس ورڈ کی تصدیق کریں",
  "Update password": "پاس ورڈ اپ ڈیٹ کریں",
  "Show password": "پاس ورڈ دکھائیں",
  "Hide password": "پاس ورڈ چھپائیں",
  "Current password is incorrect.": "موجودہ پاس ورڈ غلط ہے۔",
  "Password must be at least 8 characters.": "پاس ورڈ کم از کم 8 حروف کا ہونا چاہیے۔",
  "Those passwords don't match.": "یہ پاس ورڈ آپس میں مطابقت نہیں رکھتے۔",
  "Your new password must be different from your current one.":
    "آپ کا نیا پاس ورڈ موجودہ پاس ورڈ سے مختلف ہونا چاہیے۔",
  "Password updated. Other devices have been signed out.":
    "پاس ورڈ اپ ڈیٹ ہو گیا۔ دیگر آلات سے سائن آؤٹ کر دیا گیا ہے۔",

  // ---- Shared stat / metric labels ----
  "Portfolio Value": "پورٹ فولیو ویلیو",
  "Total Invested": "کل سرمایہ کاری",
  "Total Gain": "کل منافع",
  "Today's P/L": "آج کا نفع/نقصان",
  "Today's PSX P/L": "آج کا پی ایس ایکس نفع/نقصان",
  "Monthly Spending": "ماہانہ اخراجات",
  "Total Net Worth": "کل مجموعی مالیت",
  "Monthly Income": "ماہانہ آمدنی",
  "Total Expenses": "کل اخراجات",
  "Net Savings": "خالص بچت",
  "Savings Rate": "بچت کی شرح",
  Expenses: "اخراجات",
  "vs last month": "پچھلے ماہ کے مقابلے",
  Excellent: "بہترین",
  "Goal: 65%": "ہدف: 65%",
  "6-month totals": "6 ماہ کے کل اعداد",
  "in real terms": "حقیقی اعتبار سے",

  // ---- Dashboard ----
  "Explore PSX": "پی ایس ایکس دیکھیں",
  "Add Transaction": "ٹرانزیکشن شامل کریں",
  "AI Recommendation": "اے آئی تجویز",
  View: "دیکھیں",
  Dismiss: "نظر انداز کریں",
  "Spending Breakdown": "اخراجات کی تفصیل",
  Watchlist: "واچ لسٹ",
  "Savings Goals": "بچت کے اہداف",
  "PKR total": "کل روپے",

  // ---- Portfolio ----
  "Performance vs KSE-100": "کارکردگی بمقابلہ کے ایس ای-100",
  "Outperforming benchmark by +3.2%": "بینچ مارک سے +3.2% بہتر کارکردگی",
  "Haqeeqi Daulat™ — Your REAL Returns": "حقیقی دولت™ — آپ کا اصل منافع",
  "After 16.2% PKR devaluation": "16.2% روپے کی قدر میں کمی کے بعد",
  "Nominal PKR Gain": "برائے نام روپے منافع",
  "PKR Devaluation": "روپے کی قدر میں کمی",
  "Real USD Return": "اصل ڈالر منافع",
  "Devaluation Shield Score": "قدر کمی شیلڈ اسکور",
  "Moderate risk": "درمیانہ خطرہ",
  "Improve Score": "اسکور بہتر بنائیں",
  "Allocation by Sector": "شعبے کے لحاظ سے تقسیم",
  "Allocation by Stock": "اسٹاک کے لحاظ سے تقسیم",
  Holdings: "ملکیتی اسٹاکس",
  Stock: "اسٹاک",
  Sector: "شعبہ",
  Shares: "حصص",
  "Avg Cost": "اوسط لاگت",
  Current: "موجودہ",
  "Mkt Value": "مارکیٹ ویلیو",
  "Gain/Loss": "نفع/نقصان",
  Signal: "سگنل",
  Action: "ایکشن",
  "Add Holding": "ہولڈنگ شامل کریں",
  "Edit Holding": "ہولڈنگ میں ترمیم کریں",
  "Save Changes": "تبدیلیاں محفوظ کریں",
  Edit: "ترمیم",
  Delete: "حذف کریں",
  "No holdings yet. Add your first position.": "ابھی کوئی ہولڈنگ نہیں۔ اپنی پہلی پوزیشن شامل کریں۔",
  "Stock symbol (e.g. HBL)": "اسٹاک علامت (مثلاً HBL)",
  "Avg Cost (PKR)": "اوسط لاگت (روپے)",
  "Current price (PKR, optional)": "موجودہ قیمت (روپے، اختیاری)",
  "Please enter a stock symbol.": "براہ کرم اسٹاک علامت درج کریں۔",
  "Please enter a sector.": "براہ کرم شعبہ درج کریں۔",
  "Please enter a valid number of shares.": "براہ کرم درست تعداد میں حصص درج کریں۔",
  "Please enter a valid average cost.": "براہ کرم درست اوسط لاگت درج کریں۔",
  "AI Portfolio Report": "اے آئی پورٹ فولیو رپورٹ",
  "Get a plain-English analysis — diversification score, risk assessment, top opportunities, and suggested rebalancing.":
    "سادہ زبان میں تجزیہ حاصل کریں — تنوع اسکور، خطرے کا جائزہ، بہترین مواقع اور تجویز کردہ ری بیلنسنگ۔",
  "Generate Report": "رپورٹ بنائیں",
  "Analyzing…": "تجزیہ ہو رہا ہے…",
  "AI Finance Report": "اے آئی مالیاتی رپورٹ",
  "Things to consider": "غور کرنے کی باتیں",
  "Please sign in to generate your report.": "اپنی رپورٹ بنانے کے لیے براہ کرم سائن اِن کریں۔",
  "You've reached your AI report limit for this period. Upgrade your plan to generate more.":
    "آپ اس مدت کے لیے اپنی اے آئی رپورٹ کی حد تک پہنچ چکے ہیں۔ مزید بنانے کے لیے اپنا پلان اپ گریڈ کریں۔",
  "This report is temporarily unavailable. Please try again shortly.":
    "یہ رپورٹ عارضی طور پر دستیاب نہیں ہے۔ براہ کرم تھوڑی دیر بعد دوبارہ کوشش کریں۔",
  "Couldn't generate your report. Please try again.":
    "آپ کی رپورٹ نہیں بن سکی۔ براہ کرم دوبارہ کوشش کریں۔",
  "Health Score": "ہیلتھ اسکور",
  "Export as PDF": "پی ڈی ایف ایکسپورٹ کریں",
  Close: "بند کریں",

  // ---- PSX ----
  "Stock Screener": "اسٹاک اسکرینر",
  Price: "قیمت",
  Change: "تبدیلی",
  Volume: "حجم",
  "Mkt Cap": "مارکیٹ کیپ",
  "Sector Heatmap": "سیکٹر ہیٹ میپ",
  "Add Stock": "اسٹاک شامل کریں",
  // Watchlist row delete button, e.g. "Remove HBL from watchlist".
  Remove: "ہٹائیں",
  "from watchlist": "واچ لسٹ سے",
  // Shown when the server refuses an add/remove and the optimistic update is
  // rolled back — the user must know the row snapped back on purpose.
  "Could not remove": "ہٹایا نہیں جا سکا",
  "Could not add": "شامل نہیں کیا جا سکا",
  "Please try again.": "براہ کرم دوبارہ کوشش کریں۔",
  // Heatmap tiles are sized by size_metric — a real market cap where we have
  // listed_shares, a volume proxy otherwise. "By Size" over "By Market Cap".
  "By Size": "سائز کے حساب سے",
  "Tile size": "ٹائل کا سائز",
  "Volume-based estimate": "حجم پر مبنی تخمینہ",

  // ---- Finance ----
  "Saved this month": "اس ماہ بچایا",
  "Personal Finance": "ذاتی مالیات",
  Overview: "جائزہ",
  Transactions: "ٹرانزیکشنز",
  Budgets: "بجٹ",
  Bills: "بل",
  Goals: "اہداف",
  "Net Savings Rate": "خالص بچت کی شرح",

  // ---- Alerts ----
  "Active Alerts": "فعال الرٹس",
  "Add Alert": "الرٹ شامل کریں",
  "KSE-100": "کے ایس ای-100",
  "Add New Alert": "نیا الرٹ شامل کریں",
  Above: "اوپر",
  Below: "نیچے",
  "Notification History": "اطلاعات کی تاریخ",
  "Stock Price": "اسٹاک کی قیمت",
  "Bill Reminder": "بل یاد دہانی",
  Budget: "بجٹ",
  "Goal Milestone": "ہدف سنگ میل",
  "Create Alert": "الرٹ بنائیں",
  Push: "پش",

  // ---- Common / shell ----
  today: "آج",
  "Asalam-o-Alaikum,": "السلام علیکم،",
  // ---- User names (greeting) ----
  Usman: "عثمان",
  Investor: "سرمایہ کار",
  Ahmed: "احمد",
  Ali: "علی",
  Hassan: "حسن",
  Hussain: "حسین",
  Fatima: "فاطمہ",
  Ayesha: "عائشہ",
  Bilal: "بلال",
  Omar: "عمر",
  Zain: "زین",
  Saad: "سعد",
  Hamza: "حمزہ",
  Usama: "اسامہ",
  Talha: "طلحہ",
  Sara: "سارہ",
  Maryam: "مریم",
  Khan: "خان",
  Live: "لائیو",
  Notifications: "اطلاعات",
  "View all": "سب دیکھیں",
  Free: "مفت",
  plan: "پلان",
  "Search stocks (e.g. HBL)…": "اسٹاکس تلاش کریں (مثلاً HBL)…",
  "Search stocks": "اسٹاکس تلاش کریں",
  "Search transactions": "ٹرانزیکشنز تلاش کریں",
  "Search terms": "اصطلاحات تلاش کریں",
  Indicator: "اشارہ",
  Value: "قدر",
  Reading: "ریڈنگ",
  Neutral: "غیر جانبدار",
  Overbought: "اوور باٹ",
  Oversold: "اوور سولڈ",

  // ---- Signals ----
  "STRONG BUY": "اسٹرانگ بائی",
  BUY: "بائی",
  HOLD: "ہولڈ",
  SELL: "سیل",
  "STRONG SELL": "اسٹرانگ سیل",
  // V4 rating wording shown on the SignalBadge (bullish/bearish).
  "Strong Bullish": "مضبوط تیزی",
  Bullish: "تیزی",
  Bearish: "مندی",
  "Strong Bearish": "مضبوط مندی",
  "No Signal": "کوئی سگنل نہیں",
  All: "تمام",
  Vol: "حجم",
  Gainers: "بڑھنے والے",
  Losers: "گھٹنے والے",
  "Most Active": "سب سے فعال",

  // ---- Sectors ----
  Banking: "بینکنگ",
  Cement: "سیمنٹ",
  "Oil & Gas": "آئل اینڈ گیس",
  Fertilizer: "فرٹیلائزر",
  Textile: "ٹیکسٹائل",
  Power: "پاور",
  Pharma: "فارما",
  Tech: "ٹیک",
  Auto: "آٹو",

  // ---- Spending categories ----
  Food: "کھانا",
  Utilities: "یوٹیلیٹیز",
  Transport: "ٹرانسپورٹ",
  Shopping: "شاپنگ",
  Other: "دیگر",

  // ---- Stock company names ----
  "Habib Bank Limited": "حبیب بینک لمیٹڈ",
  "Engro Corporation": "اینگرو کارپوریشن",
  "Lucky Cement": "لکی سیمنٹ",
  "Oil & Gas Dev. Co.": "آئل اینڈ گیس ڈیولپمنٹ کمپنی",
  "Fauji Fertilizer Co.": "فوجی فرٹیلائزر کمپنی",
  "MCB Bank Limited": "ایم سی بی بینک لمیٹڈ",
  "United Bank Limited": "یونائیٹڈ بینک لمیٹڈ",
  "Nestlé Pakistan": "نیسلے پاکستان",
  "Pakistan State Oil": "پاکستان اسٹیٹ آئل",
  "Hub Power Company": "حب پاور کمپنی",
  "Food & Dining": "کھانا اور ڈائننگ",
  Groceries: "گروسری",
  Subscriptions: "سبسکرپشنز",
  Savings: "بچت",
  Income: "آمدنی",
  Expense: "اخراجات",

  // ---- Dashboard ----
  "Redirect PKR 5,000 from dining to your Hajj Fund.":
    "کھانے سے PKR 5,000 اپنے حج فنڈ کی طرف منتقل کریں۔",
  "You spent 15% more on dining this month — reallocating brings your goal 3 months closer. HBL is also flashing a Strong Buy, up 2.41% on rising volume.":
    "آپ نے اس ماہ کھانے پر 15% زیادہ خرچ کیا — دوبارہ تقسیم آپ کے ہدف کو 3 ماہ قریب لے آتی ہے۔ HBL بھی اسٹرانگ بائی دکھا رہا ہے، بڑھتے حجم پر 2.41% اوپر۔",

  // ---- Goal names + AI advice ----
  "Hajj Fund": "حج فنڈ",
  "Emergency Fund": "ایمرجنسی فنڈ",
  "Honda City": "ہونڈا سٹی",
  "Umrah 2026": "عمرہ 2026",
  "At PKR 25,000/month you'll reach this goal in 31 months. June dining overspend delayed this by ~6 days.":
    "PKR 25,000 ماہانہ پر آپ یہ ہدف 31 ماہ میں حاصل کر لیں گے۔ جون میں کھانے کے زیادہ اخراجات نے اسے ~6 دن مؤخر کر دیا۔",
  "Almost there! PKR 120,000 remaining. At current rate: 5 months.":
    "تقریباً پہنچ گئے! PKR 120,000 باقی ہیں۔ موجودہ رفتار پر: 5 ماہ۔",
  "This goal needs attention. Consider increasing monthly contribution by PKR 5,000.":
    "اس ہدف پر توجہ درکار ہے۔ ماہانہ رقم میں PKR 5,000 اضافے پر غور کریں۔",
  "You need to save PKR 15,833/month to reach this goal by your target.":
    "ہدف تک پہنچنے کے لیے آپ کو PKR 15,833 ماہانہ بچانا ہوگا۔",

  // ---- Finance ----
  "6-Month Overview": "6 ماہ کا جائزہ",
  In: "آمد",
  Out: "اخراج",
  "Add Bill": "بل شامل کریں",
  "Add Goal": "ہدف شامل کریں",
  "Amount (PKR)": "رقم (روپے)",
  "Please enter a valid amount.": "براہ کرم درست رقم درج کریں۔",
  Due: "واجب الادا",
  "Target date:": "ہدف کی تاریخ:",
  Target: "ہدف",
  Saved: "بچایا",
  "DUE SOON": "جلد واجب",
  UPCOMING: "آنے والا",
  "SNGPL Gas": "ایس این جی پی ایل گیس",
  "PTCL Internet": "پی ٹی سی ایل انٹرنیٹ",
  "Apartment Rent": "اپارٹمنٹ کرایہ",
  "Credit Card": "کریڈٹ کارڈ",
  "You've exceeded your dining budget by PKR 3,000. This is delaying your Hajj Fund goal by approximately 6 days.":
    "آپ نے کھانے کا بجٹ PKR 3,000 سے تجاوز کر لیا ہے۔ یہ آپ کے حج فنڈ ہدف کو تقریباً 6 دن مؤخر کر رہا ہے۔",
  "Shopping is PKR 3,050 over budget. Trimming this next month frees up cash for your Emergency Fund.":
    "شاپنگ بجٹ سے PKR 3,050 زیادہ ہے۔ اگلے ماہ اسے کم کرنے سے آپ کے ایمرجنسی فنڈ کے لیے رقم بچے گی۔",

  // ---- Alerts data ----
  "Stock Price Alert": "اسٹاک قیمت الرٹ",
  "Budget Alert": "بجٹ الرٹ",
  "HBL above PKR 150": "HBL، PKR 150 سے اوپر",
  "SNGPL Gas due in 3 days": "ایس این جی پی ایل گیس 3 دن میں واجب",
  "Food & Dining 80% of budget": "کھانا اور ڈائننگ بجٹ کا 80%",
  "Hajj Fund 50% reached": "حج فنڈ 50% مکمل",
  "LUCK below PKR 800": "LUCK، PKR 800 سے نیچے",
  "Created Jun 10": "10 جون کو بنایا",
  "Created Jun 12": "12 جون کو بنایا",
  "Recurring monthly": "ماہانہ تکرار",
  "June 2025": "جون 2025",
  "One-time": "ایک بار",
  "1 day before": "1 دن پہلے",
  "3 days before": "3 دن پہلے",
  "7 days before": "7 دن پہلے",
  "HBL crossed above MA50 — Strong Buy signal triggered":
    "HBL نے MA50 عبور کر لیا — اسٹرانگ بائی سگنل فعال",
  "K-Electric bill due in 3 days — PKR 18,420": "کے-الیکٹرک بل 3 دن میں واجب — PKR 18,420",
  "Food & Dining budget 92% used — PKR 32,340 of 35,000":
    "کھانا اور ڈائننگ بجٹ کا 92% استعمال — 35,000 میں سے PKR 32,340",
  "Great news! Emergency Fund reached 60% of target":
    "خوشخبری! ایمرجنسی فنڈ ہدف کے 60% تک پہنچ گیا",

  // ---- PSX ----
  "KSE-100 Index": "کے ایس ای-100 انڈیکس",
  "AI Analysis": "اے آئی تجزیہ",
  "KSE-100 is trading above both MA20 and MA50 with strong volume confirmation. RSI at 58 — bullish momentum without being overbought. Banking and Tech sectors leading gains today.":
    "کے ایس ای-100 مضبوط حجم کی تصدیق کے ساتھ MA20 اور MA50 دونوں سے اوپر ٹریڈ کر رہا ہے۔ RSI 58 پر — اوور باٹ ہوئے بغیر تیزی کی رفتار۔ بینکنگ اور ٹیک شعبے آج برتری میں ہیں۔",
  "Based on technical indicators only. Not financial advice.":
    "صرف تکنیکی اشاروں کی بنیاد پر۔ مالی مشورہ نہیں۔",
  "Pakistan Stock Exchange's benchmark index — tracks the 100 largest companies by market cap. The headline number quoted as 'the market'.":
    "پاکستان اسٹاک ایکسچینج کا بینچ مارک انڈیکس — مارکیٹ کیپ کے لحاظ سے 100 سب سے بڑی کمپنیوں کو ٹریک کرتا ہے۔ یہی نمبر 'مارکیٹ' کے طور پر پیش کیا جاتا ہے۔",
  "Tracks the 30 most liquid, large companies on the PSX using a free-float methodology — a snapshot of blue-chip performance.":
    "فری-فلوٹ طریقہ کار سے PSX کی 30 سب سے زیادہ لیکویڈ، بڑی کمپنیوں کو ٹریک کرتا ہے — بلیو چپ کارکردگی کا منظر۔",
  "The KSE-Meezan Index — 30 Sharia-compliant (Islamic) companies, screened to exclude interest-based and non-permissible businesses.":
    "کے ایس ای-میزان انڈیکس — 30 شریعت کے مطابق (اسلامی) کمپنیاں، جو سودی اور ناجائز کاروبار کو خارج کر کے منتخب کی گئی ہیں۔",
  "Captures every eligible listed company on the PSX — the broadest measure of the whole market's direction.":
    "PSX کی ہر اہل لسٹڈ کمپنی کو شامل کرتا ہے — پوری مارکیٹ کی سمت کا سب سے وسیع پیمانہ۔",

  // ---- Learn Hub ----
  "From KSE basics to technical analysis — in plain Urdu and English.":
    "کے ایس ای کی بنیادی باتوں سے تکنیکی تجزیے تک — سادہ اردو اور انگریزی میں۔",
  "Beginner Investor": "ابتدائی سرمایہ کار",
  "Learning Paths": "سیکھنے کے راستے",
  "Follow a structured track or explore freely": "ایک منظم راستہ اپنائیں یا آزادانہ دریافت کریں",
  Lessons: "اسباق",
  Glossary: "لغت",
  "Flashcard Mode": "فلیش کارڈ موڈ",
  Flashcards: "فلیش کارڈز",
  "Continue Path": "راستہ جاری رکھیں",
  "Start Path": "راستہ شروع کریں",
  "Video + Article": "ویڈیو + مضمون",
  Article: "مضمون",
  "In Progress": "جاری",
  "Tap to flip": "پلٹنے کے لیے ٹیپ کریں",
  "Got it": "سمجھ گیا",
  "Review Again": "دوبارہ دیکھیں",
  "Ask AI Tutor": "اے آئی ٹیوٹر سے پوچھیں",
  "Ask AI": "اے آئی سے پوچھیں",
  "Thinking…": "سوچ رہا ہے…",
  // NafaIQ Assistant (the "Ask NafaIQ AI" panel)
  "Hi! I can add transactions, track bills and goals, manage your portfolio and watchlist, and answer questions about your money. Type or tap the mic.":
    "سلام! میں ٹرانزیکشنز شامل کر سکتا ہوں، بلز اور اہداف پر نظر رکھ سکتا ہوں، آپ کا پورٹ فولیو اور واچ لسٹ سنبھال سکتا ہوں، اور آپ کے پیسوں سے متعلق سوالات کے جواب دے سکتا ہوں۔ لکھیں یا مائیک دبائیں۔",
  "Ask or tell me what to do…": "پوچھیں یا بتائیں کیا کرنا ہے…",
  "Sign in to use NafaIQ Assistant": "نفع آئی کیو اسسٹنٹ استعمال کرنے کے لیے سائن ان کریں",
  "Daily assistant limit reached — it resets tomorrow.":
    "آج کی اسسٹنٹ حد مکمل ہو گئی — یہ کل دوبارہ سیٹ ہو جائے گی۔",
  "Add transaction of 1200 for food via Meezan card":
    "میزان کارڈ سے کھانے کی 1200 کی ٹرانزیکشن شامل کریں",
  "How much did I spend this month?": "میں نے اس مہینے کتنا خرچ کیا؟",
  "Alert me when any goal reaches 50%": "کسی بھی ہدف کے 50% پہنچنے پر مجھے اطلاع دیں",
  "Add MEBL to my watchlist": "MEBL کو میری واچ لسٹ میں شامل کریں",
  // Voice input
  "Speak your command": "اپنا حکم بولیں",
  "Stop recording": "ریکارڈنگ روکیں",
  "Voice input isn't supported in this browser.":
    "اس براؤزر میں صوتی ان پٹ کی سہولت دستیاب نہیں ہے۔",
  "Microphone access was blocked. Enable it in your browser settings.":
    "مائیکروفون تک رسائی بلاک ہے۔ اسے اپنے براؤزر کی ترتیبات میں فعال کریں۔",
  "I couldn't hear anything. Try again.": "مجھے کچھ سنائی نہیں دیا۔ دوبارہ کوشش کریں۔",
  "Transcription failed": "تحریر میں تبدیلی ناکام",
  // Action confirmation card
  "Add transaction": "ٹرانزیکشن شامل کریں",
  "Add bill": "بل شامل کریں",
  "Create savings goal": "بچت کا ہدف بنائیں",
  "Add to goal": "ہدف میں شامل کریں",
  "Add holding": "ہولڈنگ شامل کریں",
  "Record trade": "ٹریڈ ریکارڈ کریں",
  "Add goal alert": "ہدف کا الرٹ شامل کریں",
  "Add price alert": "قیمت کا الرٹ شامل کریں",
  "Add to watchlist": "واچ لسٹ میں شامل کریں",
  "Remove from watchlist": "واچ لسٹ سے ہٹائیں",
  Merchant: "دکاندار",
  // "Amount (PKR)", "Shares" and "Symbol" are already defined earlier in this
  // dictionary with the same translations — re-adding them here is a duplicate
  // key, which TypeScript rejects.
  "Target (PKR)": "ہدف (روپے)",
  "Already saved (PKR)": "پہلے سے جمع شدہ (روپے)",
  "Average cost (PKR)": "اوسط لاگت (روپے)",
  "Price (PKR)": "قیمت (روپے)",
  "Fees (PKR)": "فیس (روپے)",
  "Paid via": "ادائیگی بذریعہ",
  "Due date": "آخری تاریخ",
  "Target date": "ہدف کی تاریخ",
  "Alert at (%)": "الرٹ اس فیصد پر (%)",
  "When price is": "جب قیمت ہو",
  Quantity: "مقدار",
  Side: "قسم",
  Bill: "بل",
  Goal: "ہدف",
  Note: "نوٹ",
  expense: "خرچ",
  income: "آمدنی",
  buy: "خریداری",
  sell: "فروخت",
  above: "سے اوپر",
  below: "سے نیچے",
  "Choose…": "منتخب کریں…",
  "Still needed": "ابھی درکار ہے",
  Confirm: "تصدیق کریں",
  Done: "مکمل",
  "Something went wrong": "کچھ غلط ہو گیا",
  "Lesson not found": "سبق نہیں ملا",
  "Back to Learn Hub": "لرن ہب پر واپس",
  "In This Lesson": "اس سبق میں",
  "Bookmark Lesson": "سبق بک مارک کریں",
  Bookmarked: "بک مارک شدہ",
  Beginner: "ابتدائی",
  Intermediate: "درمیانہ",
  Complete: "مکمل",
  Locked: "مقفل",
  "PSX Investor Starter": "PSX سرمایہ کار آغاز",
  "From zero to your first trade": "صفر سے آپ کی پہلی ٹریڈ تک",
  "Technical Analysis": "تکنیکی تجزیہ",
  "Charts, patterns, and indicators": "چارٹس، پیٹرنز اور اشارے",
  "Islamic Finance": "اسلامی مالیات",
  "Halal investing principles": "حلال سرمایہ کاری کے اصول",
  "Budget, save, and grow": "بجٹ بنائیں، بچائیں اور بڑھائیں",
  "What is a Candlestick?": "کینڈل اسٹک کیا ہے؟",
  "Understanding RSI": "آر ایس آئی کو سمجھنا",
  "Sector Heatmap Guide": "سیکٹر ہیٹ میپ گائیڈ",
  "What is a Stop-Loss?": "اسٹاپ لاس کیا ہے؟",
  "Dividend Yield": "ڈیویڈنڈ یِلڈ",
  "5 Candle Patterns": "5 کینڈل پیٹرنز",
  "50/30/20 Budget Rule": "50/30/20 بجٹ اصول",
  "How PSX Works": "PSX کیسے کام کرتا ہے",
  "Halal Investing & Islamic Finance": "حلال سرمایہ کاری اور اسلامی مالیات",
  "Understanding P/E Ratio": "قیمت آمدنی تناسب کو سمجھنا",

  // ---- Plans ----
  "Enter App": "ایپ میں داخل ہوں",
  "Simple, honest pricing": "سادہ، ایماندار قیمتیں",
  "Start free. Upgrade when you're ready for real-time data and unlimited AI insights.":
    "مفت شروع کریں۔ جب آپ ریئل ٹائم ڈیٹا اور لامحدود اے آئی بصیرت کے لیے تیار ہوں تو اپ گریڈ کریں۔",
  Monthly: "ماہانہ",
  Yearly: "سالانہ",
  "SAVE 20%": "20% بچائیں",
  "MOST POPULAR": "سب سے مقبول",
  "/ mo": "/ ماہ",
  "Billed annually — 20% off": "سالانہ بل — 20% رعایت",
  "Compare plans": "پلانز کا موازنہ",
  Feature: "خصوصیت",
  Pro: "پرو",
  Premium: "پریمیم",
  Custom: "حسبِ ضرورت",
  "Get Started": "شروع کریں",
  "Contact Us": "ہم سے رابطہ کریں",
  "Get started with the essentials": "بنیادی چیزوں کے ساتھ آغاز کریں",
  "For serious investors": "سنجیدہ سرمایہ کاروں کے لیے",
  "For families & power users": "خاندانوں اور پاور صارفین کے لیے",
  "Delayed PSX data": "تاخیر سے PSX ڈیٹا",
  "1 portfolio": "1 پورٹ فولیو",
  "Basic finance tracker": "بنیادی فنانس ٹریکر",
  "Zakat calculator": "زکوٰۃ کیلکولیٹر",
  "3 AI Advisor queries / month": "3 اے آئی ایڈوائزر سوالات / ماہ",
  "Real-time PSX data": "ریئل ٹائم PSX ڈیٹا",
  "Unlimited AI Advisor": "لامحدود اے آئی ایڈوائزر",
  "Full Haqeeqi Daulat breakdown": "مکمل حقیقی دولت تفصیل",
  "Unlimited portfolios & watchlists": "لامحدود پورٹ فولیوز اور واچ لسٹس",
  "Halal screening filters": "حلال اسکریننگ فلٹرز",
  "Priority alerts": "ترجیحی الرٹس",
  "Everything in Pro": "پرو کی ہر چیز",
  "Multi-account / family tracking": "ملٹی اکاؤنٹ / فیملی ٹریکنگ",
  "Advanced data export": "ایڈوانس ڈیٹا ایکسپورٹ",
  "Priority support": "ترجیحی سپورٹ",

  // ---- Stock detail ----
  "Back to Market": "مارکیٹ پر واپس",
  "AI Technical Analysis": "اے آئی تکنیکی تجزیہ",
  "Recent News": "حالیہ خبریں",
  "Add to Watchlist": "واچ لسٹ میں شامل کریں",
  "Add to Portfolio": "پورٹ فولیو میں شامل کریں",
  "Set Price Alert": "قیمت الرٹ سیٹ کریں",
  "Market Cap": "مارکیٹ کیپ",
  "P/E Ratio": "قیمت آمدنی تناسب",
  EPS: "ای پی ایس",
  "52W High": "52 ہفتہ بلند",
  "52W Low": "52 ہفتہ کم",
  "Avg Volume": "اوسط حجم",
  "Book Value": "بک ویلیو",
  "This is AI-generated technical analysis only. Not financial advice.":
    "یہ صرف اے آئی سے تیار کردہ تکنیکی تجزیہ ہے۔ مالی مشورہ نہیں۔",

  // ---- Portfolio report + misc ----
  "— AI signals suggest reviewing these positions.":
    "— اے آئی سگنلز ان پوزیشنز کا جائزہ لینے کی تجویز دیتے ہیں۔",
  "Your Portfolio Report — June 2025": "آپ کی پورٹ فولیو رپورٹ — جون 2025",
  "Diversification Analysis": "تنوع کا تجزیہ",
  "Risk Assessment": "خطرے کا جائزہ",
  Opportunities: "مواقع",
  "Suggested Actions": "تجویز کردہ اقدامات",
  "Your portfolio is moderately diversified across 4 sectors. However, Oil & Gas represents 34% of your holdings which increases sector concentration risk. Consider adding a Tech or FMCG stock to balance exposure.":
    "آپ کا پورٹ فولیو 4 شعبوں میں معتدل طور پر متنوع ہے۔ تاہم، آئل اینڈ گیس آپ کی ملکیت کا 34% ہے جو شعبہ ارتکاز کا خطرہ بڑھاتا ہے۔ توازن کے لیے ایک ٹیک یا ایف ایم سی جی اسٹاک شامل کرنے پر غور کریں۔",
  "Medium risk profile. FFC is showing a SELL signal with RSI at 38 — consider reviewing this position. LUCK (HOLD) is underperforming vs sector avg.":
    "درمیانہ خطرہ پروفائل۔ FFC، RSI 38 کے ساتھ سیل سگنل دکھا رہا ہے — اس پوزیشن کا جائزہ لیں۔ LUCK (ہولڈ) شعبے کی اوسط کے مقابلے میں کمزور کارکردگی دکھا رہا ہے۔",
  "HBL and UBL in the Banking sector are both showing Strong Buy signals. Your existing HBL position is +20.4% — consider whether to take partial profits.":
    "بینکنگ شعبے میں HBL اور UBL دونوں اسٹرانگ بائی سگنل دکھا رہے ہیں۔ آپ کی موجودہ HBL پوزیشن +20.4% ہے — جزوی منافع لینے پر غور کریں۔",
  "1. Review FFC position (SELL signal active)\n2. Consider reducing Oil & Gas concentration below 25%\n3. HBL approaching resistance at 150 — set a price alert":
    "1۔ FFC پوزیشن کا جائزہ لیں (سیل سگنل فعال)\n2۔ آئل اینڈ گیس ارتکاز 25% سے کم کرنے پر غور کریں\n3۔ HBL، 150 پر مزاحمت کے قریب — قیمت الرٹ سیٹ کریں",
  "34% of portfolio in Oil & Gas provides partial hedge against rupee weakness.":
    "پورٹ فولیو کا 34% آئل اینڈ گیس میں روپے کی کمزوری کے خلاف جزوی تحفظ فراہم کرتا ہے۔",
  "BULLISH · Confidence 72%": "تیزی · اعتماد 72%",

  // ---- Learn Hub (extended) ----
  "lessons complete": "اسباق مکمل",
  "5 Day Streak": "5 دن کا تسلسل",
  "Lessons Done": "اسباق مکمل",
  "XP Earned": "ایکس پی حاصل",
  "Beginner Level": "ابتدائی سطح",
  lessons: "اسباق",
  "Est:": "تخمینہ:",
  min: "منٹ",
  complete: "مکمل",
  "No terms found for": "کوئی اصطلاح نہیں ملی",
  "Deck Complete!": "ڈیک مکمل!",
  "You reviewed all": "آپ نے تمام",
  terms: "اصطلاحات",
  "terms.": "اصطلاحات کا جائزہ لیا۔",
  "Restart Deck": "ڈیک دوبارہ شروع کریں",
  Exit: "باہر نکلیں",
  "Ask about investing…": "سرمایہ کاری کے بارے میں پوچھیں…",
  "What is the KSE-100 index?": "کے ایس ای-100 انڈیکس کیا ہے؟",
  "How do I start investing in PSX?": "میں پی ایس ایکس میں سرمایہ کاری کیسے شروع کروں؟",
  "Explain candlestick charts simply": "کینڈل اسٹک چارٹس آسان الفاظ میں سمجھائیں",
  "Hi! I'm your NafaIQ tutor. Ask me anything about PSX investing, terms, or strategies.":
    "سلام! میں آپ کا نفع آئی کیو ٹیوٹر ہوں۔ پی ایس ایکس سرمایہ کاری، اصطلاحات یا حکمت عملی کے بارے میں کچھ بھی پوچھیں۔",
  "Sorry, something went wrong. Please try again.":
    "معذرت، کچھ غلط ہو گیا۔ براہ کرم دوبارہ کوشش کریں۔",

  // ---- Lesson page ----
  Bookmark: "بک مارک",
  read: "پڑھنے کا وقت",
  Hide: "چھپائیں",
  Read: "پڑھیں",
  "Article Version": "مضمون ورژن",
  "Mark Video as Watched": "ویڈیو کو دیکھا ہوا نشان زد کریں",
  "Watch at least 80% of the video to mark as complete":
    "مکمل کے طور پر نشان زد کرنے کے لیے کم از کم 80% ویڈیو دیکھیں",
  "Test Your Understanding — Take the Quiz": "اپنی سمجھ بوجھ آزمائیں — کوئز دیں",
  questions: "سوالات",
  "Earn up to 50 XP": "50 ایکس پی تک حاصل کریں",
  "You've completed this lesson": "آپ نے یہ سبق مکمل کر لیا ہے",
  Previous: "پچھلا",
  Next: "اگلا",
  "Video loading…": "ویڈیو لوڈ ہو رہی ہے…",
  "Back to Lesson": "سبق پر واپس",
  "Up to 50 XP": "50 ایکس پی تک",
  "Knowledge Check": "علم کی جانچ",
  Question: "سوال",
  of: "میں سے",
  "Correct! ": "درست! ",
  "Not quite. ": "بالکل نہیں۔ ",
  "See Results": "نتائج دیکھیں",
  "Next Question": "اگلا سوال",
  "Quiz Results": "کوئز کے نتائج",
  "Added to your profile": "آپ کے پروفائل میں شامل",
  "XP total": "کل ایکس پی",
  "Continue Learning": "سیکھنا جاری رکھیں",
  "Retake Quiz": "کوئز دوبارہ دیں",
  "Perfect Score! Ustād level understanding!": "بہترین اسکور! استاد جیسی سمجھ بوجھ!",
  "Great work! One more review and you'll nail it.": "بہترین کام! ایک اور جائزہ اور آپ کامیاب!",
  "📖 Keep learning — review the lesson and retry.":
    "📖 سیکھتے رہیں — سبق کا جائزہ لیں اور دوبارہ کوشش کریں۔",
  "💪 Don't give up — re-read and try again!": "💪 ہمت نہ ہاریں — دوبارہ پڑھیں اور کوشش کریں!",
  "AI Tutor": "اے آئی ٹیوٹر",
  "Ask anything about this lesson": "اس سبق کے بارے میں کچھ بھی پوچھیں",
  "Powered by AI": "اے آئی سے چلایا گیا",
  "just now": "ابھی",
  "Ask about this lesson…": "اس سبق کے بارے میں پوچھیں…",
  "Hi! I'm here to help you understand": "السلام علیکم! میں آپ کو سمجھانے کے لیے حاضر ہوں",
  "What would you like to know?": "آپ کیا جاننا چاہیں گے؟",
  "Video coming soon": "ویڈیو جلد آ رہی ہے",
  "A video walkthrough is in production. Read the full lesson below for now.":
    "ویڈیو وضاحت تیاری میں ہے۔ فی الحال نیچے مکمل سبق پڑھیں۔",

  // ---- Stock detail (extended) ----
  Confidence: "اعتماد",
  "Confidence 5/6 indicators": "اعتماد 5/6 اشارے",
  "RSI (14)": "آر ایس آئی (14)",
  "MA20 vs Price": "MA20 بمقابلہ قیمت",
  "MA50 vs Price": "MA50 بمقابلہ قیمت",
  MACD: "ایم اے سی ڈی",
  "Volume Trend": "حجم کا رجحان",
  "Bollinger Band": "بولنگر بینڈ",
  "Neutral-Bullish": "غیر جانبدار-تیزی",
  "Price > MA20": "قیمت > MA20",
  "Price > MA50": "قیمت > MA50",
  "Bullish cross": "تیزی کا کراس",
  Rising: "بڑھ رہا",
  "Mid-upper": "درمیانی-اوپر",
  "Room to grow": "بڑھنے کی گنجائش",
  "Overall: STRONG BUY · 5 of 6 indicators bullish":
    "مجموعی: اسٹرانگ بائی · 6 میں سے 5 اشارے تیزی میں",
  "is showing strong bullish momentum. Price has broken above MA50 with significantly above-average volume — a classic confirmation signal. RSI at 61 leaves room before overbought territory. The only caution is Bollinger Band position suggesting the move may slow near 148–150. Consider a stop-loss at the MA20 level (~136).":
    "مضبوط تیزی کی رفتار دکھا رہا ہے۔ قیمت نمایاں طور پر اوسط سے زیادہ حجم کے ساتھ MA50 سے اوپر نکل گئی ہے — ایک کلاسک تصدیقی سگنل۔ RSI 61 پر اوور باٹ ہونے سے پہلے گنجائش چھوڑتا ہے۔ واحد احتیاط بولنگر بینڈ کی پوزیشن ہے جو بتاتی ہے کہ حرکت 148–150 کے قریب سست ہو سکتی ہے۔ MA20 سطح (~136) پر اسٹاپ لاس پر غور کریں۔",
  "Banking sector rallies as policy rate held steady":
    "پالیسی ریٹ مستحکم رہنے پر بینکنگ شعبے میں تیزی",
  "Foreign inflows lift PSX to fresh highs": "غیر ملکی سرمایہ PSX کو نئی بلندیوں پر لے گیا",
  "Analysts eye resistance near key levels": "ماہرین کلیدی سطحوں کے قریب مزاحمت پر نظر رکھے ہوئے",
  Positive: "مثبت",
  "2h ago": "2 گھنٹے پہلے",
  "5h ago": "5 گھنٹے پہلے",
  "1d ago": "1 دن پہلے",

  // ---- Plans (extended) ----
  "Data delay": "ڈیٹا تاخیر",
  Portfolios: "پورٹ فولیوز",
  "AI Advisor queries": "اے آئی ایڈوائزر سوالات",
  Watchlists: "واچ لسٹس",
  "Halal screening": "حلال اسکریننگ",
  "Support tier": "سپورٹ درجہ",
  "15 min delayed": "15 منٹ تاخیر",
  "Real-time": "ریئل ٹائم",
  Unlimited: "لامحدود",
  "3 / month": "3 / ماہ",
  Basic: "بنیادی",
  Priority: "ترجیحی",
  Community: "کمیونٹی",
  Standard: "معیاری",
  "Add Contribution": "رقم جمع کریں",
  "Bill name": "بل کا نام",
  "Due date (e.g. Jun 25)": "آخری تاریخ (مثلاً 25 جون)",
  "Goal name": "ہدف کا نام",
  "Mark as paid": "ادا شدہ نشان زد کریں",
  "New goal created. Start contributing to track your progress.":
    "نیا ہدف بن گیا۔ پیش رفت دیکھنے کے لیے رقم جمع کرنا شروع کریں۔",
  "Please enter a bill name.": "براہ کرم بل کا نام درج کریں۔",
  "Please enter a goal name.": "براہ کرم ہدف کا نام درج کریں۔",
  "Please enter a valid price.": "براہ کرم درست قیمت درج کریں۔",
  "Please enter a valid target amount.": "براہ کرم درست ہدف رقم درج کریں۔",
  "Target amount (PKR)": "ہدف رقم (PKR)",
  "Target date (optional)": "ہدف کی تاریخ (اختیاری)",
  // Goals
  // Bills
  // Budget categories
  // Lessons
  Advanced: "ماہر",
  // Alerts
  // Quiz
  "correct so far": "اب تک درست",
  "correct out of": "درست از",
  answered: "حل شدہ",
  "Time left": "باقی وقت",
  "Why this matters": "یہ کیوں اہم ہے",
  "Your progress": "آپ کی پیش رفت",
  "Score 2+ to complete this lesson.": "سبق مکمل کرنے کے لیے 2 یا زیادہ درست کریں۔",
  Explanation: "وضاحت",
  Correct: "درست",
  // Urdu QA preview
  "Understand, Learn, Grow": "سمجھو، سیکھو، بڑھو",
  "Your net worth at a glance": "ایک نظر میں آپ کی کل مالیت",
  "Track your portfolio, spending and PSX signals in one calm place.":
    "اپنے پورٹ فولیو، اخراجات اور پی ایس ایکس سگنلز کو ایک پُرسکون جگہ پر دیکھیں۔",
  "Monthly Expenses": "ماہانہ اخراجات",
  "Search stocks (e.g. HBL)": "اسٹاکس تلاش کریں (مثلاً HBL)",
  Symbol: "علامت",
  "AI Suggestion": "اے آئی تجویز",
  "Back to Dashboard": "ڈیش بورڈ پر واپس",
  "Urdu QA Preview": "اردو کیو اے پیش منظر",

  // ---- Accessibility / aria-labels ----
  "Open menu": "مینو کھولیں",
  "Toggle theme": "تھیم تبدیل کریں",
  "User menu": "صارف مینو",
  "Collapse sidebar": "سائڈبار سکیڑیں",
  Collapse: "سکیڑیں",

  // ---- LearnHub RAG search ----
  "Search LearnHub…": "لرن ہب میں تلاش کریں…",
  "Searching…": "تلاش جاری ہے…",
  "No results found": "کوئی نتائج نہیں ملے",
  Quiz: "کوئز",
  Path: "راستہ",
  // Related lessons card + the glossary's semantic fallback.
  "Related topics": "متعلقہ موضوعات",
  "No AI explanation available right now.": "ابھی اے آئی وضاحت دستیاب نہیں ہے۔",
  "Closest matches": "قریب ترین نتائج",

  // ---- Quiz AI explanation (opt-in, on top of the static explanation) ----
  "Explain in depth": "تفصیل سے سمجھائیں",
  "AI explanation": "اے آئی وضاحت",
  "Based on": "ماخذ",

  // ---- Lesson AI summary card (opt-in, end of the reading page) ----
  "AI generated": "اے آئی سے تیار",
  "Common mistake": "عام غلطی",
  "Summarised by AI from this lesson. Not financial advice.":
    "اس سبق سے اے آئی کے ذریعے خلاصہ۔ یہ مالی مشورہ نہیں ہے۔",
  "Daily AI limit reached — try again tomorrow.":
    "آج کی اے آئی حد پوری ہو گئی — کل دوبارہ کوشش کریں۔",
  // ---- Help & Support ----
  "Help & Support": "مدد اور سپورٹ",
  "Find support options and account controls for your NafaIQ workspace.":
    "اپنے NafaIQ ورک اسپیس کے لیے سپورٹ آپشنز اور اکاؤنٹ کنٹرولز دیکھیں۔",
  "Account settings": "اکاؤنٹ کی ترتیبات",
  "Manage profile, notifications, plan, and integrations.":
    "پروفائل، اطلاعات، پلان اور انٹیگریشنز کا انتظام کریں۔",
  "Open Settings": "ترتیبات کھولیں",
  Support: "سپورٹ",
  "For urgent issues, contact the NafaIQ team from your registered email.":
    "فوری مسائل کے لیے اپنی رجسٹرڈ ای میل سے NafaIQ ٹیم سے رابطہ کریں۔",
  "Support email": "سپورٹ ای میل",
  "Phone support": "فون سپورٹ",

  // ---- AI Insights / report chrome ----
  "AI Investing Platform": "اے آئی سرمایہ کاری پلیٹ فارم",
  "AI Insights": "اے آئی انسائٹس",
  "Generate market, portfolio, finance, and stock analysis from one focused workspace.":
    "مارکیٹ، پورٹ فولیو، مالیات اور اسٹاک تجزیہ ایک ہی ورک اسپیس سے بنائیں۔",
  "analysis areas": "تجزیاتی شعبے",
  "portfolio window": "پورٹ فولیو مدت",
  "PSX context": "PSX تناظر",
  "Market brief": "مارکیٹ بریف",
  "Open the AI read on today's PSX conditions.": "آج کے PSX حالات پر اے آئی تجزیہ کھولیں۔",
  "Portfolio report": "پورٹ فولیو رپورٹ",
  "Analyze diversification, risk, and rebalancing opportunities.":
    "تنوع، خطرے اور ری بیلنسنگ کے مواقع کا تجزیہ کریں۔",
  "Finance report": "مالیاتی رپورٹ",
  "Review spending, budgets, savings, and money habits.":
    "اخراجات، بجٹس، بچت اور مالی عادات کا جائزہ لیں۔",
  "AI Report Center": "اے آئی رپورٹ سینٹر",
  "Stock AI Analysis": "اسٹاک اے آئی تجزیہ",
  "Search any PSX symbol to open its dedicated AI analysis card and signal context.":
    "کسی بھی PSX علامت کو تلاش کریں تاکہ اس کا مخصوص اے آئی تجزیہ اور سگنل تناظر کھل سکے۔",
  "Search stocks (e.g. HBL, ENGRO)...": "اسٹاک تلاش کریں (مثلاً HBL، ENGRO)...",
  "Use the sidebar AI button for conversational investing help and PSX education.":
    "سرمایہ کاری میں گفتگو کے ذریعے مدد اور PSX تعلیم کے لیے سائیڈ بار کا اے آئی بٹن استعمال کریں۔",
  "Get a plain-English analysis - diversification score, risk assessment, top opportunities, and suggested rebalancing.":
    "سادہ زبان میں تجزیہ حاصل کریں - تنوع، خطرے کا جائزہ، اہم مواقع، اور ری بیلنسنگ کے تعلیمی نکات۔",
  "Get a plain-English analysis - income vs expense trends, budget health, savings rate assessment, and personalized money tips.":
    "سادہ زبان میں تجزیہ حاصل کریں - آمدنی بمقابلہ اخراجات، بجٹ کی صحت، بچت کی شرح، اور مالی نکات۔",
  "Executive summary": "خلاصہ",
  "Financial health": "مالی صحت",
  "Income analysis": "آمدنی کا تجزیہ",
  "Expense analysis": "اخراجات کا تجزیہ",
  "Cash flow analysis": "کیش فلو تجزیہ",
  "Savings analysis": "بچت کا تجزیہ",
  "Budget analysis": "بجٹ کا تجزیہ",
  "Goal progress": "اہداف کی پیش رفت",
  "Emergency fund review": "ایمرجنسی فنڈ کا جائزہ",
  "Portfolio health": "پورٹ فولیو صحت",
  "Profit/loss analysis": "نفع/نقصان کا تجزیہ",
  "Allocation analysis": "تقسیم کا تجزیہ",
  "Risk analysis": "خطرے کا تجزیہ",
  "Holdings review": "ہولڈنگز کا جائزہ",
  "Action plan": "عملی منصوبہ",
  "Data quality": "ڈیٹا معیار",
  "View sources": "ماخذ دیکھیں",
  low: "کم",
  medium: "درمیانہ",
  high: "زیادہ",
  now: "ابھی",
  "next 30 days": "اگلے 30 دن",
  "next 90 days": "اگلے 90 دن",
  ongoing: "جاری",
  items: "آئٹمز",
  "Details available": "تفصیل دستیاب ہے",

  // ---- Monetary Desk ----
  "Monetary Desk": "مانیٹری ڈیسک",
  Rates: "ریٹس",
  "Live monetary desk": "لائیو مالی ڈیسک",
  "Reference FX, dollar conversion, and Pakistan bullion prices with source checks.":
    "سورس چیکس کے ساتھ حوالہ FX، ڈالر کنورژن، اور پاکستان بلین قیمتیں۔",
  Updated: "اپ ڈیٹ",
  Source: "ماخذ",
  Cadence: "تازگی",
  Quality: "معیار",
  "Cross-checked": "کراس چیکڈ",
  "Needs review": "جائزہ درکار",
  "Single source": "واحد ماخذ",
  "Dollar to PKR": "ڈالر سے روپیہ",
  "for 1 US Dollar": "1 امریکی ڈالر کے لیے",
  Cached: "کیشڈ",
  "Currency converter": "کرنسی کنورٹر",
  "Convert popular currencies through live USD rates.":
    "مقبول کرنسیوں کو لائیو امریکی ڈالر ریٹس کے ذریعے تبدیل کریں۔",
  "Swap currencies": "کرنسیاں تبدیل کریں",
  "Refresh live rates": "لائیو ریٹس ریفریش کریں",
  "Popular currencies": "مقبول کرنسیاں",
  "Indicative value of one unit converted to Pakistani Rupees.":
    "ایک یونٹ کی پاکستانی روپے میں اندازاً قیمت۔",
  Base: "بنیاد",
  "Loading monetary data...": "مالی ڈیٹا لوڈ ہو رہا ہے...",
  "Unable to load live monetary data.": "لائیو مالی ڈیٹا لوڈ نہیں ہو سکا۔",
  "The live provider may be temporarily unavailable. Try again in a moment.":
    "لائیو فراہم کنندہ عارضی طور پر دستیاب نہیں ہو سکتا۔ کچھ دیر بعد دوبارہ کوشش کریں۔",
  Refresh: "ریفریش",
  "Gold and silver spot rates are temporarily unavailable.":
    "سونے اور چاندی کے اسپاٹ ریٹس عارضی طور پر دستیاب نہیں ہیں۔",
  "Reference interbank/spot data converted to PKR and cross-checked when secondary sources are available. Local premiums, taxes, spreads, and jeweller rates can differ.":
    "حوالہ انٹربینک/اسپاٹ ڈیٹا روپے میں تبدیل کیا گیا ہے اور ثانوی ذرائع دستیاب ہوں تو کراس چیک کیا جاتا ہے۔ مقامی پریمیم، ٹیکس، اسپریڈز، اور جیولر ریٹس مختلف ہو سکتے ہیں۔",
  "Gold or silver spot rates were not available from the live provider.":
    "لائیو فراہم کنندہ سے سونے یا چاندی کے اسپاٹ ریٹس دستیاب نہیں تھے۔",
  "Live refresh failed; showing the last cached snapshot.":
    "لائیو ریفریش ناکام ہوا؛ آخری کیشڈ ڈیٹا دکھایا جا رہا ہے۔",
  "No secondary reference was available for this refresh.":
    "اس ریفریش کے لیے کوئی ثانوی حوالہ دستیاب نہیں تھا۔",
  "USD/PKR was cross-checked against independent references.":
    "USD/PKR کو آزاد حوالہ ذرائع کے ساتھ کراس چیک کیا گیا۔",
  "USD/PKR differs from one or more reference sources; treat as indicative.":
    "USD/PKR ایک یا زیادہ حوالہ ذرائع سے مختلف ہے؛ اسے اندازاً سمجھیں۔",
  "Gold price": "سونے کی قیمت",
  "Silver price": "چاندی کی قیمت",
  Gold: "سونا",
  Silver: "چاندی",
  "Indicative spot": "اندازاً اسپاٹ",
  "Per gram": "فی گرام",
  "Per 10g": "فی 10 گرام",
  "Per tola": "فی تولہ",
  "US Dollar": "امریکی ڈالر",
  Euro: "یورو",
  "British Pound": "برطانوی پاؤنڈ",
  "UAE Dirham": "یو اے ای درہم",
  "Saudi Riyal": "سعودی ریال",
  "Chinese Yuan": "چینی یوآن",
  "Japanese Yen": "جاپانی ین",
  "Canadian Dollar": "کینیڈین ڈالر",
  "Australian Dollar": "آسٹریلین ڈالر",
  "Pakistani Rupee": "پاکستانی روپیہ",
  "Base dollar rate": "بنیادی ڈالر ریٹ",
  "USD equivalent": "امریکی ڈالر کے برابر",

  // Remove-holding chooser (sold vs added by mistake).
  // NOTE: lowercase "shares" is a distinct key from "Shares" above — it is used
  // mid-phrase ("150 shares @ 320"), so both spellings are needed.
  "Remove Holding": "ہولڈنگ ہٹائیں",
  "Record Sale": "فروخت درج کریں",
  shares: "حصص",
  "What happened to this position?": "اس پوزیشن کے ساتھ کیا ہوا؟",
  "I sold it": "میں نے یہ بیچ دیا",
  "Records the sale at your price and adds the proceeds to your income.":
    "آپ کی قیمت پر فروخت درج کرتا ہے اور حاصل شدہ رقم آپ کی آمدنی میں شامل کرتا ہے۔",
  "Just remove it": "صرف ہٹا دیں",
  "Added by mistake. Undoes the purchase; no new income is recorded. Income from any real past sales is kept.":
    "غلطی سے شامل کیا گیا۔ خریداری واپس لے لیتا ہے؛ کوئی نئی آمدنی درج نہیں ہوتی۔ ماضی کی حقیقی فروخت سے آمدنی محفوظ رہتی ہے۔",
  "Sale price per share (PKR)": "فی حصص فروخت کی قیمت (روپے)",
  "Brokerage fees (PKR, optional)": "بروکریج فیس (روپے، اختیاری)",
  Proceeds: "حاصل شدہ رقم",
  "Cost basis": "لاگت کی بنیاد",
  "Realised P&L": "حقیقی نفع/نقصان",
  "Enter the price per share you sold at.": "وہ فی حصص قیمت درج کریں جس پر آپ نے بیچا۔",
  "Fees must be a positive number.": "فیس ایک مثبت عدد ہونی چاہیے۔",
  "Recording…": "درج ہو رہا ہے…",
  "Confirm Sale": "فروخت کی تصدیق کریں",
  Back: "واپس",
  Cancel: "منسوخ کریں",
  "FX source": "ایف ایکس ماخذ",
  "Metal source": "دھاتوں کا ماخذ",
  "Spot fallback": "اسپاٹ فال بیک",
  "Reference FX is converted through USD/PKR. Gold and silver prefer Pakistan sarafa/APGJSA market rates when available; local premiums, taxes, spreads, and jeweller rates can differ.":
    "FX ریٹ USD/PKR کے ذریعے تبدیل کیا جاتا ہے۔ سونا اور چاندی دستیاب ہونے پر پاکستان صرافہ/APGJSA مارکیٹ ریٹس استعمال کرتے ہیں؛ مقامی پریمیم، ٹیکس، اسپریڈز، اور جیولر ریٹس مختلف ہو سکتے ہیں۔",
  "Gold or silver prices were not available from the live providers.":
    "لائیو فراہم کنندگان سے سونے یا چاندی کی قیمتیں دستیاب نہیں تھیں۔",
  "Pakistan bullion rates were unavailable for one or more metals; using international spot converted to PKR as an indicative fallback.":
    "ایک یا زیادہ دھاتوں کے لیے پاکستان بلین ریٹس دستیاب نہیں تھے؛ اشارتی فال بیک کے طور پر بین الاقوامی اسپاٹ ریٹ کو PKR میں تبدیل کیا گیا ہے۔",
  "Pakistan sarafa market": "پاکستان صرافہ مارکیٹ",
  "Pakistan APGJSA market rate": "پاکستان APGJSA مارکیٹ ریٹ",
  "Indicative international spot converted to PKR":
    "اشارتی بین الاقوامی اسپاٹ جو PKR میں تبدیل ہوا",
  // ---------------------------------------------------------------------
  // Admin console
  //
  // Scope note: prose is translated; *identifiers* are not. Permission slugs
  // (`users.suspend`), flag keys (`maintenance_mode`), audit action codes
  // (`admin.user.tier`) and database column names stay in English because they
  // are the literal values stored server-side — translating them would make
  // them impossible to match against logs, the API or the docs.
  // ---------------------------------------------------------------------
  "NafaIQ Admin": "نفع آئی کیو ایڈمن",
  "Operations console": "آپریشنز کنسول",
  Admin: "ایڈمن",
  People: "لوگ",
  Operations: "آپریشنز",
  Platform: "پلیٹ فارم",
  Users: "صارفین",
  "Roles & Access": "کردار اور رسائی",
  "Market Data": "مارکیٹ ڈیٹا",
  Signals: "سگنلز",
  "AI Operations": "اے آئی آپریشنز",
  "Feature Flags": "فیچر فلیگز",
  "Audit Log": "آڈٹ لاگ",
  "System Health": "سسٹم ہیلتھ",
  "Back to app": "ایپ پر واپس",
  "Expand sidebar": "سائیڈبار کھولیں",
  "Open navigation": "نیویگیشن کھولیں",
  "Close navigation": "نیویگیشن بند کریں",
  "Account menu": "اکاؤنٹ مینو",
  "Skip to content": "مواد پر جائیں",
  "Admin sections": "ایڈمن حصے",
  "No roles": "کوئی کردار نہیں",
  "Toggle language": "زبان تبدیل کریں",

  // Command palette
  "Open command palette": "کمانڈ پیلیٹ کھولیں",
  "Search…": "تلاش کریں…",
  "Search sections and users…": "حصے اور صارفین تلاش کریں…",
  "Search sections…": "حصے تلاش کریں…",
  "Go to": "یہاں جائیں",
  navigate: "نیویگیٹ",
  open: "کھولیں",

  // Common actions
  Retry: "دوبارہ کوشش",
  Export: "ایکسپورٹ",
  Columns: "کالمز",
  "Visible columns": "دکھائی دینے والے کالمز",
  "Clear selection": "انتخاب صاف کریں",
  "Clear filters": "فلٹرز صاف کریں",
  Details: "تفصیلات",
  Inspect: "معائنہ",
  Suspend: "معطل کریں",
  Reactivate: "بحال کریں",
  Restrict: "محدود کریں",
  Assign: "تفویض کریں",
  Revoke: "منسوخ کریں",
  Save: "محفوظ کریں",
  Reset: "ری سیٹ",
  "Add note": "نوٹ شامل کریں",
  Manage: "انتظام",
  "Manage roles": "کرداروں کا انتظام",
  "Full log": "مکمل لاگ",
  "Open full profile": "مکمل پروفائل کھولیں",
  "Refresh now": "ابھی ریفریش کریں",
  Prev: "پچھلا",
  Rows: "قطاریں",

  // States
  "Loading…": "لوڈ ہو رہا ہے…",
  "No results": "کوئی نتیجہ نہیں",
  "Nothing here yet.": "ابھی یہاں کچھ نہیں ہے۔",
  "You're offline": "آپ آف لائن ہیں",
  "This didn't load": "یہ لوڈ نہیں ہوا",
  "You don't have access to this": "آپ کو اس تک رسائی نہیں ہے",
  "Not tracked yet": "ابھی ٹریک نہیں کیا گیا",
  Unavailable: "دستیاب نہیں",
  "Verifying administrator access…": "ایڈمنسٹریٹر رسائی کی تصدیق ہو رہی ہے…",

  // Table / filter labels
  User: "صارف",
  Status: "حالت",
  Joined: "شمولیت",
  "Last seen": "آخری بار",
  Actor: "عمل کنندہ",
  Resource: "ریسورس",
  When: "کب",
  Tier: "درجہ",
  Roles: "کردار",
  Administrator: "ایڈمنسٹریٹر",
  Administrators: "ایڈمنسٹریٹرز",
  "Admin since": "ایڈمن تب سے",
  "All statuses": "تمام حالتیں",
  "All plans": "تمام پلانز",
  "All time": "تمام وقت",
  "Last 24 hours": "پچھلے 24 گھنٹے",
  "Last 7 days": "پچھلے 7 دن",
  "Last 30 days": "پچھلے 30 دن",
  "Last 90 days": "پچھلے 90 دن",
  Active: "فعال",
  Suspended: "معطل",
  Restricted: "محدود",
  Success: "کامیاب",
  Failure: "ناکام",

  // Page headings
  Activity: "سرگرمی",
  "Subscription tier": "سبسکرپشن درجہ",
  "Administrative roles": "انتظامی کردار",
  "Admin notes": "ایڈمن نوٹس",
  "Current roles": "موجودہ کردار",
  "Access & roles": "رسائی اور کردار",
  Notes: "نوٹس",
  History: "تاریخ",
  "Role assignment history": "کردار تفویض کی تاریخ",
  "Permission matrix": "اجازت میٹرکس",
  "Current admins": "موجودہ ایڈمنز",
  "Total users": "کل صارفین",
  "New this week": "اس ہفتے نئے",
  "Active this week": "اس ہفتے فعال",
  "Recent admin activity": "حالیہ ایڈمن سرگرمی",
  "Subscription tiers": "سبسکرپشن درجات",
  "Platform engagement": "پلیٹ فارم مصروفیت",
  "Tier distribution": "درجات کی تقسیم",
  "Manage tiers": "درجات کا انتظام",
  "Delivery health": "ڈیلیوری کی صحت",
  "Alert events": "الرٹ ایونٹس",
  "Most-watched symbols": "سب سے زیادہ دیکھے گئے سمبلز",
  Database: "ڈیٹابیس",
  Scheduler: "شیڈولر",
  Environment: "ماحول",
  "Process role": "پروسیس رول",
  selected: "منتخب",
  "Select all rows on this page": "اس صفحے کی تمام قطاریں منتخب کریں",
  "No records match the filters you've applied. Try widening or clearing them.":
    "آپ کے لگائے گئے فلٹرز سے کوئی ریکارڈ میل نہیں کھاتا۔ انہیں وسیع یا صاف کریں۔",
  "The request failed. This is usually transient — retry, or check System Health.":
    "درخواست ناکام رہی۔ یہ عام طور پر عارضی ہوتا ہے — دوبارہ کوشش کریں یا سسٹم ہیلتھ دیکھیں۔",
  "The console can't reach the network. Data shown may be stale.":
    "کنسول نیٹ ورک تک نہیں پہنچ سکتا۔ دکھایا گیا ڈیٹا پرانا ہو سکتا ہے۔",
  Retire: "ریٹائر کریں",
  Restore: "بحال کریں",
  "Alerts oversight": "الرٹس کی نگرانی",
  "Price alerts": "قیمت الرٹس",
  "App alerts": "ایپ الرٹس",
  "Users with alerts": "الرٹس والے صارفین",
  "Paid tiers": "ادا شدہ درجات",
  "Free tier": "مفت درجہ",
  "NafaIQ is undergoing scheduled maintenance. Some data may be unavailable until it completes.":
    "نفع آئی کیو کی طے شدہ دیکھ بھال جاری ہے۔ مکمل ہونے تک کچھ ڈیٹا دستیاب نہ ہو سکتا ہے۔",
  // Plan entitlements
  "Plan entitlements": "پلان استحقاقات",
  Distribution: "تقسیم",
  "Subscription sections": "سبسکرپشن حصے",
  Entitlement: "استحقاق",
  Limits: "حدود",
  "AI quotas": "اے آئی کوٹے",
  Features: "خصوصیات",
  "Watchlist symbols": "واچ لسٹ سمبلز",
  "Holdings per portfolio": "فی پورٹ فولیو ہولڈنگز",
  "Finance history (days)": "مالیاتی تاریخ (دن)",
  "AI tutor / day": "اے آئی ٹیوٹر / دن",
  "AI reports / period": "اے آئی رپورٹس / مدت",
  "Report period": "رپورٹ کی مدت",
  "Email alerts": "ای میل الرٹس",
  "Push alerts": "پش الرٹس",
  "Data export": "ڈیٹا ایکسپورٹ",
  "Multi-currency": "کثیر کرنسی",
  "Real-time PSX": "ریئل ٹائم پی ایس ایکس",
  "Full screener": "مکمل اسکرینر",
  Webhooks: "ویب ہکس",
  "API access": "اے پی آئی رسائی",
  "Set to unlimited": "لامحدود مقرر کریں",
  unsaved: "غیر محفوظ",
  "Save changes": "تبدیلیاں محفوظ کریں",
  Discard: "رد کریں",
  "Reset all": "سب ری سیٹ کریں",
  "Unsaved changes to": "غیر محفوظ تبدیلیاں:",
  "Last updated": "آخری تازہ کاری",

  // Account actions
  "Account actions": "اکاؤنٹ اقدامات",
  "Force sign-out": "زبردستی سائن آؤٹ",
  "Send password reset": "پاس ورڈ ری سیٹ بھیجیں",
  "Resend verification": "تصدیق دوبارہ بھیجیں",
  "Send email": "ای میل بھیجیں",
  "Danger zone": "خطرناک زون",
  "Anonymise account": "اکاؤنٹ گمنام کریں",
  "Anonymise this account": "اس اکاؤنٹ کو گمنام کریں",
  "Anonymise permanently": "مستقل طور پر گمنام کریں",
  "Display name cleared": "ڈسپلے نام صاف کر دیا گیا",
  "Search users…": "صارفین تلاش کریں…",
  "Search by email or name…": "ای میل یا نام سے تلاش کریں…",
  // --- Reliability: errors + bug reports -------------------------------
  Reliability: "قابلِ اعتماد",
  Errors: "خرابیاں",
  "Bug Reports": "بگ رپورٹس",
  Error: "خرابی",
  "Open issues": "کھلے مسائل",
  "Active (24h)": "فعال (24 گھنٹے)",
  "Events (24h)": "واقعات (24 گھنٹے)",
  Events: "واقعات",
  "Distinct unresolved failures": "الگ الگ غیر حل شدہ خرابیاں",
  "Groups that fired in the last day": "گروپ جو پچھلے دن چلے",
  "Total occurrences": "کل واقعات",
  "All sources": "تمام ذرائع",
  "Search message or route…": "پیغام یا راستہ تلاش کریں…",
  "No errors captured": "کوئی خرابی ریکارڈ نہیں ہوئی",
  Occurrences: "واقعات",
  "First seen": "پہلی بار",
  Fingerprint: "فنگر پرنٹ",
  "Sample stack": "نمونہ اسٹیک",
  "Recent occurrences": "حالیہ واقعات",
  "Signed out": "سائن آؤٹ",
  Ignore: "نظر انداز کریں",
  Investigating: "تحقیق جاری",
  "Mark resolved": "حل شدہ نشان زد کریں",
  "Error updated": "خرابی اپ ڈیٹ ہو گئی",
  "Errors this user hit": "اس صارف کو پیش آنے والی خرابیاں",
  "Captured automatically. Most recent first.": "خودکار طور پر ریکارڈ شدہ۔ تازہ ترین پہلے۔",
  "No errors recorded for this user": "اس صارف کے لیے کوئی خرابی ریکارڈ نہیں",

  Report: "رپورٹ",
  Reporter: "رپورٹ کنندہ",
  Reported: "رپورٹ کیا گیا",
  Open: "کھلا",
  Category: "زمرہ",
  "All categories": "تمام زمرے",
  "Search reports…": "رپورٹس تلاش کریں…",
  "No reports": "کوئی رپورٹ نہیں",
  "Awaiting a first response": "پہلے جواب کا منتظر",
  "all time": "ہر وقت",
  "What the user said": "صارف نے کیا کہا",
  Context: "سیاق و سباق",
  Page: "صفحہ",
  "App version": "ایپ ورژن",
  "Linked error": "منسلک خرابی",
  "Current reply": "موجودہ جواب",
  "Reply to the reporter": "رپورٹ کنندہ کو جواب دیں",
  Resolve: "حل کریں",
  "Won't fix": "درست نہیں کریں گے",
  "Report updated": "رپورٹ اپ ڈیٹ ہو گئی",

  // --- User-facing report dialog ---------------------------------------
  "Report a problem": "مسئلہ رپورٹ کریں",
  "What kind of problem?": "کس قسم کا مسئلہ؟",
  "Something is broken": "کچھ خراب ہے",
  "The numbers look wrong": "اعداد غلط لگ رہے ہیں",
  "Billing or plan": "بلنگ یا پلان",
  Suggestion: "تجویز",
  "Something else": "کچھ اور",
  Summary: "خلاصہ",
  "What happened?": "کیا ہوا؟",
  "Send report": "رپورٹ بھیجیں",
  "A sentence or two is enough.": "ایک دو جملے کافی ہیں۔",
  "Your previous reports": "آپ کی پچھلی رپورٹس",
  "Being looked at": "دیکھا جا رہا ہے",
  Closed: "بند",

  // --- Dashboard reliability strip --------------------------------------
  "unresolved error": "غیر حل شدہ خرابی",
  "unresolved errors": "غیر حل شدہ خرابیاں",
  "active today": "آج فعال",
  "user report awaiting reply": "جواب کی منتظر صارف رپورٹ",
  "user reports awaiting reply": "جواب کی منتظر صارف رپورٹس",
  "AI-generated · Source grounded": "AI سے تیار کردہ · مستند ذرائع پر مبنی",
  "Practice Quiz": "مشقی کوئز",
  "Practice only": "صرف مشق",
  "Practice your understanding. Official progress is unchanged.":
    "اپنی سمجھ کی مشق کریں۔ سرکاری پیش رفت میں کوئی تبدیلی نہیں ہوگی۔",
  "Generated quizzes do not affect your XP or learning streak.":
    "تیار کردہ کوئز مشق کے طور پر محفوظ ہوتے ہیں اور سرکاری پیش رفت یا سیکھنے کے تسلسل کو متاثر نہیں کرتے۔",
  "Sources used": "استعمال شدہ ذرائع",
  "Key ideas from this lesson": "اس سبق کے اہم نکات",
  "Key terms": "اہم اصطلاحات",
  "Suggested next topics": "اگلے مجوزہ موضوعات",
  "Study flashcards": "فلیش کارڈز سے مشق کریں",
  "Educational content only — not financial advice.": "یہ صرف تعلیمی مواد ہے، مالی مشورہ نہیں۔",
  "Generate 3–5 minute video lesson": "3–5 منٹ کا ویڈیو سبق بنائیں",
  "Generating video…": "ویڈیو تیار ہو رہی ہے…",
  "Lesson source": "سبق کا ذریعہ",
  "Choose a topic": "موضوع منتخب کریں",
  "Upload a PDF": "پی ڈی ایف اپ لوڈ کریں",
  "Select a private PDF": "نجی پی ڈی ایف منتخب کریں",
  "PDF only · Up to 15 MB and 100 pages · Never added to the public corpus":
    "صرف پی ڈی ایف · زیادہ سے زیادہ 15 ایم بی اور 100 صفحات · عوامی مواد میں کبھی شامل نہیں کیا جاتا",
  "Lesson focus (optional)": "سبق کی توجہ (اختیاری)",
  "Optional focus, e.g. explain the dividend policy":
    "اختیاری توجہ، مثلاً ڈیویڈنڈ پالیسی کی وضاحت کریں",
  "Create from PDF": "پی ڈی ایف سے سبق بنائیں",
  "Uploading…": "اپ لوڈ ہو رہا ہے…",
  "Private PDF": "نجی پی ڈی ایف",
  "Delete lesson": "سبق حذف کریں",
  "Delete this lesson and its private uploaded files?":
    "کیا یہ سبق اور اس کی نجی اپ لوڈ شدہ فائلیں حذف کر دی جائیں؟",
  "The lesson could not be deleted. Please try again.":
    "سبق حذف نہیں ہو سکا۔ براہ کرم دوبارہ کوشش کریں۔",
  "PDF exceeds the 15 MB limit.": "پی ڈی ایف 15 ایم بی کی حد سے بڑی ہے۔",
  "Reading and checking your private PDF": "آپ کی نجی پی ڈی ایف پڑھی اور جانچی جا رہی ہے",
};
