-- PSX Module Tables
-- Run via supabase db push or manually via Supabase Dashboard

-- 1. Market snapshot (refreshed every 5s during session)
CREATE TABLE IF NOT EXISTS public.psx_market_snapshot (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol      TEXT NOT NULL,
    price       NUMERIC(12,2),
    change      NUMERIC(12,2),
    change_pct  NUMERIC(8,4),
    volume      BIGINT DEFAULT 0,
    day_high    NUMERIC(12,2),
    day_low     NUMERIC(12,2),
    refreshed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(symbol)
);
CREATE INDEX IF NOT EXISTS idx_psx_ms_sym ON public.psx_market_snapshot(symbol);
CREATE INDEX IF NOT EXISTS idx_psx_ms_refreshed ON public.psx_market_snapshot(refreshed_at DESC);
ALTER TABLE public.psx_market_snapshot ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read market snapshot" ON public.psx_market_snapshot FOR SELECT USING (true);
GRANT SELECT ON public.psx_market_snapshot TO anon, authenticated;
GRANT ALL ON public.psx_market_snapshot TO service_role;

-- 2. Daily OHLCV history
CREATE TABLE IF NOT EXISTS public.psx_ohlcv (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol  TEXT NOT NULL,
    date    DATE NOT NULL,
    open    NUMERIC(12,2) DEFAULT 0,
    high    NUMERIC(12,2) DEFAULT 0,
    low     NUMERIC(12,2) DEFAULT 0,
    close   NUMERIC(12,2) DEFAULT 0,
    volume  BIGINT DEFAULT 0,
    UNIQUE(symbol, date)
);
CREATE INDEX IF NOT EXISTS idx_psx_ohlcv_sym_date ON public.psx_ohlcv(symbol, date);
ALTER TABLE public.psx_ohlcv ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read ohlcv" ON public.psx_ohlcv FOR SELECT USING (true);
GRANT SELECT ON public.psx_ohlcv TO anon, authenticated;
GRANT ALL ON public.psx_ohlcv TO service_role;

-- 3. Fundamentals
CREATE TABLE IF NOT EXISTS public.psx_fundamentals (
    symbol      TEXT PRIMARY KEY,
    eps         NUMERIC(12,2),
    pe          NUMERIC(8,2),
    pb          NUMERIC(8,2),
    div_yield   NUMERIC(8,4),
    payout      NUMERIC(8,4),
    roe         NUMERIC(8,4),
    refreshed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE public.psx_fundamentals ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read fundamentals" ON public.psx_fundamentals FOR SELECT USING (true);
GRANT SELECT ON public.psx_fundamentals TO anon, authenticated;
GRANT ALL ON public.psx_fundamentals TO service_role;

-- 4. Company profile
CREATE TABLE IF NOT EXISTS public.psx_profile (
    symbol          TEXT PRIMARY KEY,
    name            TEXT NOT NULL DEFAULT '',
    sector          TEXT,
    listed_shares   BIGINT,
    free_float      BIGINT,
    refreshed_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE public.psx_profile ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read profile" ON public.psx_profile FOR SELECT USING (true);
GRANT SELECT ON public.psx_profile TO anon, authenticated;
GRANT ALL ON public.psx_profile TO service_role;

-- 5. Announcements
CREATE TABLE IF NOT EXISTS public.psx_announcements (
    id          TEXT PRIMARY KEY,
    symbol      TEXT,
    posted_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    title       TEXT NOT NULL DEFAULT '',
    category    TEXT,
    url         TEXT,
    body_cached TEXT,
    refreshed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_psx_ann_sym ON public.psx_announcements(symbol, posted_at DESC);
CREATE INDEX IF NOT EXISTS idx_psx_ann_posted ON public.psx_announcements(posted_at DESC);
ALTER TABLE public.psx_announcements ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read announcements" ON public.psx_announcements FOR SELECT USING (true);
GRANT SELECT ON public.psx_announcements TO anon, authenticated;
GRANT ALL ON public.psx_announcements TO service_role;

-- 6. Dividends
CREATE TABLE IF NOT EXISTS public.psx_dividends (
    announcement_id     TEXT PRIMARY KEY,
    symbol              TEXT NOT NULL,
    ex_date             DATE,
    announcement_date   DATE,
    payout_type         TEXT,
    per_share           NUMERIC(10,4),
    bonus_pct           NUMERIC(10,4),
    refreshed_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_psx_div_sym ON public.psx_dividends(symbol, ex_date DESC);
ALTER TABLE public.psx_dividends ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read dividends" ON public.psx_dividends FOR SELECT USING (true);
GRANT SELECT ON public.psx_dividends TO anon, authenticated;
GRANT ALL ON public.psx_dividends TO service_role;

-- 7. Index EOD
CREATE TABLE IF NOT EXISTS public.psx_index_eod (
    code    TEXT NOT NULL,
    date    DATE NOT NULL,
    close   NUMERIC(12,2) DEFAULT 0,
    volume  BIGINT,
    UNIQUE(code, date)
);
CREATE INDEX IF NOT EXISTS idx_psx_idx_code ON public.psx_index_eod(code, date);
ALTER TABLE public.psx_index_eod ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read index eod" ON public.psx_index_eod FOR SELECT USING (true);
GRANT SELECT ON public.psx_index_eod TO anon, authenticated;
GRANT ALL ON public.psx_index_eod TO service_role;

-- 8. Real-time ticks (high-write, Supabase Realtime broadcast)
CREATE TABLE IF NOT EXISTS public.psx_ticks (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol      TEXT NOT NULL,
    time        TIMESTAMPTZ NOT NULL DEFAULT now(),
    price       NUMERIC(12,2),
    volume      BIGINT DEFAULT 0,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_psx_tick_sym_time ON public.psx_ticks(symbol, time DESC);
ALTER TABLE public.psx_ticks ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read ticks" ON public.psx_ticks FOR SELECT USING (true);
GRANT SELECT ON public.psx_ticks TO anon, authenticated;
GRANT ALL ON public.psx_ticks TO service_role;
-- Required for realtime broadcast on inserts
ALTER TABLE public.psx_ticks REPLICA IDENTITY FULL;

-- 9. User watchlist (RLS: users see only their own)
CREATE TABLE IF NOT EXISTS public.psx_watchlist (
    user_id     UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    symbol      TEXT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY(user_id, symbol)
);
ALTER TABLE public.psx_watchlist ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users own their watchlist" ON public.psx_watchlist FOR ALL TO authenticated USING (auth.uid() = user_id);
GRANT ALL ON public.psx_watchlist TO authenticated;

-- 10. User alerts (RLS: users see only their own)
CREATE TABLE IF NOT EXISTS public.psx_alerts (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    symbol      TEXT NOT NULL,
    type        TEXT NOT NULL,
    condition   TEXT NOT NULL,
    threshold   NUMERIC(12,4),
    enabled     BOOLEAN NOT NULL DEFAULT true,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_psx_alerts_user ON public.psx_alerts(user_id, symbol);
ALTER TABLE public.psx_alerts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users own their alerts" ON public.psx_alerts FOR ALL TO authenticated USING (auth.uid() = user_id);
GRANT ALL ON public.psx_alerts TO authenticated;

-- 11. User portfolios (RLS)
CREATE TABLE IF NOT EXISTS public.psx_portfolios (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    name        TEXT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE public.psx_portfolios ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users own their portfolios" ON public.psx_portfolios FOR ALL TO authenticated USING (auth.uid() = user_id);
GRANT ALL ON public.psx_portfolios TO authenticated;

-- 12. Holdings within a portfolio (RLS via parent portfolio join)
CREATE TABLE IF NOT EXISTS public.psx_holdings (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id    BIGINT REFERENCES public.psx_portfolios(id) ON DELETE CASCADE,
    symbol          TEXT NOT NULL,
    shares          BIGINT NOT NULL DEFAULT 0,
    avg_cost        NUMERIC(12,2) NOT NULL DEFAULT 0,
    purchased_at    DATE,
    UNIQUE(portfolio_id, symbol)
);
ALTER TABLE public.psx_holdings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users own their holdings through portfolio" 
    ON public.psx_holdings FOR ALL TO authenticated 
    USING (
        EXISTS (
            SELECT 1 FROM public.psx_portfolios 
            WHERE public.psx_portfolios.id = public.psx_holdings.portfolio_id 
            AND public.psx_portfolios.user_id = auth.uid()
        )
    );
GRANT ALL ON public.psx_holdings TO authenticated;
